### ISSUE TITLE
Will need to update Billing Library on Android

### ISSUE THREAD

**Issue by danieltsai1230** [codenameone/CodenameOne#3706] opened 2023-06-02 23:03 UTC
We've detected that this app is using an old version of Google Play Billing. From November 1, 2023, all app updates must use Billing Library version 5 or newer.

Action required: Please verify your publicly available APKs are updated to the latest version of the Play Billing Library. This includes any APK or App Bundle rolled out in production.

**Comment by shai-almog** [comment] 2023-06-03 03:17
This is in relation to https://stackoverflow.com/questions/76386696/play-billing-library-version-deprecation-issues

**Comment by danieltsai1230** [comment] 2023-07-03 13:44
Is the issue related to querying subscribe status of the order on the server-side program?

**Comment by danieltsai1230** [comment] 2023-07-03 13:55
1. Starting on August 2, 2023, all new apps must use Billing Library version 5 or newer. By November 1, 2023, all updates to existing apps must use Billing Library version 5 or newer. 
(https://developer.android.com/google/play/billing/deprecation-faq).

**Comment by shai-almog** [comment] 2023-07-22 04:54
@danieltsai1230 yes this is about the deprecation of the existing API level we use in Google Play.

@shannah new apps using this API will be blocked on August, is there an estimate on this issue?

**Comment by shannah** [comment] 2023-07-22 14:34
> Play Billing Library 5 and 6 include the deprecated methods querySkuDetailsAsync and BillingFlowParams.Builder.setSkuDetails that takes [SkuDetails](https://developer.android.com/reference/com/android/billingclient/api/SkuDetails) as a billing flow parameter. This means that you can gradually move to Play Billing Library 6 by planning different stages of migration.
> 
> As a first step to migration, you can just [update the library version](https://developer.android.com/google/play/billing/migrate-gpblv6#update-google), leave your catalog and backend as they are, and test your app while it still uses the deprecated methods. If you are not using queryPurchases, launchPriceChangeFlow, or setVrPurchaseFlow, it should still work as intended. Afterwards, you can iterate to fully adopt the [new subscription features released in May 2022](https://developer.android.com/google/play/billing/compatibility).

https://developer.android.com/google/play/billing/migrate-gpblv6

Since we are "not using queryPurchases, launchPriceChangeFlow, or setVrPurchaseFlow, it should still work as intended"

I have added a build hint `android.billingclient.version` that can be used to override the billing client version.  This will be available in the next release.  E.g. `android.billingclient.version=6.0.0`.

**Comment by danieltsai1230** [comment] 2023-07-22 15:14
Should I migrate the server-side program?
I use the sample server-side released by cn1.
ReceiptsScheduler.validateAndSaveReceipt

**Comment by danieltsai1230** [comment] 2023-07-29 10:52
I haven't seen the build hint `android.billingclient.version.`
Let me know once you have done it.
I don't use Maven.
Thank you.

**Comment by shannah** [comment] 2023-07-29 16:30
This went out in the release yesterday.  Please give it a try.
You can verify that it "worked" by downloading sources and looking at the billing client library dependency in your gradle file.
You should have something like `implementation 'com.android.billingclient:billing:6.0.0`

**Comment by shannah** [comment] 2023-07-30 14:57
Note: I have tested this build hint in an app and it appears to work, both on the server-side and client-side.  Server-side required no changes, and I'm using the same logic as the sample IAP server that you are using @danieltsai1230 .

**Comment by danieltsai1230** [comment] 2023-07-30 16:07
Thank you so much. I will try it.

**Comment by danieltsai1230** [comment] 2023-07-31 04:35
I sent my app to cn1 server for Android build.
Wait for 10 mins but cn1 server still can't finish the process.
![2023-07-31 12 30 37](https://github.com/codenameone/CodenameOne/assets/25316953/6d421af3-f991-4606-adbe-00e95b2ab788)

**Comment by danieltsai1230** [comment] 2023-07-31 08:40
I sent for Android build but still got the depreciated warning.

**Comment by shannah** [comment] 2023-07-31 17:27
Did you confirm that it is using version 6.0.0 in the billing client library version in your build.gradle file?

**Comment by danieltsai1230** [comment] 2023-07-31 22:51
I don't see any words mention to version 6.0.0.
Should I add `android.billingclient.version=6.0.0` to build hint?

**Comment by danieltsai1230** [comment] 2023-07-31 23:01
I add `android.billingclient.version=6.0.0` to build hint but saw ` implementation 'com.android.billingclient:billing:4.0.0'` in build.gradle.

**Comment by shannah** [comment] 2024-04-07 11:27
This was fixed by making gradle 8 the default on the build server, which includes newer dependencies for play libs.

**Closed by shannah** 2024-04-07 11:27 UTC
