### ISSUE TITLE
Use a custom allocator in the new VM to speed up memory allocation/GC

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1341] opened 2015-03-27 16:25 UTC
Original [issue 1342](https://code.google.com/p/codenameone/issues/detail?id=1342) created by codenameone on 2015-02-08T14:52:47.000Z:

Its important that there would be an option to turn it off so we can use the native OS debugging tools. However, a custom implementation of malloc/free could allow us to significantly speed up allocations when compared to C since we can rely on the single thread nature of the GC.

**Comment by shannah** [comment] 2017-08-18 17:34
Closing since this is a duplicate of https://github.com/codenameone/CodenameOne/issues/2112 and that issue has a clear action path.

**Closed by shannah** 2017-08-18 17:34 UTC
Labels: Priority-Medium, Type-Enhancement
