### ISSUE TITLE
clipRect is "out of control"

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1817] opened 2016-07-02 23:04 UTC
g.clipRect(x,y,w,h) is able to set the clipping region anywhere on the screen, even to places
not owned by any codename1 application.  Screen shot attached, note that the rogue use of
cliprect was able to overwrite the top and bottom bars that are not part of the client application.

This behavoir is common to android devices, but doesn't seem to be a problem on IOS
![screenshot_2016-07-02-15-53-39](https://cloud.githubusercontent.com/assets/5963076/16542832/95cf6a08-406e-11e6-9896-078db59df6a7.png)

**Comment by codenameone** [comment] 2016-07-03 05:16
This requires a testcase

**Comment by ddyer0** [comment] 2016-07-03 19:48
attached
[Dtest.zip](https://github.com/codenameone/CodenameOne/files/345268/Dtest.zip)

**Comment by codenameone** [comment] 2016-07-05 04:41
Can you please provide an embedded test case and not a zip. This makes it impossible to test and much slower to review bugs: https://www.codenameone.com/blog/issue-submission-guideline.html

**Comment by ddyer0** [comment] 2016-07-05 07:21
You need to be a little more flexible accepting free assistance for your product.  As
previously noted, I use zips because your upload facility won't accept .java or .res files.

You'll need some sort of image in your theme file with the name "black-chip-np.jpg"

````java
//
// this version shows the clipping bug seen on android devices
//

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Graphics;
import com.codename1.ui.layouts.BorderLayout;

import java.util.Random;


public class Dtest  {
	
    /**
     * Draw an image from/to particular rectangles with rescaling.  Note that
     * this uses left,top,right,bottomt coordinates rather than left,top,width,height 
     * @param gc	the gc to be written to
     * @param im	the image to be written from
     * @param dx	dest left
     * @param dy	dest top
     * @param dx2 dest right
     * @param dy2 dest bottom
     * @param fx  source left
     * @param fy  source top
     * @param fx2 source right
     * @param fy2 source bottom
      */
    public static void drawImage(Graphics gc,Image im,
			int dx,int dy,int dx2,int dy2,
			int fx,int fy,int fx2,int fy2
			)
{	if(gc!=null)
	{	int w = dx2-dx;
		int h = dy2-dy;
		int sw = fx2-fx;
		int sh = fy2-fy;
		int imw = im.getWidth();
		int imh = im.getHeight();
		double xscale = w/(double)sw;
		double yscale = h/(double)sh;
	   	int[]clip = gc.getClip();
	   	//gc.clipRect(dx,dy,w,h);			// combine with proper clipping region
	   	gc.setClip(dx,dy,w,h);		// runs wild, can write anywhere!
	   	int finx = dx-(int)(fx*xscale);
	   	int finy = dy-(int)(fy*yscale);
	   	int finw = (int)(imw*xscale);
	   	int finh = (int)(imh*yscale);
	   	gc.drawImage(im,finx,finy,finw,finh);
  	gc.setClip(clip);
	}
}
 
    private Form current;
    @SuppressWarnings("unused")
	private Resources theme;
    private Image chip ;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");
        chip = Resources.getGlobalResources().getImage("black-chip-np.jpg");
        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    int loops = 0;
   
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi >>0 World");
         current = hi;
        hi.setLayout(new BorderLayout());
        hi.addComponent(BorderLayout.CENTER, new Label("Hi Overlay World 2") {

            @Override
            public void paint(Graphics g) {
             	int w = getWidth();
            	int h = getHeight();
             	g.setColor(0x8f8f9f7f);
            	g.fillRect(0,0,w,h);
            	drawImage(g,chip,-loops,-loops,w+loops,h+loops,0,0,chip.getWidth(),chip.getHeight());
            	g.drawImage(chip,100,100);
            	loops++;
            
            	repaint();
            }
            
        });
        hi.show();
        
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }
    
    public void destroy() {
    }
}
````

**Comment by codenameone** [comment] 2016-07-06 07:40
You can embed Java just fine and attach necessary resources just fine. We are helping each other so this is a two way street. 

Which point of our reasoning for wanting an embed rather than a zip file doesn't make sense? 

If you attach zips I can't search and I have to download, unzip/grep etc. just to see if your code makes any sense. With this issue I can review and test almost immediately.

**Comment by ddyer0** [comment] 2016-07-06 16:09
embedding is fine for sufficiently simple problems.  Not so fine if multiple files and resources are involved.   It would simplify matters if you published a standard bug test project, so that the 
source folder could be uploaded for you to drop into place.

**Comment by ddyer0** [comment] 2016-10-01 20:35
This problem is still extant on android (after other recent cliprect issues were fixed).
I also noticed that if you run the test program on IOS it seems to work, but if you rotate
the device the protected areas of the screen get trashed and not repainted.

**Comment by shannah** [comment] 2017-05-19 17:15
Please describe what your expected behaviour vs actual behaviour is on this test.  Looking at the code as it is, I would expect the image to be able to draw over the entire screen.

Changing `setClip(...)` to `clipRect(...)` as follows:

~~~
gc.clipRect(dx,dy,w,h);           // combine with proper clipping region
//gc.setClip(dx,dy,w,h);      // runs wild, can write anywhere!
~~~

I expect it to just draw inside the bounds of the component.

The actual behaviour on both the Simulator and on Android (Nexus 5 running Android 6) matched the expected behaviour for me.

**Comment by ddyer0** [comment] 2017-05-19 18:09
On the simulator, and on IOS the "Hi World" banner at the top is protected.  I believe this
is the correct behavior.  On android, the top banner is eaten up, and the damage spreads
even further up into the top and bottom of the screen, which should be untouchable by
a normal app.
![screenshot_2017-05-19-10-57-43](https://cloud.githubusercontent.com/assets/5963076/26260814/88ea25e6-3c83-11e7-96fa-eea9eacb2bbb.png)
![screenshot_2017-05-19-10-57-26](https://cloud.githubusercontent.com/assets/5963076/26260817/8b305154-3c83-11e7-84f0-b75d453e1ac6.png)

Also, on IOS, if you wait until the top banner is clearly being protected and rotate the screen,
the top area is corrupted in the newly rotated screen.

**Comment by ddyer0** [comment] 2017-05-19 18:12
"anyware on the screen" should still be constrained by the component being drawn on.

**Comment by shannah** [comment] 2017-05-19 18:21
`setClip()` has no such protection.  This is consistent across all platforms.

**Comment by ddyer0** [comment] 2017-05-19 19:31
just try it.

you'll see that the simulator and actual devices behave differently, and IOS behaves
differently from Android.  Three different sets of behavior can't all be correct.

Clipping for a GC derived from a particular component shouldn't be
able to be set to a screen area not owned by that component.

IOS behaves more like the  simulator, but it's still the case that the parts of the screen 
not owned by any part of the app ought to be protected.

be protected unconditionally.

**Comment by shannah** [comment] 2017-05-19 20:13
I tried it.  Behaviour in all 3 matches for me.
None of the screenshots you shared indicate a problem as far as I can tell.

**Comment by ddyer0** [comment] 2017-05-19 20:41
In the first screen shot, the "Hi World" form label has been wiped out by
repainting the center window.  In the second screen shot, the expanding
background in the center window has expanded to where it pollutes the
areas at the top and bottom of the screen, which are not even owned
by the app.

**Comment by ddyer0** [comment] 2017-05-19 21:00
those particular screen shots were from a kindle fire running fireos 5.3.3.0
insignia tablet running android 4.2.2 produces similar behavior to the first shot, but not the second
irulu tablet running android 4.4.2 ditto

**Comment by shannah** [comment] 2017-05-19 21:14
> In the first screen shot, the "Hi World" form label has been wiped out by
repainting the center window.

Since setClip() will allow you to set a clip anywhere in the window, this is expected behaviour.

>  In the second screen shot, the expanding
background in the center window has expanded to where it pollutes the
areas at the top and bottom of the screen, which are not even owned
by the app.

The app "owns" whatever the platform allows it to write to.  In the cases of your screenshots, likely the top bar is just set to transparent.  You can change that style to whatever you like.  In any case, I see nothing wrong with that screenshot either.

**Comment by ddyer0** [comment] 2017-05-19 21:39
"the window" in question is the center pane.  The banner is in a separate window, and 
setClip ought to be unable to affect it.

**Comment by shannah** [comment] 2017-05-19 23:04
As I said.  setClip() can affect the entire drawable region.  If you want to constraint it to a certain region, use clipRect().

Closing this issue as it appears as though this bug report is describing correct behaviour.

**Closed by shannah** 2017-05-19 23:04 UTC

**Comment by ddyer0** [comment] 2017-05-20 08:27
As it stands now, ios and android behave visibly differently.  One of them is still wrong.

**Comment by codenameone** [comment] 2017-05-20 11:42
>  Drawing is considered a low level API that might introduce some platform fragmentation. 

From: https://www.codenameone.com/manual/graphics.html

That's even highlighted there. The behaviors you highlight are exactly the type of "gray area" you shouldn't rely on when working with graphics.

**Comment by shannah** [comment] 2017-05-20 14:12
> As it stands now, ios and android behave visibly differently. One of them is still wrong.

Please post a screenshot on iOS and on Android that demonstrates this difference.  I haven't seen anything so far in this issue that sounds out of place.

**Comment by ddyer0** [comment] 2017-05-20 17:58
On IOS, the top component containing the banner is protected.  Also on the 
simulator.  I believe this is the correct behavior.
![img_0087](https://cloud.githubusercontent.com/assets/5963076/26278275/33b6f478-3d4b-11e7-8983-52540090a1bb.PNG)
