### ISSUE TITLE
New Guibuilder Picker 3.7.1

### ISSUE THREAD

**Issue by thomasmcneill** [codenameone/CodenameOne#2141] opened 2017-06-28 03:19 UTC
When adding "Picker" from Additional components section it results text being "Error: java.lang.NullPointerException" and the object has a UUID of Label.

**Comment by shannah** [comment] 2017-07-12 17:52
Are you using autolayout mode?  I just tried and can't reproduce the problem.

**Comment by thomasmcneill** [comment] 2017-07-12 18:47
No, I am not using autolayout.  I have a few new projects and I will try
implementing a slider to see if it is an issue with that project.  I can't
reproduce it on my second PC.    I did install the 3.7.2 update and need to
see if the issue persists.

**Comment by shannah** [comment] 2017-09-25 16:00
Can't seem to reproduce this problem in autolayout mode or in the old "manual" mode.  Must have been fixed in one of the many improvements that have happened over the past few months.  Closing

**Closed by shannah** 2017-09-25 16:00 UTC

**Comment by thomasmcneill** [comment] 2017-09-25 16:10
I quit using the designer and went with dynamic form generation.
