### ISSUE TITLE
Login with google/facebook leave underlying form active

### ISSUE THREAD

**Issue by iwaymike** [codenameone/CodenameOne#2243] opened 2017-10-16 20:15 UTC
This problem is occurring in the simulator, when I click the login with google button the google entry dialog is shown, but when I try to click on the field to enter my google ID the (facebook login) button on the original form behind the field gets triggered. My code is pretty much copied from the socialchat demo with the exception of two buttons (my system login, register to my system). Other issues that I am having that might be related are I had to set the force login to true or code runs as if it is logged in already (with null values for name, id, etc.). I cannot get the button to retain the border changes (also true for facebook button). The Start and doLogin code is as supplied in the demo with a few System.out.println statements I added for debugging.

    private void showLoginForm() {

        Form loginForm = new Form();

    // the blue theme styles the title area normally this is good but in this case we don't want the blue bar at the top
        loginForm.getTitleArea().setUIID("Container");
        loginForm.setLayout(new BorderLayout());
        loginForm.setUIID("MainForm");
        Container cnt = new Container(new BoxLayout(BoxLayout.Y_AXIS));
        cnt.setUIID("Padding"); 
        Button loginWithGoogle = new Button("Signin with Google");
        loginWithGoogle.setUIID("LoginButtonGoogle");
        Button loginWithFacebook = new Button("Signin with Facebook");
        loginWithFacebook.setUIID("LoginButtonFacebook");
        Style iconFontStyle = UIManager.getInstance().getComponentStyle("IconFont");
        loginWithFacebook.setIcon(FontImage.create(" \ue96c ", iconFontStyle));
        loginWithGoogle.setIcon(FontImage.create(" \ue976 ", iconFontStyle));    
        Button myLoginBtn = new Button("");
        FontImage.setMaterialIcon(myLoginBtn, FontImage.MATERIAL_LINK);
        myLoginBtn.setUIID("ButtonLogin");
        Button registerBtn = new Button("Register");
        registerBtn.setUIID("ButtonRegister");
        cnt.addComponent(myLoginBtn);
        cnt.addComponent(loginWithGoogle);
        cnt.addComponent(loginWithFacebook); 
        cnt.addComponent(registerBtn);        
        loginWithGoogle.addActionListener((e) -> {
                Dialog.show("Test", "Test", "OK", null);
                tokenPrefix = "google";
                Login gc = GoogleConnect.getInstance();
                gc.setScope("profile email https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.me");
                gc.setClientId("----------.apps.googleusercontent.com");
                gc.setRedirectURI("http://barq.appspot.com/oauth2callback");
                gc.setClientSecret("--------");
//                doLogin(gc, new GoogleData(), false);
                doLogin(gc, new GoogleData(), true);                
                System.out.println("The fullname is; " + fullName);
                //doLogin(GoogleConnect.getInstance());
            });

        loginWithFacebook.addActionListener((e) -> {
                System.out.println("Facebook action listener");
                tokenPrefix = "facebook";
                Login fb = FacebookConnect.getInstance();
                fb.setClientId("--------------");
                fb.setRedirectURI("http://www.barq.appspot.com/");
                fb.setClientSecret("--------------");
//                doLogin(fb, new FacebookData(), false);
                doLogin(fb, new FacebookData(), true);
                System.out.println("The fullname is; " + fullName);
                //doLogin(FacebookConnect.getInstance());
            });

        myLoginBtn.addActionListener((e) -> {
                System.out.println("In actionListener for myLoginBtn of base app");
                CustLogin custlogin = new CustLogin();
                custlogin.show();
                return;
        });

        registerBtn.addActionListener((e) -> {
                System.out.println("In actionListener for registerBtn of base app");
                execute("https://barq.appspot.com/signup");
        });

        loginForm.addComponent(BorderLayout.SOUTH, cnt);
        System.out.println("About to show loginForm");
        loginForm.show();

**Comment by codenameone** [comment] 2017-10-17 06:18
@shannah this is on 3.8 for evaluation whether this is a regression. If it is it should be fixed.

**Comment by shannah** [comment] 2017-10-23 18:25
I was not able to reproduce this. If, for some reason the OAuth login is displayed on top of the current form (rather than on a new form), and the pointer events are being handled by the bottom form- then this should have been fixed by https://github.com/codenameone/CodenameOne/commit/7197fcc7eaf580ab24c7e9512645d60ac5fb7d87

**Closed by shannah** 2017-10-23 18:25 UTC
