### ISSUE TITLE
Recent update has forced RoundRectBorder's radius to 2

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3005] opened 2020-01-21 22:48 UTC
Setting it to any other value now produces no effect. The update also inverted the effect of SetTopOnly/SetBottomOnly

**Comment by shannah** [comment] 2020-01-21 22:59
Suspect duplicate of https://github.com/codenameone/CodenameOne/issues/2993 which should be fixed in latest.  Please update plugin and libs to ensure that you are working with latest.

**Comment by javieranton-zz** [comment] 2020-01-21 23:35
Just updated and this is still present. Setting RoundRectBorder.create().cornerRadius( number ) has no effect. [number] is always set as 2

**Closed** 2020-01-21 23:52 UTC
