### ISSUE TITLE
Entire touch Screen freezes after specific cycle of activities - Remains

### ISSUE THREAD

**Issue by hrugani** [codenameone/CodenameOne#2230] opened 2017-10-06 14:20 UTC
This issue is related to issue #2203.
Although, the issue #2203 was marked as closed,
the problem continues to occur.
It wasn't solved by commit [ddc2356](https://github.com/codenameone/CodenameOne/commit/ddc2356ee77eefb64425bcdd0d8ed5aab30505bf) as described in the comments that closed the issue.
 
This problem causes stress to our customers.
They are constantly losing their work and need to re-enter data that they just typed.

I wrote a little project that reproduces the problem. It can be accessed using this link: [Freeze5](https://github.com/hrugani/ProjectFreezeScreen5).
All code is in file MyApplication.java that has few lines.

To reproduce, first of all, **you need to run the App Freeze5 on a real device**.
(Typically all devices that have Android 6 - My device is Sumsung Galaxy J7 Prime). 
(**On Simulator the problem doesn't happen**).

After app loaded, the FORM1 will be shown. This form has only one big button in the center.

Now, the cycle of activities that reproduce the problem:

1. Touch the button in the center of Form1
2. then, Form2 will be shown. It has only one WebBrowser component in the center and it is set to show the "HTML String" of the Codename One Site.
3. then, do some navigation on the site (scrolling).
4. Finally, touch in back command to return to Form1

Please, repeat this cycle several times(steps 1 till 4).
The number of times you need to do this cycle till app freezes its screen is random.
The button in form1 stops responding to touch events.
Could occur in the first cycle as in 20th or 50th cycle. But it always occurs.

**Comment by codenameone** [comment] 2017-10-07 05:05
Can you reproduce this in the native Android Studio debugger then pause the application?
See: https://www.codenameone.com/how-do-i---use-the-include-sources-feature-to-debug-the-native-code-on-iosandroid-etc.html

Once you do that you will see the exact stack traces of the code freeze and you can paste them here.

**Comment by hrugani** [comment] 2017-10-09 14:49
We'll try to do that. As soon it is ready we' ll paste the result here.

**Comment by hrugani** [comment] 2017-10-11 20:06
I executed the procedure described in the video.
I was faced in additional errors than those has been presented in the video, but I reached the goal to debug my code in the device. (Sumsung Galaxy J7 Prime).
I don't know if the exact information that you are looking for is the one I will paste below. But,  at moment the freezing occurred, I got this after made a "Full Thread Dump":

`Full thread dump

"GAC_Executor[0]@4778" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks GAC_Executor[0]@4778
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1a2b> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at com.google.android.gms.internal.zzoe.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:818)

"GAC_Executor[1]@5031" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks GAC_Executor[1]@5031
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1a2d> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at com.google.android.gms.internal.zzoe.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:818)

"GAC_Executor[0]@5709" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks GAC_Executor[0]@5709
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1a30> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at com.google.android.gms.internal.zzbic.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:818)

"GAC_Executor[1]@6019" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks GAC_Executor[1]@6019
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1a32> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at com.google.android.gms.internal.zzbic.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:818)

"pool-2-thread-1@4566" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks pool-2-thread-1@4566
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1a2a> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"AsyncTask #1@5332" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks AsyncTask #1@5332
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1a2f> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"AsyncTask #2@6151" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks AsyncTask #2@6151
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor$(Thread.java:1220)
	  - locked <0x1a33> (a java.lang.Object)
	  at sun.misc.Unsafe.park(Unsafe.java:299)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:158)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2013)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1036)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1098)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	  at java.lang.Thread.run(Thread.java:818)

"FinalizerDaemon@6433" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks FinalizerDaemon@6433
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
	  - locked <0x1a28> (a java.lang.ref.ReferenceQueue)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
	  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:200)
	  at java.lang.Thread.run(Thread.java:818)

"main@4094" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-1)
	  at android.os.MessageQueue.next(MessageQueue.java:323)
	  at android.os.Looper.loop(Looper.java:135)
	  at android.app.ActivityThread.main(ActivityThread.java:7409)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

"EDT@4989" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks EDT@4989
	  at java.lang.Object.wait(Object.java:-1)
	  at com.codename1.ui.Display.mainEDTLoop(Display.java:940)
	  - locked <0x1a2c> (a java.lang.Object)
	  at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	  at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
	  at java.lang.Thread.run(Thread.java:818)

"CleanupReference@5778" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks CleanupReference@5778
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:423)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
	  - locked <0x1a31> (a java.lang.ref.ReferenceQueue)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
	  at org.chromium.android_webview.CleanupReference$1.run(CleanupReference.java:3)

"FinalizerWatchdogDaemon@6434" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks FinalizerWatchdogDaemon@6434
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:270)
	  - locked <0x1a29> (a java.lang.Daemons$FinalizerWatchdogDaemon)
	  at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:242)
	  at java.lang.Thread.run(Thread.java:818)

"invokeAndBlock1@5160" prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks invokeAndBlock1@5160
	  at java.lang.Object.wait(Object.java:-1)
	  at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:132)
	  - locked <0x1a2e> (a java.lang.Object)
	  at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
	  at java.lang.Thread.run(Thread.java:818)

"ReferenceQueueDaemon@6437" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks ReferenceQueueDaemon@6437
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:162)
	  - locked <0xc39> (a java.lang.Class)
	  at java.lang.Thread.run(Thread.java:818)

"Thread-46485@4288" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.net.LocalSocketImpl.accept(LocalSocketImpl.java:-1)
	  at android.net.LocalSocketImpl.accept(LocalSocketImpl.java:331)
	  at android.net.LocalServerSocket.accept(LocalServerSocket.java:90)
	  at com.android.tools.fd.runtime.Server$SocketServerThread.run(Server.java:157)
	  at java.lang.Thread.run(Thread.java:818)

"GoogleApiHandler@5540" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-1)
	  at android.os.MessageQueue.next(MessageQueue.java:323)
	  at android.os.Looper.loop(Looper.java:135)
	  at android.os.HandlerThread.run(HandlerThread.java:61)

"Chrome_ProcessLauncherThread@5660" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-1)
	  at android.os.MessageQueue.next(MessageQueue.java:323)
	  at android.os.Looper.loop(Looper.java:135)
	  at android.os.HandlerThread.run(HandlerThread.java:61)

"ConnectivityManager@5823" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-1)
	  at android.os.MessageQueue.next(MessageQueue.java:323)
	  at android.os.Looper.loop(Looper.java:135)
	  at android.os.HandlerThread.run(HandlerThread.java:61)

"HeapTaskDaemon@6435" daemon prio=5 waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	  at dalvik.system.VMRuntime.runHeapTasks(VMRuntime.java:-1)
	  at java.lang.Daemons$HeapTaskDaemon.run(Daemons.java:370)
	  at java.lang.Thread.run(Thread.java:818)

"Signal Catcher@6432" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 Incompatible thread state: thread not suspended

"Binder_1@5993" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_2@6436" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_3@4091" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_4@4092" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_5@4093" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"RenderThread@5022" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_IOThread@5662" prio=7 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-46498@5695" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-46499@5696" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-46503@5991" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-46504@6000" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_InProcRendererThread@6002" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Chrome_InProcGpuThread@6029" prio=7 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"hwuiTask1@6154" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"hwuiTask2@6155" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Thread-46513@6546" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

`

**Comment by codenameone** [comment] 2017-10-12 04:30
Thanks. It looks like the native rendering is stuck. Check the following:

- Place a breakpoint under the line in the EDT thread where it's blocked (`Display.java` line 941) - see if any action caused the EDT to run
- Place a breakpoint in `dispatchDraw` within `AndroidAsyncView` and see if it is hit

**Comment by hrugani** [comment] 2017-10-18 19:41
I've been trying to get the information that you requested in the last message, but the Android Studio is presenting a weird behavior and it doesn't allow to get the pieces of information.

AndroidStudio compiles and builds my project correctly and also I can run it (without debug) on my device. But, when I make the same thing in debug mode, an exception is thrown and the application stops. The device's display remains blank with no visual component.
Only in debug mode, I can get the information.

Below, I listed the stack-trace at the moment when the exception is thrown in debug mode. 
**Could anyone help me solve this problem? i.e, I need to make my project work in debug mode too**.

**IMPORTANT:
In debug mode, Android Studio installs successfully the application on the device. The exception happens at application's start time into the device.**

Stack-Trace:
main@4097" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Posix.stat(Posix.java:-1)
	  at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:293)
	  at java.io.File.isDirectory(File.java:523)
	  at dalvik.system.DexPathList.makePathElements(DexPathList.java:232)
	  at dalvik.system.DexPathList.<init>(DexPathList.java:139)
	  at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
	  at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
	  at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:86)
	  - locked <0x101a> (a android.util.ArrayMap)
	  at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:47)
	  at android.app.LoadedApk.getClassLoader(LoadedApk.java:438)
	  - locked <0x1009> (a android.app.LoadedApk)
	  at android.app.LoadedApk.makeApplication(LoadedApk.java:663)
	  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6472)
	  at android.app.ActivityThread.access$1800(ActivityThread.java:230)
	  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1888)
	  at android.os.Handler.dispatchMessage(Handler.java:102)
	  at android.os.Looper.loop(Looper.java:148)
	  at android.app.ActivityThread.main(ActivityThread.java:7409)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

"Signal Catcher@4115" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 Incompatible thread state: thread not suspended

"ReferenceQueueDaemon@4116" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 Incompatible thread state: thread not suspended

"FinalizerDaemon@4117" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 Incompatible thread state: thread not suspended

"FinalizerWatchdogDaemon@4118" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 Incompatible thread state: thread not suspended

"HeapTaskDaemon@4119" daemon prio=5 waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 Incompatible thread state: thread not suspended

"Binder_1@4120" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_2@4121" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_3@4091" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_4@4092" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_5@4093" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_6@4094" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_7@4095" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_8@4096" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

**Comment by codenameone** [comment] 2017-10-19 06:33
Which exception is thrown and is it caught/handled? Is there anything printed in DDMS when that happens? 
It's possible that this is an exception that's handled and you just have a debugger option to break on all exceptions.

**Comment by hrugani** [comment] 2017-10-21 16:18
First of all, thank you for the last message.
It helped me to solve the problem that was preventing me from generating the new data that you requested. 

You asked me to do the following:
- **Place a breakpoint under the line in the EDT thread where it's blocked (Display.java line 941)
 (see if any action caused the EDT to run)**

- **Place a breakpoint in dispatchDraw within AndroidAsyncView and see if it is hit**

I made what you have requested.
I marked the breakpoints on the lines you have asked me to set. 
After that, I debugged the Application in my device repeating the same cycle of activities that cause the Screen's Freezing.

When I pressed the button on form 1, the breakpoint on line 941 of Display.java was hit twice before form2 was ready.
When I fired the return command from form2 to form1, this same breakpoint was only reached once until form1 was ready to be used again.

This cycle was repeated several times till the Screen freeze.

After screen freeze, the passing behavior of the breakpoint(941) has changed:

Form 2 never showed up again.
When I pressed the button (on Form 1) the breakpoint on line 941 of Display.java was only reached once. (before freezing it was always hit twice as described above).

And with respect to the second breakpoint (in dispatchDraw within AndroidAsyncView ). It continued to be hit even after freezing. Right after passing the first breakpoint (941).

**Comment by codenameone** [comment] 2017-10-22 11:53
If line 941 was is reached when you tap the screen after the screen is frozen that means the EDT isn't stuck and is still processing events. That means the UI is frozen because something went wrong in the rendering layer.

Is this indeed the case or does the EDT event run once then no longer loops?

If the EDT is still functioning but nothing is drawn we need to check what happened to the drawing surface and why it stopped drawing. The code that draws to the screen is in `AndroidAsyncView` where you should see a `flushGraphics` method. It should be invoked every time a draw operation is requested by the EDT. 

This should trigger `dispatchDraw` which is invoked asynchronously to draw the display. Is it invoked? Does it contain elements that should be drawn?

**Comment by hrugani** [comment] 2017-10-24 18:34
Answering the questions:

**1)Is this indeed the case or does the EDT event run once then no longer loops?**

The EDT event runs once then no longer loops.

**2) This should trigger dispatchDraw which is invoked asynchronously to draw the display. Is it invoked?** 

Even after Freezing the dispatchDraw method is invoked. But nothing happens on the screen.
Also, the second EDT invocation doesn't happen as expected,  after the button in the center of form1 is clicked (Based on the normal run cycle shown by Debugger before freezing. The debugger shows always 2 invocations of EDT). 

**3) Does it contain elements that should be drawn?**
There are elements that should be drawn.
The entire form 2, that has a WebBrowser component in the center that exhibit  the CodeNameOne's home page.

**Comment by codenameone** [comment] 2017-10-25 10:12
So after that point is the EDT stuck in line 940 or is it stuck on some other line? 
If the EDT isn't looping and calling flush graphics then we have the answer we just need to see why events aren't triggered. If it's looping in a different location of the EDT then just follow the flow of the loop, it should invoke the flush graphics to draw the elements. 

When I said elements that should be drawn I meant within that method where low level primitives are drawn. You will notice in the `AndroidAsyncView.dispatchDraw` it loops over the elements to draw. If there are no elements to draw that would be a problem.

**Comment by hrugani** [comment] 2017-10-26 23:07
In the last couple of days, I have been trying to debug the project on my device (Sumsung J7 Prime) as I did before and find the answers to questions that you ask in the last comment.  I executed the debugger a lot of times, but the execution presents other problem. I can't freeze the App as I always did before. Now, after repeating the same cycle of activities (a random number of times), the app instead of freezing, it stops (displaying the message: screenFreeze stops).  So, I'm not getting the requested information because of this new behavior.

**Comment by hrugani** [comment] 2017-10-26 23:33
IMPORTANT:

By reading the last questions that you sent, they lead us to suppose that you are considering that this project (attached in this issue #2230) has some specific code of our application. If this is the case, we'd like to undo this misconception.

This little project isn't our real App and it does not have any specific code of our own.
It was written only for isolate the problem of our code. It tries to show you that the problem is intrinsic of the CodeName One platform. Then, our App consequently has the same problematic behavior.

The project has a little number of lines (only one file:MyApplication.java).
A few visual components are used (2 Forms, 1 Button and 1 WebBrowser).
All of them connected by a simple and direct logic.
Only pure Codename One code are present.
All sources are on Github and the issue description has a link to it.

We find and you can correct us if you think we are wrong, you have better resources and knowledge to extract all necessary pieces of information to diagnose and find a possible solution. Our intention in publish this comment is only in the direction of speeding up the solution if possible.

Finally, We are always willing to walk together with CodeNameOne and contribute for 
robustness of CodeNameOne Framework.
We are very grateful for the promptness of CodeName One team.
And also we are always ready to respond all your questions that help us solve this issue.

**Comment by codenameone** [comment] 2017-10-27 06:34
I totally understand that this is a standalone app and probably an issue in Codename One, I didn't think this has application specific issues. It might have device specific issues as we have a limited set of devices to test on. 

We can try to reproduce this and fix this but because 3.8 is practically upon us we don't have the resources to dedicate for this before 2018 as after the release we'd walk right into the holiday season. 

Normally reproducing device issues is tricky and takes much longer than other issues, if you can reproduce the issue easily and follow our internal framework code we might be able to fix the issue sooner. As you saw from trying to debug this, on device debugging with the native framework is a tedious and lengthy process. If you can provide deeper insight into the location/cause of the failure we might be able to fix it sooner. If not we'll eventually try to reproduce the issue and fix it but it will obviously take us more time.

**Comment by hrugani** [comment] 2017-11-01 17:47
Ok. We will continue to work together on that issue answering all your questions.
As soon we find out the answers for the last questions you asked us,
we will post a new comment here.

**Comment by codenameone** [comment] 2017-11-02 12:22
Great, keep us posted. If you can't resolve it we'll look into it in the 4.0 release cycle which should start before December.

**Comment by shannah** [comment] 2018-02-16 18:49
I was able to reproduce this using the provided test program.  I found the memory leak using Android Studio's monitor tool, and it is fixed now.

**Closed** 2018-02-16 18:48 UTC
