### ISSUE TITLE
New or modified rounded rectangle border defined through the theme file are forced in top only mode

### ISSUE THREAD

**Issue by Romadelf** [codenameone/CodenameOne#2995] opened 2020-01-16 09:35 UTC
Hi,

I initially posted this on [StackOverflow](https://stackoverflow.com/questions/59761649/2-bugs-since-last-cn1-updates-debug-mode-and-rounded-rectangle-border) before realizing should have been here instead. Apologies for that.

We can't use rounded rectangle borders using theme unless we have set them before the recent updates (I have no clue on since when the bug exists except that it is no older than 1 month). If you create/edit a rounded rectangle border, I will automatically be set to top only mode upon save.

The current workaround I am using is creating a hard coded RoundRectBorder.

I see @shannah did a commit in that regard. Thanks, that was fast! I still create this issue for better follow-up and having better chances that it gets effectively and succesfully merged to the master branch.

Cheers

**Comment by shannah** [comment] 2020-01-16 13:19
Duplicate of https://github.com/codenameone/CodenameOne/issues/2993

**Closed by shannah** 2020-01-16 13:19 UTC
Labels: duplicate
