### ISSUE TITLE
Medium font size is inconsistent on devices and simulator

### ISSUE THREAD

**Issue by diamondobama** [codenameone/CodenameOne#1631] opened 2016-01-09 17:32 UTC
When font is set to medium, it looks approximately the same size as small. It happens with both new native fonts and system fonts. The font sizes proportion also act differently on different devices. Font sizes are not so distinct on high DPI devices with.

Test done on Windows environment. 

Test case 1 (Native vs System):

• Create a new  'Getting Started' app 
• Change the title font to "System font Medium Bold" and change the Get Started button font to "native:MainRegular small". 
• Run on simulator and on device, you will discover that the Get started text is slightly bigger than the Title Welcome text.

Test case 2 (Side by side):

• Create a new app using one of the themes.
• Add back command, title and title command.
• Change the BackCommand uiid to "native:MainLight medium"
• Change the Title uiid to "native:MainLight medium"
• Change the TitleCommand uiid to "native:MainLight large"
• Run the app on an iOS device or HTC one simulator.
• The difference between the 'back" and "title" is unnoticeable, compared to the title command.

**Comment by diamondobama** [comment] 2016-01-20 07:12
Noticed that Android medium font size seems to be fine now but iOS still have the issue.

**Comment by codenameone** [comment] 2016-01-20 07:23
I actually didn't get a chance to work on this yet so I have no idea what happened. I hope to look into it before the release next week. We are rushing to get things committed for the codefreeze.

**Closed** 2016-01-20 15:04 UTC

**Comment by codenameone** [comment] 2016-01-24 17:59
I just reverted this fix. Its too problematic to fix this issue and maintain backwards compatibility. The crux of the issue is that platforms can return wildly different font sizes when you request size X and if we try to enforce accuracy we get even worse results than before. 

The workaround is to just use millimeters which should be very consistent within the same font family.
