### ISSUE TITLE
Problems in MultiButton component  impact my app.

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3491] opened 2021-09-03 14:26 UTC
Yesterday in the mourning I have been compiled my app in android and iphone and it'was perfectly. But in the afternoon when I want to compile a update that I applie to my app that is not related with this screen. I found that my app goes to white screen in android an in iphone. To day when I check in the real device android I check this error log like if your push server is returning from GCM instead FCM google service.

![image](https://user-images.githubusercontent.com/16245755/132020281-38caf9fa-83c6-4e8a-ae9a-c044986e0213.png)

and in my Form that goes to white screen where I request to get the push id:

![image](https://user-images.githubusercontent.com/16245755/132020438-b2ff328c-47cf-4d6a-9bdf-05a0ab1d80d5.png)

could you tell me if you apply some update in your push server?

**Comment by Ngosti2000** [comment] 2021-09-03 16:35
i have raised the same issue on reddit, on 3 devices this is turning black
on my end.

**Comment by DurankGts** [comment] 2021-09-03 17:11
@shannah  is possible that this committ https://github.com/DurankGts/CodenameOne/commit/ddfefbd5dd58a9d2cfa708ff3ef614cdb460300c

cause this problem?

**Comment by shannah** [comment] 2021-09-03 17:26
No.  It looks like you are trying to get the phone number from the device.  You'll need to add the READ_PHONE_STATE permission to do that.  Google has tightened its policies and this permission is now disabled by default.

**Comment by DurankGts** [comment] 2021-09-03 18:39
This the not the  problem. The problem is in the MultiButton Component, Container, Component or Label. Do you apply some update Yesterday?

Do you set some Exceptin in your source code in the built server?

java.lang.IllegalArgumentException: id must be non-null and non-empty

this the error that just occur in real devices android and iphone.  I'm print log to chek where specifi if failing. I think that this a RunTimeException. This the cause that My Screen goes to White because this Exception is Occuring.

I attach my Custom MultiButton component

[CtmMultiButton.txt](https://github.com/codenameone/CodenameOne/files/7107790/CtmMultiButton.txt)

**Comment by DurankGts** [comment] 2021-09-03 18:40
This componen is causing and Exception that goes to White Screen in my Form.

**Comment by shannah** [comment] 2021-09-03 18:42
File that in a new issue.  That is not related to this issue.

**Comment by DurankGts** [comment] 2021-09-03 18:49
![image](https://user-images.githubusercontent.com/16245755/132052810-b754ec66-4375-452b-83a7-77c106dea2ea.png)

public static CtmMultiButton getCustomMultiButton(String uiidBackground,char icon, String uuidIcon,char emblemIcon,String uiidEmblem, String line1,String line2, String line3, String line4,String uiidLine1,String uuidLine2, String uiidLine3,  String uiidLine4, boolean checked) {

        CtmMultiButton mb = null;
        try {
            
            try {
                mb = new CtmMultiButton(uiidBackground);
                mb.setUIID(uiidBackground);
            } catch (Exception e) {
                Log.e(TAG, "getCustomMultiButton()->Error7836-1:" + e.toString());
            }
            
            if (uiidLine1 != null) {
                mb.setUIIDLine1(uiidLine1);
            }
            if (uuidLine2 != null) {
                mb.setUIIDLine2(uuidLine2);
            }
            if (uiidLine3 != null) {
                mb.setUIIDLine3(uiidLine3);
            }
            if (uiidLine4 != null) {
                mb.setUIIDLine4(uiidLine4);
            }
            
            if (line1 != null) {
                mb.setTextLine1(line1);
            }
            if (line2 != null) {
                mb.setTextLine2(line2);
            }
            if (line3 != null) {
                mb.setTextLine3(line3);
            }
            if (line4 != null) {
                mb.setTextLine4(line4);
            }
            
            try {
                if (uuidIcon != null && icon != 0) {
                    mb.setIconUIID(uuidIcon);
                    mb.setIcon(Utils.getMaterialImageUnselected(icon, uuidIcon));                    
                } else {
                    Log.e(TAG, "getCustomMultiButton()->uuidIcon:" + uuidIcon);
                    Log.e(TAG, "getCustomMultiButton()->icon:" + icon);
                    mb.setIconUIID(null);
                    mb.setIcon(null);
                }
            } catch (Exception e) {
                Log.e(TAG, "getCustomMultiButton()->Error7836-2:" + e.toString());
            }
            
            try {
                if (uiidEmblem != null && emblemIcon != 0) {
                    mb.setEmblemUIID(uiidEmblem);
                    mb.setEmblem(Utils.getMaterialImageUnselected(emblemIcon, uiidEmblem));
                } else { 
                    Log.e(TAG, "getCustomMultiButton()->uiidEmblem:" + uuidIcon);
                    Log.e(TAG, "getCustomMultiButton()->emblemIcon:" + icon);
                    mb.setEmblemUIID(null);
                    mb.setEmblem(null);
                }
            } catch (Exception e) {
                Log.e(TAG, "getCustomMultiButton()->Error7836-3:" + e.toString());
            }
            
            try {
                mb.setRadioButton(checked);
                mb.setCheckBox(checked);
            } catch (Exception e) {
                Log.e(TAG, "getCustomMultiButton()->Error7836-6:" + e.toString());
            }
            
            
        } catch (RuntimeException e) {
            Log.e(TAG, "getCustomMultiButton()->Error7836-4:" + e.toString());
        }

        return mb;
    }


this the problem in the methods now I think that you add some throws IllegalArgumentException in this methods

mb.setEmblemUIID(null);
mb.setEmblem(null);

mb.setIconUIID(null);
mb.setIcon(null);

**Comment by shannah** [comment] 2021-09-03 18:58
This is caused by the call to `setIconUIID(null)`.
I have removed this exception and recommitted - it will be included in the update next Friday., but, in general setting UIID to null is not recommended.

**Closed by shannah** 2021-09-03 18:58 UTC

**Comment by DurankGts** [comment] 2021-09-03 19:03
I understand you but You must Documentated this in your Api first. You can't apply and update that impact the developers where the app compiled it was very well today and tomorrow not. you must announce it first.

**Comment by DurankGts** [comment] 2021-09-03 19:04
this the problem. I need to launch my app as soon as possible. Now I will very late to launch to production to my company and clients.

**Comment by shannah** [comment] 2021-09-03 19:25
I have just pushed the latest to the server which will suppress these errors.
I still recommend not setting UIID to null.
