### ISSUE TITLE
Capture.capturePhoto can only be called a limited number of times on iOS before crashing

### ISSUE THREAD

**Issue by DigNZ** [codenameone/CodenameOne#2289] opened 2017-12-05 23:13 UTC
I've made a very simple minimal example for this to get to the bottom of the camera crash that I've reported a number of other places.
Reducing it right down to this from the getting started template:

```
package org.littlemonkey.test;

import com.codename1.capture.Capture;
import static com.codename1.ui.CN.*;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.FontImage;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;

import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import java.util.ArrayList;
import java.util.List;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class CaptureTest {

    private Form current;
    private Resources theme;

    private final List<Button> buttons = new ArrayList<>();

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER));

        Button getStarted = new Button("Take a photo");
        FontImage.setMaterialIcon(getStarted, FontImage.MATERIAL_CAMERA);
        getStarted.setUIID("GetStarted");
        hi.addComponent(BorderLayout.SOUTH, getStarted);
        getStarted.addActionListener((e) -> {
            String path = Capture.capturePhoto();
        });
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
```

The relevant part it just the action listener which opens the camera and ignores the result:
```
        getStarted.addActionListener((e) -> {
            String path = Capture.capturePhoto();
        });
```

On iOS around 175 photos can be taken before the app crashes back to the home screen.

Changing this to this call:

```
        getStarted.addActionListener((e) -> {
            String path = Capture.capturePhoto(400,-1);
        });
```

Then only 100 photos can be taken before the app crashes.

**Comment by shannah** [comment] 2017-12-08 15:06
This is a duplicate of https://github.com/codenameone/CodenameOne/issues/2285

**Comment by shannah** [comment] 2017-12-08 15:12
Possible workaround suggested at https://github.com/codenameone/CodenameOne/commit/303fca28079864f1ac3b513cae27fe49ddfc3de6#commitcomment-25971752 https://stackoverflow.com/questions/6554225/uiimagepickercontroller-memory-leak

**Closed** 2017-12-08 20:39 UTC
