### ISSUE TITLE
PullToRefresh and TensileDrag default behavior

### ISSUE THREAD

**Issue by diamondobama** [codenameone/CodenameOne#2190] opened 2017-08-23 14:32 UTC
PullToRefresh needs some polishing with regards to its default behavior to be up to par with its native counterpart.

Below are some of the issues I noticed with it:

- It's too sensitive, especially on iPhone. Dragging container a little bit activates it and even sometimes scrolling to the top aggressively also.
- No way of increasing distance before it's activated.
- No elasticity on pullToRefresh and container tensileDrag. If tensile Length is 4, that's the distance where tensileDrag will stop, instead of becoming more resistance to stretch as the length grows.
- Sometimes, when you are in portrait mode on iPhone and scroll to the bottom then flip your device to landscape, it gets activated.

**Comment by codenameone** [comment] 2017-10-28 18:05
I wasn't able to reproduce 1 & 2. I think they are triggered for you because of customization's to the theme that changed the way pull to refresh looks but also impacted the height negatively. I've added a theme constant `pullToRefreshHeight` which is a floating point value in millimeters indicating the height for pull to refresh which should hopefully solve this.
About number 3 I think I understand what you are saying but I'm not really sure where to begin with addressing this. Googling elastic pull to refresh found this: https://github.com/gontovnik/DGElasticPullToRefresh which doesn't seem like what you are referring to (although it is pretty cool and probably doable in Codename One).

**Comment by codenameone** [comment] 2017-11-06 12:19
I'm closing this as fixed for now as most of this should work. If there are more specific fine tuning we can open a new issue with screenshots and more details

**Closed by codenameone** 2017-11-06 12:19 UTC
