### ISSUE TITLE
Will need to update Billing Library on Android

### ISSUE THREAD

**Issue by javieranton-zz** [codenameone/CodenameOne#3404] opened 2021-05-08 13:03 UTC
`We've detected that this app is using an old version of Google Play Billing. By 1 November 2021, all app updates must use billing library version 3 or newer. Update to billing library 3 before this date. Learn more about billing library 3.`

You may already be aware of this. It's a long time from now (6 months) but I will leave it open here so we're aware of it

**Comment by javieranton-zz** [comment] 2021-08-06 18:00
Friendly reminder about this one.. still some time to go

**Comment by shannah** [comment] 2021-09-09 11:38
Looking through the code, I think we're already on version 3.  Do you have any server-side interaction with the Google play billing service (e.g. to validate receipts)?

**Comment by javieranton-zz** [comment] 2021-09-12 15:00
Just uploaded new version with AndroidX build hint this time and I still see this. The only IAP I use are 1-time consumable IAPs. I don't validate receipts server-side, I assume they always work. I prevent fraud by forcing all rooted devices to go through paypal instead of Google. I will delete this last sentence after you have read this

![image](https://user-images.githubusercontent.com/11293898/132992528-b45ffea2-29c3-437a-8a68-6f983465ae90.png)

**Comment by shannah** [comment] 2021-09-13 15:07
I've seen that warning message before, but I can't seem to find it right now in any of my test apps.  Does this error persist in the play console after your release is complete, or does it only show up while you are uploading a new APK?

**Comment by javieranton-zz** [comment] 2021-09-13 15:52
I only see it while uploading

**Comment by shannah** [comment] 2021-09-13 18:36
OK.  I've identified it.  Looks like, we were still using the old billing library, even though we were using the V3 API.  Confusing.  Working on updating this.

**Comment by javieranton-zz** [comment] 2021-09-13 18:51
Sounds good thanks

**Comment by shannah** [comment] 2021-09-15 13:50
I have just committed some changes that will cause it to use the latest billing library (4.0.0).
https://github.com/codenameone/CodenameOne/commit/f2491083866c4a82594135936732747bd739ea5d

This will be on the build server in Friday's update.  You can test it now using Maven and local gradle builds (but you'd have to build CN1 from source, and set the cn1.version and cn1.plugin.version of your project to be 8.0-SNAPSHOT).

This constitutes a fairly major change, and IAP is notoriously brittle, so I recommend testing your payment workflow before submitting a new build.

**Comment by javieranton-zz** [comment] 2021-09-25 19:18
Hey, this needs re-opening

I just updated CN1 on IDEA and now all consumables say "already purchased" when re-purchased (they shoudln't) and each purchase also returns an error call "Server Error" + success call

I am clocking out for today, will give screenshots tomorrow if possible

**Comment by shannah** [comment] 2021-09-27 11:58
Is there anything else contained in the ServerError string?  Or just "Server Error".

**Comment by javieranton-zz** [comment] 2021-09-28 11:05
The full error is "Server error, please try again."

**Comment by shannah** [comment] 2021-09-28 11:49
I can't find that error message anywhere in our sources, so either that text comes whole from Android, or it comes from your code.   My IAP test app was deleted from Google play, so I need to set up a new test from scratch, and am awaiting their approval for closed testing (which I think is the minimum necessary for IAP to be testable).

**Comment by javieranton-zz** [comment] 2021-09-28 11:53
The error message is the string passed in the second param in `public void itemPurchaseError(String sku, String errorMessage)`

I suspect it must come from Google too. In its current state CN1's IAPs are broken so feel free to update the plugin and ask me to test again (I won't publish or anything until this is fixed anyway)

**Comment by shannah** [comment] 2021-09-28 12:01
I have other apps that use IAP and they work fine (subscription and non-consumable).  My test app was the only one with consumable.  It worked when tested last week, but it got deleted.

Do you have anything else in your logcat log?  What is the SKU of your product?

**Comment by javieranton-zz** [comment] 2021-09-28 12:03
SKU: com.groups.network.5mb

I am working overtime (day job) every day this week so I can't really dive into debugging with my dev machine, apologies. But I can be on github replying all your questions

**Comment by javieranton-zz** [comment] 2021-09-28 12:04
Could you not create a new consumable IAP in your other app? Google usually approves new IAPs very quickly

**Comment by shannah** [comment] 2021-09-28 12:14
I have a new consumable product in that one pending review too.

**Closed** 2021-09-30 16:43 UTC

**Comment by javieranton-zz** [comment] 2021-10-02 19:25
Hey, I just updated the plugin to 7.0.42

All works well when building on the server, but the Android Local build still has the same problem

Building from the sources provided from the server build also still has this problem

I need to build from sources because I need to edit the final stub

**Comment by shannah** [comment] 2021-10-02 19:37
Make sure that cn1.version and cn1.plugin.version are both 7.0.42

**Comment by shannah** [comment] 2021-10-02 19:45
Also clean the android module.  ie delete the android/target directory

**Comment by javieranton-zz** [comment] 2021-10-02 22:59
I intuitively think that your proposed solutions should work; but no, neither deleting the entire target directory and rebuilding nor making changes in the src and rebuilding gets rid of this problem

The sources generated do include the changes in https://github.com/codenameone/CodenameOne/commit/485e752b5c0552a8d2b400188bc1208593172cc6 so I don't know why this is happening. It isn't happening in the server build, weird (but it is happening in the server builds' sources too). Could the server build not be yet using 7.0.41?

**Comment by javieranton-zz** [comment] 2021-10-03 09:01
I just decompiled the apk from the server and it does include https://github.com/codenameone/CodenameOne/commit/485e752b5c0552a8d2b400188bc1208593172cc6 so I really don't know what to do now

**Comment by javieranton-zz** [comment] 2021-10-03 11:28
Update: servers apk also doesnt work. Must have tested it wrong the first time

**Comment by shannah** [comment] 2021-10-03 12:04
I cannot reproduce. Consumable products working correctly in my tests.  Please re-describe your issue with the presumption that your current problem is different than the original problem.  If your consumable product was previously purchased by your test account and not "consumed", then you may need to "refund" it through the play developer console before you'll be allowed to purchase it again.  Note, also, that when I was doing my tests, I ended up having to create a new SKU for testing after I had an unconsumed SKU, because even after refunding it in Google play, the device still said that I had already purchased that item.  Probably it is a caching issue, that would clear itself after some time, but I waited several hours and the cache was still not purged.

**Comment by javieranton-zz** [comment] 2021-10-03 13:06
Yes, you are right. I just tested with a different product and this time it was fine. I will try to clear the cache somehow, can't really create new skus because these are live products. Thanks for this
