### ISSUE TITLE
CN.openGallery GALLERY_IMAGE failing on Android

### ISSUE THREAD

**Issue by diamondobama** [codenameone/CodenameOne#3255] opened 2020-09-03 21:00 UTC
Using `CN.GALLERY_IMAGE` works fine on the Simulator but throwing below exception on Android.

> Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

```
CN.openGallery(e -> {
    if (e != null && e.getSource() != null) {
        try {
            String imageFile = e.getSource().toString();

            Image image = Image.createImage(imageFile);
            ScaleImageLabel icon = new ScaleImageLabel(image);

        } catch (Exception ex) {
            ToastBar.showErrorMessage(ex.getMessage());
        }
    }
}, CN.GALLERY_IMAGE);
```
If I switch to `CN.GALLERY_IMAGE_MULTI`, this works fine on Android by selecting the first image:
```String imageFile = ((String[]) e.getSource())[0];```

**Comment by shai-almog** [comment] 2020-10-03 09:54
Duplicate of #3204

**Closed by shai-almog** 2020-10-03 09:54 UTC
Labels: duplicate
