### ISSUE TITLE
UWP Solitaire demo crashes on Lumia 930

### ISSUE THREAD

**Issue by FabricioCabeca** [codenameone/CodenameOne#1881] opened 2016-09-05 19:38 UTC
Just tried the Solitaire demo from the app store, but it closed right after showing the initial splash icon.

**Comment by codenameone** [comment] 2016-09-06 03:38
Was this on a device or desktop? 
Assuming the latter which device?

**Comment by FabricioCabeca** [comment] 2016-09-06 13:38
Lumia 930 is a Windows 10 phone.

**Comment by shannah** [comment] 2016-09-06 16:40
I have crash reporting turned on and I'm not receiving this crash report so this crash must occur before initialization (or the crash reporting it failing on device also).

What version of Win10 is the device running? (I'm running on a Lumia 640 with 10.0.14393.67 without a problem).  The 930 has more RAM and better specs that the 640 across the board so it shouldn't be a hardware limitation.

Any other debug information you can provide would be helpful.  E.g. if anything is reported in the device logs.

**Comment by shannah** [comment] 2017-08-24 16:36
Duplicate of https://github.com/codenameone/CodenameOne/issues/2060

**Closed by shannah** 2017-08-24 16:36 UTC
Labels: duplicate
