### ISSUE TITLE
UWP App crashes on startup on Lumia 930

### ISSUE THREAD

**Issue by Elewyth** [codenameone/CodenameOne#2185] opened 2017-08-21 21:58 UTC
Steps to reproduce:

1. Create new Project in Eclipse (using any Template, e.g. Get Started App)
2. Follow instructions on https://www.codenameone.com/manual/appendix-uwp.html (Everything works fine, installation of App etc.)
3. Open App on Lumia 930 (Windows 10 mobile (10.0.14393.1593))
4. App shows splash icon
5. App briefly shows a black screen without anything of the expected GUI in it and immediately crashes (returns to home screen).

I made a Pro-Trial just to enable the logging (Log.bindCrashProtection(true);), but I haven't received any Emails so far.

The App works just fine on Windows 10 Desktop and when building and running on Android.

Tested Templates: "Get Started App", "Hello World (Bare Bones)", "Solitaire Demo" from App Store. All of these exhibit the exact same behavior.

**Comment by shannah** [comment] 2017-08-24 16:28
Duplicate of https://github.com/codenameone/CodenameOne/issues/1881 and https://github.com/codenameone/CodenameOne/issues/2060

**Closed** 2017-08-24 16:29 UTC
Labels: duplicate
