### ISSUE TITLE
BUG: BoxLayout.y() inside BoxLayout.y() doesn't work (it's cut)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2464] opened 2018-06-29 15:06 UTC
The following code generates the following screenshot: as you can see, some text is not present, like if it's cut. I need to style a Container with BoxLayout.y() inside a Form with BoxLayout.y(), but this bug breaks the layout of my app: I didn't find any workaround. 

Tested with a new Codename One project, native theme, project lib updated few minutes ago.

Code:
```
import com.codename1.components.SpanLabel;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.Container;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class BoxLayoutTest {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        SpanLabel spanLabel1 = new SpanLabel("Quite long text that should go on two lines al least... if the device is on portrait mode");
        hi.add(spanLabel1);

        Container box = new Container(BoxLayout.y());
        SpanLabel spanLabel2 = new SpanLabel("Quite long text that should go on two lines al least... if the device is on portrait mode");
        SpanLabel spanLabel3 = new SpanLabel("Quite long text that should go on two lines al least... if the device is on portrait mode");
        box.add(spanLabel2);
        box.add(spanLabel3);
        hi.add(box);
        
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
```

Screenshot (with iPhone X skin):
![boxlayoutbug](https://user-images.githubusercontent.com/1997316/42099802-b69090cc-7bbe-11e8-9516-3d545d5eb8ad.png)

**Comment by codenameone** [comment] 2018-06-30 05:18
That's because of `SpanLabel` not box layout. Try using a `TextArea` with a `Label` UIID and editable/focusable set to false.

Because of the line break the text area (within the span label) tries to trigger a reflow to request additional height but fails because of the deep hierarchy. It doesn't recurse as this will both block performance and could create an infinite loop.

**Comment by jsfan3** [comment] 2018-07-02 11:09
Thank you very much: your suggestion worked for me. It's a perfect replacement for SpanLabel if I only need to show text.

**Comment by jsfan3** [comment] 2018-07-02 12:05
Because I want to keep my code simple and compatible with the SpanLabel API (assuming that its implementation will be fixed), as a temporary workaround I replaced the import of `com.codename1.components.SpanLabel` with the import of the following custom class:

```
package [mypackage].components;

import com.codename1.ui.TextArea;
import com.codename1.ui.plaf.UIManager;

/**
 * Simply (temporary) replacement of SpanLabel, useful to show multiline text.
 * The motivation of this SpanLabel replacement is this bug:
 * https://github.com/codenameone/CodenameOne/issues/2464
 *
 */
public class SpanLabel extends TextArea {
    
    public SpanLabel(String txt) {
        this(txt, "Label");
    }

    public SpanLabel(String txt, String textUiid) {
        super(UIManager.getInstance().localize(txt, txt));
        super.setUIID(textUiid);
        super.setEditable(false);
        super.setFocusable(false);
    }

}
```

**Comment by codenameone** [comment] 2018-08-09 12:12
I'm able to reproduce this but after several attempts at working around this I'm still running into issues. I think the solution might require a complete re-imagination of the text layout logic in a way that isn't as recursive as it is now. I'm not sure if that's possible. I'm closing this as I don't think the current code is fixable for this use case without breaking too much of the legacy code.

**Closed by codenameone** 2018-08-09 12:12 UTC

**Comment by jsfan3** [comment] 2018-08-09 21:58
Ok, however thank you for your attemps.
