### ISSUE TITLE
Aspect Ratio changes on iPad after restore from background

### ISSUE THREAD

**Issue by VToegel** [codenameone/CodenameOne#2739] opened 2019-03-15 09:02 UTC
My App works without flaw on iphone, but on the iPad the aspect ratio changes on every restore.
iPad: iPad 2 Air
iOS: 12.1.4

Problem Description:
App starts correctly on iPad. When sending the app in background via homebutton and then restoring the app to foreground the aspect ratio changes. When switching thereafter to a new form or by turning the iPad (e.g. Portrait to landscape), the aspect ratio is correct again.
When the aspect ratio is wrong and i send to background and restore the aspect ratio is correct, to background and restore its wrong again, to background and restore its correct again and so on.
This only happens on the iPad. In the simulator this does not happen.

A Testcase is attached, i can provide a complete testcase export on request, since its too big for upload.

Rgds Vinc

![grafik](https://user-images.githubusercontent.com/27338698/54419822-a67c8680-4708-11e9-85de-2eb16fcbb47b.png)

 
![grafik](https://user-images.githubusercontent.com/27338698/54419850-b3997580-4708-11e9-9817-ab854e2ef2b1.png)

[Testcase.zip](https://github.com/codenameone/CodenameOne/files/2970197/Testcase.zip)

**Comment by shannah** [comment] 2019-03-15 12:12
Can you share the .res file for that test case also?

**Comment by Incalculable83** [comment] 2019-03-15 17:57
Here the linkt to the Test.zip including the .res file.

https://www.dropbox.com/s/8h26nyzxwb2fxts/Testcase.zip?dl=0

rgds Vinc

**Comment by shannah** [comment] 2019-03-18 13:25
I have only been able to reproduce this randomly, and at a frequency of about 1 in 100 attempts.  I'm trying different variations of opening the app, rotating it, closing the app (with home button), reopening , etc...  Trying rotating the device both when the app is in the foreground and in the background.  Can't identify any pattern so far to reliably reproduce it.  There must be a race condition here, but I need to find a way to reproduce the issue more reliably.

**Comment by Incalculable83** [comment] 2019-03-18 13:47
I tried again with the last version of the full app. No problem whatsoever on iPhone, but on my ipad 2 air it happens almost everytime on every form. Just close with homebutton, reopen, aspect ratio is different. Do again, and all is normal again.
I can provide the full app if you can provide an email to send the dropbox link...

**Comment by shannah** [comment] 2019-03-18 13:57
If you're an Enterprise account, you can request full project support through the support email.
Otherwise I would need a test case, that I can use to reproduce it.  A test case can be a self-contained app... preferably that you can paste inside an issue.  If it requires the full project, then you can create a public git repo that I can clone and build locally to reproduce it.  The smaller the test case the better.

If you have access to a Mac, it may also be helpful to see the device log.  There may be an exception being thrown somewhere that is affecting the app sizing.

**Comment by Incalculable83** [comment] 2019-03-18 14:36
I just uploaded a standalone testcase to github and invited you to the repository.
Unfortunately i am no enterprise user. And its the first time i used Github, so i hope everything is correct ;-)
Thank you very much for the help.

**Comment by shannah** [comment] 2019-03-18 14:47
Unfortunately a private repo with a full project is full project support.

Let's start from here:

This this happen with a hello world app?

Here is a starting test case:

~~~~
public void test() {
    Form f = new Form("Hello World", BoxLayout.y());
    f.add(new Label("Hello World"));
    f.show();
}
~~~~

If you can't reproduce with this test case, modify it until it can be reproduced.

**Comment by shannah** [comment] 2019-07-16 13:09
This should be fixed by https://github.com/codenameone/CodenameOne/commit/738fc9b28aeb8909bee37ab25d565086f30e0081

This issue is likely actually a duplicate of https://github.com/codenameone/CodenameOne/issues/2819

**Closed by shannah** 2019-07-16 13:09 UTC
