### ISSUE TITLE
TextArea doesn't stop editing in Javascript port when the virtual keyboard is closed

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2682] opened 2019-01-23 00:21 UTC
`TextArea` doesn't stop editing in Javascript port when the virtual keyboard is closed (it also means that the `ActionListener` of the `TextArea` is not called when the virtual keyboard is closed).

Expected behaviour (like in native app): https://vimeo.com/312846801

Current wrong behaviour (tested with Android Chrome): https://vimeo.com/312847234

My test case:
```
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(getProfileMsgCnt());
        hi.show();
    }
    
    public static Container getProfileMsgCnt() {
        TextArea shortBio = new TextArea();
        shortBio.setGrowByContent(true);
        shortBio.setMaxSize(250);
        shortBio.setGrowLimit(-1); // note the 250 char limit
        shortBio.stopEditing(); // no automatic editing
        shortBio.setUIID("BaseProfileForm-ShortBio");
        shortBio.setText(null);
        shortBio.setHint("ProfileUtilities-YourMessage");
        shortBio.getHintLabel().setUIID("BaseProfileForm-ShortBioHint");
        shortBio.addActionListener(l -> {
            shortBio.stopEditing();
            shortBio.getParent().revalidate();
        });
        return BoxLayout.encloseY(shortBio);
    }
```

**Comment by codenameone** [comment] 2019-01-23 14:21
Is this not sending a done listener or an action listener?
If an action listener event is sent but a done listener event isn't then I would say this is fine. Not much to do here... If there is no action listener event then this is a problem, we need a way to detect that text editing finished.

**Comment by shannah** [comment] 2019-01-23 14:39
There is no action event because the field doesn't lose focus.  In Android in web apps, there is no javascript event fired by hiding the keyboard.  It has no effect on the state of the app.  Firing an action event here would be wrong.

I actually just tried out a couple of native android apps (non-cn1), and it would seem that our behaviour  on native apps is at odds with native android apps.

E.g. The GMail app.  If I tap on "Search" to start searching, the keyboard opens.  If I close the keyboad, the search field remains focused (cursor blinking).  

If anything, we should probably be changing the behaviour of our Android native apps to align with this behaviour and not vice versa.  I.e. merely hiding the keyboard should not cause the field to lose focus, nor should it fire an action event since the field is still in focus.

**Comment by codenameone** [comment] 2019-01-23 14:46
In Android you often have the search icon in the keyboard itself but you can't rely on this feature on all OS's. We need a way to detect that the user finished editing and that's something we rely on universally. The fact that the keyboard folded isn't the issue, it's the fact that editing is finished. This would effectively force all our existing code to convert ActionListener to DataChangeListener which is probably not what we want.

**Comment by codenameone** [comment] 2019-01-23 15:14
Why not fire an action event every time the screen size changed in Android? 
Why do we need something more complicated than that?
Even if editing isn't finished it would still behave in a similar way to the way it behaves on most OS's right now.

**Comment by shannah** [comment] 2019-01-23 17:12
> Why not fire an action event every time the screen size changed in Android?
This simplifies the scenario a tiny bit (does away with a timer - perhaps), but there are still a lot of heuristics to deal with.

> Even if editing isn't finished it would still behave in a similar way to the way it behaves on most OS's right now.

I have so far identified 3 platforms that have a "hide keyboard" function.

1. Android - When user closes the keyboard while editing a text field, the text field remains focused.  (e.g. Try Gmail app.  Start a search and close keyboard - the field remains focused.  This is especially important when there are autocomlete suggestions for the field... the user may close the keyboard to select an option).
2. iPad - When user closes the keyboard, the field appears to lose focus (i.e. cursor stops blinking).  However, autocomplete suggestions stay open, suggesting that the field still has focus in some sense.
3. Windows surface.  Opening/closing keyboard has no effect on field focus.

In all 3 cases, our Javascript port behaves the same as the native platform behaviour.  I.e. On iPad if you hide the keyboard while editing a TextArea, it will fire the action event.  On Android, it does not fire the event.

In running these tests, it crossed my mind that it is just blind luck that the JS port works correctly (i.e. is consistent with native app behaviour on that platform), but it is actually because I'm binding to the "focus/blur" event to decide when editing is done that everything works correctly.   If the platform thinks editing is done, it will fire the "blur" event on the field.  Then we fire the action event.  

I don't think we should be arguing with the platform as to whether editing is complete or not.  Introducing additional action events in response to other state changes will only make behaviour less consistent, and harder to work with.

It occurs to me that part of the problem here is that "Action Events" aren't well defined.   Even searching through Swing/AWT javadocs, the best I can find is that they are "events fired in response to user actions".  But which actions?  JTextField, for example, will fire an action event when the "enter" key is typed, but not when a user tabs out of the field, or when it just loses focus.  

For Codename one, it seems like a descriptive definition (with respect to text fields) might be more like "event fired when editing is done, such as when the user hits "enter", "done", or "next" on the VKB, or when the user taps outside of the field, or when the field loses focus for any reason".

We could  add "or when the keyboard is closed" to this definition, but I think this would be a mistake.  On Android, for whatever reason, they don't consider editing to be done when the keyboard is closed.

**Comment by codenameone** [comment] 2019-01-23 20:04
OK, I think I didn't understand this correctly. If this is for the hide keyboard only then no an action event probably shouldn't be fired.

**Comment by jsfan3** [comment] 2019-01-24 00:46
@shannah I understood that you don't want or you cannot modify the current behavior as I requested, however I have a problem with the current behavior, maybe you can help me and you can also better understand my reasons.

You wrote that "every part of text editing on android involves some sort of _inhuman contortion_"... I don't want to give you troubles with inhuman contorted code, I only need to solve a problem :-)

In the app I'm developing there is a _crucial functionality_ that have to stay "over" the Forms, in the layeredPane. More precisely, I have a Container in the South of the layeredPane, that uses a BorderLayout. To simplify this description, think that this Container has a Button placed in its center, so I have a Button placed in the bottom-center of the layeredPane. The problem is that I have to hide this Container when the virtual keyboard is open, otherwise the input field (like a TextArea) is under the Button placed in the layeredPane.

My use case is more complex, but this description is enough. 

Hiding the Container in the LayeredPane when the virtual keyboard is opened is trivial on iPhone, because I haven't to do anything, in fact the virtual keyboard is over the Form, that is not resized.

On Android native apps and Android web-apps the Form is resized when the virtual keyboard is open, so I created a code that executes a method to show my Container when the user is not editing and another method to hide the Container when the user is editing. In short, I created _EditingListeners_, as in the code shown below.

My code works fine on native Android apps, but it cannot work on web-apps because closing the keyboard doesn't stop the editing.

This is my code for the problem that I've just tried to describe:

```
public class KeyboardUtilities {

    /**
     * Returns true if the user is editing a TextArea in the current Form: this
     * does not distinguish between a virtual keyboard and a real keyboard
     *
     * @return
     */
    public static boolean isEditing() {
        return isEditing(Display.getInstance().getCurrent());
    }

    private static boolean isEditing(Container cnt) {
        if (cnt == null) {
            return false;
        }
        for (Component cmp : cnt.getChildrenAsList(true)) {
            if (cmp instanceof Container) {
                if (isEditing((Container) cmp)) {
                    return true;
                }
            } else if (cmp instanceof TextArea) {
                if (((TextArea) cmp).isEditing()) {
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * Add EditingListeners to the given Form, at the following conditions: (1)
     * the listeners will be invoked only on Android; (2) the listeners will be
     * invoked one or more times; (3) this method relies on the fact that
     * addSizeChangedListener will be invoked on Android when the virtual
     * keyboard is opened or closed.
     *
     * @param form to which the EditingListeners will be added
     * @param isEditing Runnable to be executed one or more time during the
     * editing
     * @param isNotEditing Runnable to be executed one or more time when the
     * editing is finished
     */
    public static void addEditingListeners(OuterForm form, Runnable isEditing, Runnable isNotEditing) {
        if (ThemeUtilities.isAndroidTheme || DeviceUtilities.isSimulator()) {
            form.addSizeChangedListener(l -> {
                // form.innerForm.add(new Label("form.addSizeChangedListener invoked"));
                if (StartPoint.DEBUG) {
                    Log.p("KeyboardUtilities - Form size changed listener invoked", Log.DEBUG);
                }
                if (isEditing()) {
                    // form.innerForm.add(new Label("isEditing"));
                    if (StartPoint.DEBUG) {
                        Log.p("KeyboardUtilities EditingListener - isEditing invoked", Log.DEBUG);
                    }
                    isEditing.run();
                } else {
                    // form.innerForm.add(new Label("isNotEditing"));
                    if (StartPoint.DEBUG) {
                        Log.p("KeyboardUtilities EditingListener - isNotEditing invoked", Log.DEBUG);
                    }
                    isNotEditing.run();
                }
                form.revalidate();
            });
        }
    }

}
```

**Comment by shannah** [comment] 2019-01-24 12:58
This problem seems more directly related to the usable screen space than to whether the keyboard is opened.  E.g. If the form were to be made smaller for any reason, you would need to hide this button.

Why not test directly if the button is overlapping the textarea, and hide it in this case.  You can override the layoutContainer method of the container that contains these items to do this.  E.g.

~~~~
@Override
public void layoutContainer() {
    super.layoutContainer();
    if (checkforOverlap(theButton, theTextArea)) {
        if (theButton.isVisible()) {
             theButton.setVisible(false);
             repaint();  // <-- might not be necessary
        }
    } else {
        if (!theButton.isVisible()) {
            theButton.setVisible(true);
            repaint();   // <----- might not be necessary
        }
    }

}
~~~~

**Comment by jsfan3** [comment] 2019-01-24 13:39
I need something like this if the current behavior of the TextAreas cannot be changed (I haven't tried this library, but the description seems promising to solve the problem on Android):
https://github.com/GillesVermeulen/virtualKeyboardDetector

**Comment by shannah** [comment] 2019-01-24 13:59
It wouldn't be hard to link something like this library up to the `Display.setVirtualKeyboardListener()` and `Display.isVirtualKeyboardShowing()`.

For your purposes, though, I still think a better test would be to see if the button is overlapping something that it shouldn't be.  That sounds like that is really what you want to know.

**Comment by jsfan3** [comment] 2019-01-24 16:25
Unfortunately I have a different requirement: my button can overlap anything, except when the virtual keyboard is open ... and when it is open, the button must disappear, whether it is overlapping or not.

As you thought, can you make `Display.setVirtualKeyboardListener()` and `Display.isVirtualKeyboardShowing()` working on web-apps when run on Android? It should be great and a solution for my problem. Are these two (deprecated) APIs currently working on Android native apps? If yes, I can change my code and use them directly (because I have this problem on Android only).

**Comment by jsfan3** [comment] 2019-01-26 00:53
Thank you for these new APIs! :+1: 
Have I to wait the next Friday for the update?

**Comment by codenameone** [comment] 2019-01-26 05:19
We'll push out a new update soon to fix the regression with the menus on Windows so it will include this fix

**Closed by codenameone** 2019-01-26 05:19 UTC

**Comment by shannah** [comment] 2019-01-28 18:41
I have added support for these keyboard APis in the Javascript port now as well.  Will be available in the next update. 

Here is sample usage of the APIs:

~~~~
public void testVirtualKeyboardListeners() {
        Form f = new Form("Test Keyboard", BoxLayout.y());
        TextField tf1 = new TextField();
        f.add(tf1);
        
        TextArea ta1 = new TextArea();
        ta1.setRows(2);
        ta1.setColumns(30);
        f.add(ta1);
        
        ComboBox cb = new ComboBox<String>("Hello", "World", "Red", "Green", "Blue");
        f.add(cb);
        
        Picker picker = new Picker();
        picker.setUseLightweightPopup(true);
        picker.setType(PICKER_TYPE_STRINGS);
        picker.setStrings("Hello", "World", "Red", "Green", "Blue");
        f.add(picker);
        
        Timer t = new Timer();
        t.schedule(new TimerTask() {
            @Override
            public void run() {
                callSerially(()->{
                    Log.p("keyboard showing? "+Display.getInstance().isVirtualKeyboardShowing());
                });
            }
            
        }, 0l, 1000l);
        
        Display.getInstance().addVirtualKeyboardListener(e->{
            Boolean showing = (Boolean)e.getSource();
            if (showing) {
                Log.p("Keyboard shown");
            } else {
                Log.p("Keyboard hidden");
            }
                    
        });
        
        f.show();
    }
~~~~

**Comment by jsfan3** [comment] 2019-01-31 14:32
Thank you very much, your test code works nicely on Android native and even on iPhone native. I'll wait the Friday update to see it working also in the Javascript port.
