### ISSUE TITLE
Component.setHidden does not work for Containers based on e.g. BoxLayout

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#2241] opened 2017-10-12 19:35 UTC
To explain (my understanding of) the reason for this issue again (seems my explanation in my pull request was not clear): Component.setHidden(true) works by forcing the Component.preferredSize to Dimension(0,0) but when BoxLayout.__*getScrollSize*__ is later called when refreshing the Form, it will update the same instance of Dimension as previously returned by BoxLayout.getPreferredSize to whatever size the object has, changing the value of Dimension from (0,0) to component's actual size which cancels the effect of setHidden(). 

I proposed a solution in a push request, but was asked to file an issue instead.  

Here's (updated) code to show the issue (I've moved the Container from south to center).

Let me know if you see the same issue as I do (only tried this in the simulator). 

```
Form hideable = new Form("Hiding Container doesn't work", BoxLayout.y());
hideable.setLayout(new BorderLayout());
Container hideableContainer = new Container(BoxLayout.y());
hideableContainer.setScrollableY(true);
//Clicking "Hide list" does not hide the list, it stays visible all the time
hideable.add(BorderLayout.NORTH, new Button(Command.create("Hide list", null, (e) -> {
    hideableContainer.setHidden(!hideableContainer.isHidden());
    hideable.revalidate();
})));
hideableContainer.addAll(new Label("label1"), new Label("label2"), new Label("label3"));
hideable.add(BorderLayout.CENTER, hideableContainer);
hideable.show();
```

**Comment by ThomasH99** [comment] 2017-10-14 13:46
This seems like a significant bug (setHidden() not working), and it is preventing my app from working correctly on devices (on the simulator I've fixed  it myself in the CN1 code), so is there any chance this could be fixed in CN1 before 3.9? I've even pushed what I believe is a valid fix, but if not fixed in the platform before 3.9 it will leave me high and dry for many months...

**Comment by codenameone** [comment] 2017-10-15 07:16
`setHidden` is a feature that was added around 3.5 if I remember correctly so it didn't even exist before. Its failure as far as I understand is only for hiding a scrollable container which isn't a common use case and was probably there all along so it's probably not a regression.
3.8 is literally now. There are features that were scheduled for it 7-8 months ago and features that we'll probably have to postpone. In fact 3.9 is already full and a lot of the features scheduled for it won't make it. New issues area already going to 4.0.

Actually looking again at the source code of the test case you provided above I  think this isn't a bug. You placed a component in the center of the border layout which manipulates preferred size. The behavior is as intended and this isn't a bug. `setHidden` just changes preferred size, if the layout manager ignores that preferred size then set hidden has no meaning.

**Comment by JrmyDev** [comment] 2017-10-16 07:15
And what about that : https://github.com/codenameone/CodenameOne/issues/2228
I think it's related but not exactly same use case !

**Comment by codenameone** [comment] 2018-02-05 12:13
Looking at the comments here I'm not sure what to do with this issue. The workaround is pretty simple: Wrap the scrollable `Container` in a non-scrollable `Container` e.g. like this:

````java
Container actual = BorderLayout.center(scrollableContainer);
````

This should work fine. Changing the behavior of hidden to support scrollable widgets would be problematic. Unless there is an objection I'll close this issue.

**Closed** 2018-02-07 09:08 UTC
