### ISSUE TITLE
ToastBar causing form components to disappear

### ISSUE THREAD

**Issue by plumberg** [codenameone/CodenameOne#3550] opened 2022-02-01 18:10 UTC
**Describe the bug**
When `Toastbar.showInfoMessage("")` is called to being displayed, all other components of the form disappear, except the toolbar with Title and it's commands.
It happens only in one of my apps. 
No errors are shown in the logcat. 
Tested on simulator and iOS device.

**To Reproduce**
1. Add button (_Save my info_ in the example) with action listener that will trigger showing a ToastBar message.
2. Click on it

**Expected behavior**
The toastbar message must be displayed, every component of the form should stay in place. 

**Screenshots**

![image](https://user-images.githubusercontent.com/22183321/152025840-8d2391a6-0dbc-4ccd-8732-a08e29ab1a8f.png)
![image](https://user-images.githubusercontent.com/22183321/152025736-ab49d199-44d1-449f-9e1e-86709a6fc9d9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by shannah** [comment] 2022-02-03 13:26
Can you post a small test case to reproduce the issue?

**Comment by shai-almog** [comment] 2022-04-16 10:05
Closing due to lack of test case

**Closed by shai-almog** 2022-04-16 10:05 UTC
