### ISSUE TITLE
BrowserComponent crashes App on Android

### ISSUE THREAD

**Issue by Bitxenio** [codenameone/CodenameOne#2267] opened 2017-11-02 13:47 UTC
After the recent lib update, BrowserComponent is no longer working on Android.

Test case (substitute on Get Started App):

public void start() {
        if(current != null){
            current.show();
            return;
        }
        
        Form hi = new Form();
        hi.setLayout(new BorderLayout());
        
        BrowserComponent browserComponent = new BrowserComponent();
        hi.add(BorderLayout.CENTER, browserComponent);
        
        Button loadButton = new Button("setUrl");
        loadButton.addActionListener((ev) -> {
			browserComponent.setURL("https://www.google.es");
		});
        hi.add(BorderLayout.SOUTH, loadButton);
        hi.show();
    }

Load App, push "setUrl" button -> App crashes.
Expected result: browser component shows google webpage.

**Comment by shannah** [comment] 2017-11-02 16:03
I just added a test for this in the CN1 test suite.  Test passes on Android 4.4 (emulator) and Android 6.0 (device).  I can't seem to reproduce the problem.  

Can you provide more details about the crash?  E.g. device, android version, DDMS output of the crash?

**Comment by shannah** [comment] 2017-11-02 16:30
Likely the relevant crash report was submitted separately in https://github.com/codenameone/CodenameOne/issues/2270

That issue was fixed and will be included with the next server update on Friday.  

[This](https://github.com/codenameone/CodenameOne/commit/66373ff3d2bceeb2b4bce66ab16e86537bbefe28) commit alone fixes the issue by not running through that code path by default.

[This](https://github.com/codenameone/CodenameOne/commit/e9e6188023f575f002e8c419eff239ef3499417d) commit further guards against this issue by guarding the NPE in cases where the codepath is run.

A workaround in the mean time is to call

~~~~
Display.getInstance().setProperty("syncNativeCookies", "true");
~~~~

Somewhere before the browser component is created (e.g. in your app's init() method.

**Closed by shannah** 2017-11-02 16:30 UTC

**Comment by igo211** [comment] 2017-11-02 16:54
FYI, just tried the stated workaround, and it doesn't work - the crash still occurs.  Probably because that first fix checkin happened after the libs push today.

Also, I could be wrong (maybe there's a side-effect I'm not seeing), but I suspect the second fix check-in mentioned above does not actually address the problem.

The NPE is on the cookies hashtable itself (which is uninitialized at that point)  - however, the added null check code is on the domain value.   The null check should be on the cookies hashtable var (or an init of the cookies hashtable should occur there - either way).

**Comment by shannah** [comment] 2017-11-02 16:58
If the crash still occurs, then it is a different issue than the one I cited, and I'll require a stack trace (or a way to reproduce) to narrow it down.

**Comment by igo211** [comment] 2017-11-02 17:03
The crash still occurs with the stated workaround in place (and again, I suspect the second checkin/fix mentioned above will not fix the issue).

The stacktrace is the same as the one in https://github.com/codenameone/CodenameOne/issues/2270.

For your convienence I repeat it here:

5/com.zero211.dky E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.zero211.dky, PID: 13275
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.Hashtable.get(java.lang.Object)' on a null object reference
                                                                     at com.codename1.impl.CodenameOneImplementation.removeCookiesForDomain(CodenameOneImplementation.java:4179)
                                                                     at com.codename1.impl.android.AndroidImplementation.access$1200(AndroidImplementation.java:177)
                                                                     at com.codename1.impl.android.AndroidImplementation$AndroidBrowserComponent$1.onLoadResource(AndroidImplementation.java:4048)
                                                                     at com.android.webview.chromium.WebViewContentsClientAdapter.onLoadResource(WebViewContentsClientAdapter.java:126)
                                                                     at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:15)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by shannah** [comment] 2017-11-02 17:06
Then you didn't implement the workaround correctly.  There was only one code-path that calls the removeCookiesForDomain() method, and it is effectively cut off if you have called `Display.getInstance().setProperty("syncNativeCookies", "false");` somewhere before you create the browser component.

**Comment by igo211** [comment] 2017-11-02 17:18
OK, that's very odd....
I just rebuilt & retested it after some completely unrelated changes and now there's no crash.
So, sorry... disregard comment about workaround not working.

**Comment by igo211** [comment] 2017-11-02 17:30
Any thoughts about my other comment, re: npe guard code?

**Comment by shannah** [comment] 2017-11-02 17:39
You'll need to elaborate on why that won't fix it.  My tests are working.  There are two levels of "fix" in place.

1. That method is no longer called at all unless you explicitly set the flag.
2. It checks for null key before attempting to get value in case that code is actually run.

**Comment by igo211** [comment] 2017-11-02 17:41
#2 is the issue I'm referring to.
The NPE was on the cookies var itself, not the value it's checking for (domain).
The checked-in fix appears to be checking for a null domain value, not a null cookies hashtable.
