### ISSUE TITLE
Stopping and starting the app causes a screen distortion

### ISSUE THREAD

**Issue by carlosverdier** [codenameone/CodenameOne#2819] opened 2019-05-29 14:21 UTC
When I stop any of my apps and reopen again the screen goes wrong, but if I close and reopen once more, then it renders fine again.

This happens with a new and updated iPad, but works fine with an old 32 bits iPad mini.

I'm enclosed two videos so you can see the issue.

This is an iPad Mini with iOS 9.3.5:

https://videos.yourappeasy.com/iPadMini.mp4

This is an iPad 2018 with iOS 12.3:

https://videos.yourappeasy.com/iPad2018.mp4

**Comment by shannah** [comment] 2019-07-15 17:42
I haven't been able to reproduce this yet.  Can you post your build hints from the codenameone_settings.properties file?  (redact sensitive info).

**Comment by carlosverdier** [comment] 2019-07-15 18:20
Sure. Here you are. This is an old project, maybe some hints are not needed anymore...

`#
#Mon Jul 01 16:34:12 CEST 2019
codename1.arg.android.debug=false
codename1.arg.ios.NSCameraUsageDescription=Some functionality of the application requires your camera
package=generated
codename1.arg.vserv.scaleMode=false
codename1.arg.j2me.nativeThemeConst=0
codename1.arg.ios.NSCalendarsUsageDescription=We use the device calendar to allow users add a reminder to their preferred events
codename1.arg.ios.project_type=ios
codename1.vendor=CodenameOne
codename1.ios.provision=
userClass=src/userclasses/StateMachine.java
codename1.version=5.79
codename1.arg.javascript.googlemaps.key=*********
codename1.displayName=Viajar con Hijos
codename1.arg.ios.pods.sources=,https\://github.com/CocoaPods/Specs.git
codename1.ios.appid=**********
codename1.arg.ios.bundleVersion=1.0
userClassAbs=/Users/carlos/NetBeansProjects/Viajar con Hijos/src/userclasses/StateMachine.java
codename1.rim.signtoolCsk=
codename1.arg.ios.locationUsageDescription=Location is needed to discover events related to app content in user's city
codename1.arg.ios.application_exits=false
codename1.ios.certificatePassword=
codename1.description=
codename1.arg.ios.objC=true
codename1.arg.rim.obfuscation=false
baseClass=src/generated/StateMachineBase.java
codename1.arg.vserv.transition=300000
codename1.ios.debug.certificatePassword=******
codename1.arg.zooz.sandbox=false
codename1.arg.android.playService.maps=true
codename1.arg.gcm.sender_id=*********
codename1.arg.ios.prerendered_icon=false
codename1.arg.win.ver=8
codename1.arg.android.xapplication=<meta-data android\:name\="com.google.android.maps.v2.API_KEY" android\:value\="***********"/>
codename1.ios.release.provision=/Users/carlos/Desktop/DEV4775/Users/imac/Trabajo_Carlos/Documents/Codename/Viajar Con Hijos/Compilacion/ViajarDistribution.mobileprovision
codename1.arg.ios.plistInject=<key>UIStatusBarHidden</key><true/><key>UIViewControllerBasedStatusBarAppearance</key> <false/><key>NSAppTransportSecurity</key><dict><key>NSAllowsArbitraryLoads</key><true/><key>NSAllowsArbitraryLoadsInWebContent</key><true/></dict>
codename1.rim.certificatePassword=
codename1.arg.java.version=8
codename1.ios.debug.certificate=/Users/carlos/Desktop/DEV4775/Users/imac/Trabajo_Carlos/Documents/Codename/CERTIFICADOS_APPLE/CertificadoDevelopment.p12
codename1.arg.ios.testFlight=false
codename1.ios.release.certificatePassword=******
mainForm=Cargando
codename1.arg.ios.themeMode=modern
codename1.secondaryTitle=Viajar con Hijos
codename1.arg.javascript.stopOnErrors=false
codename1.arg.ios.statusbar_hidden=false
codename1.packageName=**********
codename1.arg.android.release=true
codename1.android.keystoreAlias=vchmag
codename1.ios.debug.provision=/Users/carlos/Desktop/DEV4775/Users/imac/Trabajo_Carlos/Documents/Codename/Viajar Con Hijos/Compilacion/ViajarDevelop.mobileprovision
codename1.arg.ios.pods=,GoogleMaps
codename1.arg.ios.add_libs=SystemConfiguration.framework;EventKit.framework
codename1.arg.ios.includePush=true
codename1.arg.android.xpermissions=<uses-permission android\:name\="android.permission.ACCESS_NETWORK_STATE"/> <uses-permission android\:name\="android.permission.READ_CALENDAR"/> <uses-permission android\:name\="android.permission.WRITE_CALENDAR"/> <uses-permission android\:name\="com.google.android.providers.gsf.permission.READ_GSERVICES"/> <uses-feature         android\:glEsVersion\="0x00020000"         android\:required\="true"/><uses-permission android\:name\="android.permission.ACCESS_NETWORK_STATE"/> <uses-permission android\:name\="com.google.android.providers.gsf.permission.READ_GSERVICES"/><uses-feature         android\:glEsVersion\="0x00020000"         android\:required\="true"/>
codename1.arg.ios.pods.platform=,7.0
codename1.icon=icon.png
codename1.rim.signtoolDb=
releaseVersion=4.0
codename1.languageLevel=5
codename1.android.keystorePassword=*******
codename1.arg.android.gradle=true
codename1.arg.android.allowBackup=false
codename1.arg.android.playService.location=true
codename1.arg.ios.dsym=false
codename1.mainName=Hijos
codename1.ios.release.certificate=/Users/carlos/Desktop/DEV4775/Users/imac/Trabajo_Carlos/Documents/Codename/CERTIFICADOS_APPLE/CertificadoDistribucion.p12
codename1.arg.android.licenseKey=*********
codename1.android.keystore=/Users/carlos/Desktop/DEV4775/Users/imac/Trabajo_Carlos/Documents/MAGPLUS/Viajar/Android/vchmag/my-release-key.keystore.file
gm\#=
codename1.arg.ios.afterFinishLaunching=[GMSServices provideAPIKey\:@"**********"];
gplcodename1.android.keystoreAlias=*******
guiResource=theme.res
codename1.arg.ios.interface_orientation=UIInterfaceOrientationPortrait\:UIInterfaceOrientationPortraitUpsideDown\:UIInterfaceOrientationLandscapeLeft\:UIInterfaceOrientationLandscapeRight
codename1.arg.ios.NSPhotoLibraryUsageDescription=Some functionality of the application requires access to your photo library
codename1.j2me.nativeTheme=nbproject/nativej2me.res
codename1.arg.ios.glAppDelegateHeader=\n\#import "GoogleMaps/GoogleMaps.h"
codename1.arg.ios.useWKWebView=true
codename1.ios.certificate=
`

**Comment by shannah** [comment] 2019-07-15 22:12
I believe I have this fixed now.  Since it is intermittent, it is possible that my fix misses some edge cases, but I was able to reproduce it fairly consistently before my [fix](https://github.com/codenameone/CodenameOne/commit/738fc9b28aeb8909bee37ab25d565086f30e0081), and can't seem to reproduce it anymore.

This fix will be included in the next update.

**Closed by shannah** 2019-07-15 22:12 UTC
