### ISSUE TITLE
Top-only border changes to bottom-only when theme.res file is opened and saved.

### ISSUE THREAD

**Issue by dekromant** [codenameone/CodenameOne#2940] opened 2019-10-29 07:31 UTC
I have created a custom style with rectangular border. I've set the border to be 'top-only'. Then I saved the theme.res file. Built and run the app and it works fine, the border is 'top-only'. After that, when I open theme.res file and just save it, it automatically changes 'top-only' to 'bottom-only' border. It does it every time I save theme.res. It gets very annoying to change it back to 'top-only'. I'm using Windows 10, Netbeans. Codename one Designer version 1.1

**Comment by shannah** [comment] 2020-01-23 14:04
Duplicate of https://github.com/codenameone/CodenameOne/issues/2993

**Closed by shannah** 2020-01-23 14:04 UTC
Labels: duplicate
