### ISSUE TITLE
IOException on some models of Android only

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2693] opened 2019-02-02 23:59 UTC
The following code generates an `IOException` only on some Android brands and models (for example  [Huawei Honor 6x](https://www.gsmarena.com/honor_6x-8388.php) and Google Pixel 3XL), while it works fine on other Android brands (like Samsung Galaxy models), on iPhone, on Javascript.

```
public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hi World"));
        hi.show();

        try {
            String path = FileSystemStorage.getInstance().getAppHomePath() + "test.jpg";
            Image img = Image.createImage(1000, 700);
            OutputStream out = FileSystemStorage.getInstance().openOutputStream(path);
            ImageIO.getImageIO().save(img, out, ImageIO.FORMAT_JPEG, 0.6f);
            Log.p("ImageUtilities.reduceImageFileSize - Original file size: " + FileSystemStorage.getInstance().getLength(path) / 1024 + "kbyte", Log.DEBUG);
            Log.p("ImageUtilities.reduceImageFileSize - Original dimensions: " + ImageIO.getImageIO().getImageSize(path).toString(), Log.DEBUG);
        } catch (IOException ex) {
            Dialog.show("Exception", ex.getMessage(), "Ok", null);
            Log.e(ex);
        }
    }
```

![screenshot_20190203-004634](https://user-images.githubusercontent.com/1997316/52170663-c9ea0400-274e-11e9-8400-58c962458f36.png)

**Comment by codenameone** [comment] 2019-02-03 04:19
@shannah if you can't reproduce this reassign it to me

**Comment by jsfan3** [comment] 2019-02-03 11:33
I better inspected this issue and I discovered that there is something strange even when the issue is not reproduced. I attach the native logs of two devices: note that the line `Log.p("ImageUtilities.reduceImageFileSize - Original dimensions: " + ImageIO.getImageIO().getImageSize(path).toString(), Log.DEBUG);` doesn't log anything even on Samsung Galaxy that doesn't show the Dialog with the exception. 

Google Pixel 3 XL (reproduces the issue) -> 
[GooglePixel3XL.log](https://github.com/codenameone/CodenameOne/files/2825461/GooglePixel3XL.log)

Samsung Galaxy S9+ (doesn't reproduce the issue) -> 
[SamsungGalaxy.log](https://github.com/codenameone/CodenameOne/files/2825462/SamsungGalaxy.log)

**Comment by shannah** [comment] 2019-02-04 14:13
I reproduced this issue on my Nexus 5/Android 6.  I have posted a fix in git.

**Closed by shannah** 2019-02-04 14:13 UTC
