### ISSUE TITLE
Google Native Maps addPath function doesn't work in iOS

### ISSUE THREAD

**Issue by rochanas** [codenameone/CodenameOne#3559] opened 2022-02-23 14:18 UTC
**Describe the bug**
When trying to use the addPath function in the Google Native Maps extension, it doesn't work when using an iOS device (works fine in the simulator and Android). The path doesn't display on the screen and a null exception happens. Here are the logs from my test application:

Exception: java.lang.NullPointerException - null
java.lang.NullPointerException
    at com_codename1_googlemaps_InternalNativeMapsStub.addToPath:125
    at com_codename1_googlemaps_MapContainer.addPath:878
    at com_codename1_twentyminutesoutside_MyApplicationMain.showMapNew:223
    at com_codename1_twentyminutesoutside_MyApplicationMain.start:133
    at com_codename1_twentyminutesoutside_MyApplicationMainStub.run:31
    at com_codename1_ui_Display.processSerialCalls:1368
    at com_codename1_ui_Display.mainEDTLoop:1155
    at com_codename1_ui_RunnableWrapper.run:120
    at com_codename1_impl_CodenameOneThread.run:176
    at java_lang_Thread.runImpl:153

**To Reproduce**
The code below will reproduce the problem when run on an iOS device, after clicking the Add Path button. addMarker works fine, but addPath does not. 

        Form f = new Form(new BorderLayout());
        f.setScrollableY(false);        
        MapContainer cnt = new MapContainer(HTML_API_KEY);        
        cnt.zoom(new Coord(51.1753601, -115.5619419), 15);
                       
        Button btnAddPath = new Button("Add Path");
        btnAddPath.addActionListener(e->{
            Style s = new Style();
            s.setBgTransparency(0);
            s.setFgColor(0xff0000);
            FontImage markerImg = FontImage.createMaterial(FontImage.MATERIAL_PLACE, s, 3);
            cnt.addMarker(EncodedImage.createFromImage(markerImg, false),new Coord(51.1753601, -115.5619419),"Hi marker","Optional long description",evt -> {
                    ToastBar.showMessage("You clicked the marker", FontImage.MATERIAL_PLACE);
                }
            );  
            
            cnt.setPathStrokeColor(0xff0000);
            cnt.setPathStrokeWidth(5);
            cnt.addPath(new Coord(51.1753601, -115.5619419), new Coord(51.177001, -115.553495));
        });
         
        f.add(CENTER, cnt).add(SOUTH, btnAddPath);
        f.show();    

**Expected behavior**
I expect the path to display and no error to occur. 

**Smartphone (please complete the following information):**
iPad Air running iOS 15.1 and an iPhone 6 running iOS 12.5.5 both have this problem

**Comment by shannah** [comment] 2022-02-25 14:47
I just built this test case and was unable to reproduce this issue.  Test devices were iPhoneX on iOS 15.4 and iPhone SE on iOS 12.3

Are you using the latest release of the Google Maps cn1lib?  Try updating to the latest and see if this fixes it for you.

**Comment by shannah** [comment] 2022-02-28 15:12
Closing for now.  Will reopen if new information is obtained and/or confirmation of issue with latest Googlemaps plugin is received.

**Closed by shannah** 2022-02-28 15:12 UTC

**Comment by rochanas** [comment] 2022-02-28 23:58
I tried refreshing the CN1 libs, but the refresh might have not been going through properly. On a new project my ios maps version was 2.7.0, but this particular one was stuck at 2.6.0. I deleted all references to Googlemaps in my project, then redownloaded it. Now that it's on 2.7.0, the error does not happen anymore (leaving these notes incase someone else has the same issue). Thanks for your help!
