### ISSUE TITLE
Safe area causing margin error when returning from landscape

### ISSUE THREAD

**Issue by jnorth515** [codenameone/CodenameOne#3036] opened 2020-03-04 08:51 UTC
Hi, we have implemented the safe areas to forms on our app. This seems to work well when changing orientation from portrait to landscape. However, we have found that when returning from landscape to portrait some components do not return to their normal size. The images below are taken from the Codename One safe area samples code. Please see the link below and the images attached. This seems to affect tabs and also anything in the NORTH of BorderLayout.
![How it should look in Portrait](https://user-images.githubusercontent.com/61280167/75861379-32ddf880-5df5-11ea-82ff-c95bc0e631ec.png)
![Returning from Landscape to Portrait](https://user-images.githubusercontent.com/61280167/75861399-3f625100-5df5-11ea-8d01-7b62cfec2659.png)

https://github.com/codenameone/CodenameOne/blob/master/Samples/samples/SafeAreasSample/SafeAreasSample.java

**Comment by shannah** [comment] 2020-03-27 13:55
I believe this is already fixed.  I can't reproduce it with the SafeAreaSample.  Please provide a test case that reproduces the issue, and I can look at it further.

**Comment by jnorth515** [comment] 2020-04-01 09:27
Hi, thank you for getting back to me. How can i provide you with a test case? What do you need from me? I took the code from the sample and simply applied it to a form. Using the Simulator I get the results shown in the images.

**Comment by shannah** [comment] 2020-04-01 13:40
If you're using that sample, then it is fixed.  You may need to wait for the latest update to get the latest changes.  Or you could build it against sources to verify right now.

**Comment by jnorth515** [comment] 2020-04-02 15:50
I'm sure that it is fixed and an update will resolve the issue but I followed [this](https://www.codenameone.com/blog/how-to-use-the-codename-one-sources.html) tutorial to do as you suggested and "build it against sources to verify right now." I now see the below after changing orientation from landscape to portrait. Seems I have missed something however I have no errors when running the project

The only part of the tutorial I could not make sense of was the "Update August 10, 2018 - You will need to build the codenameone-skins project using the build.xml file in its root directory in order to generate some skins that are required to build the JavaSE project." 

![Screenshot 02_04_2020 16_36_38 (2)](https://user-images.githubusercontent.com/61280167/78269809-fab7fb80-7501-11ea-8c4f-aac8851f0c68.png)
![Screenshot 02_04_2020 16_35_58 (2)](https://user-images.githubusercontent.com/61280167/78269835-0277a000-7502-11ea-934e-2ccc58c1c8be.png)

**Comment by shannah** [comment] 2020-04-02 16:30
OK.  I've finally been able to reproduce the issue. It is fixed in git.  will be part of update tomorrow.

**Closed by shannah** 2020-04-02 16:30 UTC

**Comment by jnorth515** [comment] 2020-04-03 08:14
Many thanks for your help!
