### ISSUE TITLE
Showing browser component on Android causes crash (related to cookies?)

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#2270] opened 2017-11-02 16:09 UTC
The following stacktrace is from android studio:

11-02 12:04:39.726 3478-3478/com.zero211.dky E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.zero211.dky, PID: 3478
                                                               java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.Hashtable.get(java.lang.Object)' on a null object reference
                                                                   at com.codename1.impl.CodenameOneImplementation.removeCookiesForDomain(CodenameOneImplementation.java:4179)
                                                                   at com.codename1.impl.android.AndroidImplementation.access$1200(AndroidImplementation.java:177)
                                                                   at com.codename1.impl.android.AndroidImplementation$AndroidBrowserComponent$1.onLoadResource(AndroidImplementation.java:4048)
                                                                   at com.android.webview.chromium.WebViewContentsClientAdapter.onLoadResource(WebViewContentsClientAdapter.java:126)
                                                                   at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:15)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by shannah** [comment] 2017-11-02 16:31
Duplicate of https://github.com/codenameone/CodenameOne/issues/2267

**Closed by shannah** 2017-11-02 16:31 UTC
