### ISSUE TITLE
Screen flickers on Android when keyboard is dismissed first time

### ISSUE THREAD

**Issue by amiga** [codenameone/CodenameOne#1804] opened 2016-06-20 15:04 UTC
OK, shortest possible way to recreate in code follows. Steps to see error:

- run app  on android
- tap first textfield (with blah) in it, hit "next" button in android keyboard to go to next textfield
- tap "tick" in bottom right of the keyboard on the second textfield when it closes observe screen jerk (doesnt always happen try again a few times to see it, leave app come back to recreate)

doesnt look like much in this test app but in my app its quite a nasty jerky which is more visible due to the colours of the components etc I have used.

public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World");
        hi.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
        hi.addComponent(new Label("Hi World"));
        hi.addComponent(new Label("Hi World"));
        hi.addComponent(new Label("Hi World"));
        hi.addComponent(new Button("Hi World"));
        hi.addComponent(new Button("Hi World"));
        hi.addComponent(new Label("Hi World"));
        hi.addComponent(new TextField("blah"));
        hi.addComponent(new TextField("tap me then dismiss the keyboard"));
        hi.addComponent(new Label("Hi World"));
        hi.addComponent(new Button("Hi World"));
        hi.addComponent(new Label("Hi World"));
        hi.addComponent(new Label("Hi World"));
        hi.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}

**Comment by shannah** [comment] 2016-06-20 16:51
@amiga Any chance you can post a video of this issue.  I can't reproduce on my Nexus 5.  The screen does shift up (on keyboard open) and down (on keyboard close), but I wouldn't describe it as a jerk, and this behaviour is correct as the canvas is supposed to shift up on keyboard open to prevent the textfield from being covered by the keyboard.

**Comment by amiga** [comment] 2016-06-21 15:59
Sent you the video hopefully you can see what I mean. From playing all day I definitely feel like the keyboard code has had a rejig somehow, my forms don't layout when the keyboard pops up, no call to sizeChanged()? I can't quite pin point what the issue is, may look into code soon if client keeps throttling me :-) Thanks.

**Comment by amiga** [comment] 2016-06-28 15:27
did you managed to recreate and look at this?

**Comment by codenameone** [comment] 2016-06-29 09:28
@shannah did you look at the video?

**Comment by shannah** [comment] 2016-06-29 16:30
Yes.  I looked at the video.  Haven't been able to reproduce myself yet.

**Comment by amiga** [comment] 2016-06-29 16:36
Suprised you arent getting any more reports. Did you see it in the video,
happens on this app if you close keyboard,
http://codename-one.appspot.com/5688779121098752/4f4717b1-a964-4298-b04b-d95b1e91a35a/MyApplication-release.apk

Wondering if I need to adjust my layouts or something but it was working
fine for a long time.

On 30 June 2016 at 00:30, Steve Hannah <notifications@github.com> wrote:

> Yes. I looked at the video. Haven't been able to reproduce myself yet.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1804#issuecomment-229412130>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEJ59txIOavmA3zMrmeUPBLJ9pYRsRWks5qQp2vgaJpZM4I5yxn>
> .
>



-- 
Gareth Murfin
(Android Freelancer - www.garethmurfin.co.uk)

**Comment by shannah** [comment] 2016-06-29 21:29
I have reproduced the issue and fixed it.  Will be included with next server update.

**Closed by shannah** 2016-06-29 21:29 UTC

**Comment by amiga** [comment] 2016-06-30 00:07
oh mate i owe you a thousand kisses!!!!!!! not gay but you know.

On 30 June 2016 at 05:29, Steve Hannah <notifications@github.com> wrote:

> I have reproduced the issue and fixed it. Will be included with next
> server update.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/codenameone/CodenameOne/issues/1804#issuecomment-229494642>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEJ5xplSEC6_AASzVLfDb58HtwUWNgNks5qQuOcgaJpZM4I5yxn>
> .
>



-- 
Gareth Murfin
(Android Freelancer - www.garethmurfin.co.uk)
