### ISSUE TITLE
Codename One designer and preferences not opening

### ISSUE THREAD

**Issue by jscrump59** [codenameone/CodenameOne#2854] opened 2019-06-26 16:22 UTC
Computer: Dell M4500, Quad Core, 8GB
OS: Linux Mint 19.1
Platform: NetBeans 8.2
CodenameOne Plugin: 6.0
java: openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

java -Xms128m -Xmx750m -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -ea -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -Djdk.http.auth.tunneling.disabledSchemes="" -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/home/jscrump/cn1/java_error.log -XX:HeapDumpPath=/home/jscrump/cn1/java_error.hprof -jar /home/jscrump/.codenameone/designer_1.jar /home/jscrump/crumptech/xxxxxxxxxx/com/crumptech/services/mobile/xxxxxxxxxx/src/lang.res
Retina Scale: 1.0
2019-06-26 11:11:40.887:INFO:oejs.Server:jetty-8.0.y.z-SNAPSHOT
2019-06-26 11:11:40.947:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:9000 STARTING
Jun 26, 2019 11:11:41 AM org.jdesktop.application.LocalStorage getId
WARNING: unspecified resource Application.id using ResourceEditorApp

No error files generated

**Comment by codenameone** [comment] 2019-07-03 08:05
Duplicate of #2747

**Closed by codenameone** 2019-07-03 08:05 UTC
Labels: duplicate
