### ISSUE TITLE
iOS port shows the text or hint text from another TextField on the form

### ISSUE THREAD

**Issue by codenameone** [codenameone/CodenameOne#1199] opened 2015-03-27 15:47 UTC
Original [issue 1200](https://code.google.com/p/codenameone/issues/detail?id=1200) created by codenameone on 2014-10-01T14:27:01.000Z:

IPlease clearly state whether the issue relates to a device/the simulator or
<b>the tools.</b>
iOS devices
<b>If related to a device be sure to specify exactly which device with as much</b>
<b>details as possible.</b>

iPad 2 (iOS ver 8.0.2), iPhone 4 (iOS ver 7.1.2 and iPod Touch running iOS ver 6.1.6)

In iPhone port, when you have two TextFields in a form and you click on other textField, the text from the other field is shown briefly. Let me give an example:
Form A has two TextFields F1 and F2.
When you click on F1 and then click on F2, it briefly shows the text from F1, before showing the text of F2.

Also when one of the field is a password field and you enter some text in it and move to another field. Then come back on the first field and try to enter some more letters. In that case it clears the previous inputed values.

Also sometimes the field is becoming blank and when you click on other field and then when you click back on the field, it shows the value.

<b>What steps will reproduce the problem?</b>
1. Have a Form with two or more TextFields
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

The TextFields should not show value or hitText from other fields.
The password TextField should retain value when user clicks on it again to enter more chars.
The TextField should not become blank when user clicks on other field.

<b>What version of the product are you using? On what operating system?</b>

Latest version of Codenameone on Mac OS.

<b>Please provide any additional information below.</b>

This issue is created as per the discussion on following topic:
http://www.codenameone.com/discussion-forum.html?place=topic%2Fcodenameone-discussions%2FobCqt9y8kDs%2Fdiscussion

**Comment by shannah** [comment] 2015-05-09 00:22
Cannot reproduce.  Using same test case from https://github.com/codenameone/CodenameOne/issues/1073.

Tried entering text in one field and clicking in another.  Did this multiple times.  Tested on iPhone 4S with iOS 8.2. 

Closing issue for now.  Will reopen if you can provide a test case to reproduce.

**Closed by shannah** 2015-05-09 00:22 UTC
Labels: bug, Priority-High, Type-Defect
