### ISSUE TITLE
UWP: Windows Store Builds broken

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#2114] opened 2017-05-16 19:05 UTC
Testing on Microsoft Lumia 640 LTE, OS build: 10.0.15063.297

After updating my app I submitted a UWP Windows Store Build for final testing. My app works find when the build type is Mobile Debug. With a Windows Store build the icon displays then a black screen.

I build a brand new project in Netbeans using the Hello World GUI code. I submitted a UWP build and it ran fine on the above device. I made 1 change to the project using the Codename One Settings, I changed the build type from Mobile Debug to Windows Store Build. When I installed the app on the above device I had the same black screen problem. When the app was launched the icon displayed then a black screen and nothing else. So it looks like the Windows Store Build is broken period.

I have not yet tried to submit a new build to the Windows store using a Windows Store Upload build type but I think that may be broken too.

**Comment by codenameone** [comment] 2017-05-17 05:57
We are looking into it, this seems to be a regression with the latest version of .net. 

We contacted Microsoft and are waiting for a reply from them.

**Comment by shannah** [comment] 2017-05-25 18:42
Fixed.  Will be included with next server update.

**Closed by shannah** 2017-05-25 18:42 UTC
