### ISSUE TITLE
issue in android side

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3309] opened 2020-11-17 21:32 UTC
Please check why this screen is very different in android side

![image](https://user-images.githubusercontent.com/16245755/99453086-d119dc00-28fa-11eb-9864-8a0c35f6bf53.png)

**Comment by javieranton-zz** [comment] 2020-11-17 23:20
Looks like you need to `revalidate()` the form after calling `show()` because you have a `Label`/`TextArea` spanning multiple rows. Its gets calculated by the layout manager at runtime and it will incorrectly guess its height based on device/SO

Alternatively, you can force its dimensions in `calcPreferredSize`

**Comment by shai-almog** [comment] 2020-11-18 05:00
I can't tell for sure without code but it looks like this isn't a scrollable form. So there isn't enough room to render everything in the second screenshot. Notice the image is of the same size and so are the buttons (roughly) so there's no room for the text. 

I don't know how you implemented the circle so I can't really comment on that. Try to reproduce these in the desktop mode of the simulator by resizing to various sizes. You can then debug and use the component inspector to understand what went wrong.

**Comment by DurankGts** [comment] 2020-11-18 20:13
this the code to page1 in my tabs

private Container getPageInfo1() {

        //Strings localized
        //------------------------
        final String txtWelcome = Utils.getLocalizeWord(KeyLang.gw_welcome, "Welcome",true);
        final String txtInfo    = Utils.getLocalizeWord(KeyLang.gw_info1, "The app that allows you to feel safe while living your life without worries.");

        Container cntBgnInfo    = new Container(BoxLayout.y(),Uiid.gw_bgnContenPage);
        Container cntBgnIcon    = new Container(new LayeredLayout());
        
        Image i1     = Utils.getMaterialImageUnselected(FontImage.MATERIAL_FIBER_MANUAL_RECORD,  Uiid.gw_circle1);
        Image i2     = Utils.getMaterialImageUnselected(FontImage.MATERIAL_FIBER_MANUAL_RECORD,  Uiid.gw_circle2);
        Image i3     = Utils.getFixedFontelloIcon(FontelloIcon.icon_mobile, Uiid.gw_iconMobile, false);
        Image i4     = Utils.getFixedFontelloIcon(FontelloIcon.icon_shield, Uiid.gw_iconShield, false);

        Label lbWelcome     = new Label(txtWelcome, Uiid.gw_welcome);
        SpanLabel lbInfo    = new SpanLabel(txtInfo, Uiid.gw_info1);

        //Container cntIcons = new Container(new LayeredLayout());
        //cntIcons.add(FlowLayout.encloseCenterMiddle(new Label(i1)));
        //cntIcons.add(FlowLayout.encloseCenterMiddle(new Label(i2)));
        
        cntBgnIcon.add(FlowLayout.encloseCenterMiddle(new Label(i1,Uiid.gw_circle1)));
        cntBgnIcon.add(FlowLayout.encloseCenterMiddle(new Label(i2,Uiid.gw_circle2)));
        cntBgnIcon.add(FlowLayout.encloseCenterMiddle(new Label(i3,Uiid.gw_iconMobile)));
        cntBgnIcon.add(FlowLayout.encloseCenterMiddle(new Label(i4,Uiid.gw_iconShield)));

        cntBgnInfo.add(FlowLayout.encloseCenterMiddle(cntBgnIcon));
        cntBgnInfo.add(lbWelcome);
        cntBgnInfo.add(lbInfo);

        return cntBgnInfo;
    }

**Comment by DurankGts** [comment] 2020-11-18 20:14
Page2
private Container getPageInfo2() {

        //Strings localized
        //------------------------
        final String txtCreateYourList  = Utils.getLocalizeWord(KeyLang.gw_createYourList, "Create your list",true);
        final String txtInfo1           = Utils.getLocalizeWord(KeyLang.gw_info2, "of emergency Contacts");
        final String txtInfo2           = Utils.getLocalizeWord(KeyLang.gw_info3, "Your friends, family or close friends will be able to know about you with a simple button in case of risks.");

        Container cntBgnInfo            = new Container(BoxLayout.y(),Uiid.gw_bgnContenPage);
        Container cntBgnIcon            = new Container(new LayeredLayout());
        
        SpanLabel lbCreateList          = new SpanLabel(txtCreateYourList, Uiid.gw_createYourList);
        SpanLabel lbInfo1               = new SpanLabel(txtInfo1, Uiid.gw_info2);
        SpanLabel lbInfo2               = new SpanLabel(txtInfo2, Uiid.gw_info1);
        
        Image i1     = Utils.getMaterialImageUnselected(FontImage.MATERIAL_FIBER_MANUAL_RECORD,  Uiid.gw_circle1);
        Image i2     = Utils.getMaterialImageUnselected(FontImage.MATERIAL_FIBER_MANUAL_RECORD,  Uiid.gw_circle2);
        Image i3     = Utils.getFixedFontelloIcon(FontelloIcon.icon_network, Uiid.gw_iconNetWork, false);

        cntBgnIcon.add(FlowLayout.encloseCenterMiddle(new Label(i1,Uiid.gw_circle1)));
        cntBgnIcon.add(FlowLayout.encloseCenterMiddle(new Label(i2,Uiid.gw_circle2)));
        cntBgnIcon.add(FlowLayout.encloseCenterMiddle(new MyLabel(i3,Uiid.gw_iconNetWork)));

        cntBgnInfo.add(cntBgnIcon);
        cntBgnInfo.add(lbCreateList);
        cntBgnInfo.add(FlowLayout.encloseCenterMiddle(lbInfo1));
        cntBgnInfo.add(FlowLayout.encloseCenterMiddle(lbInfo2));

        return cntBgnInfo;
    }

**Comment by DurankGts** [comment] 2020-11-18 20:14
Page3
private Container getPageInfo3() {

        //Strings localized
        //------------------------
        final String txtReceiveAssistance = Utils.getLocalizeWord(KeyLang.gw_receiveAssistance, "Receive Assistance");
        final String txtInfo    = Utils.getLocalizeWord(KeyLang.gw_info4, "In case you need a tire change, crane, traffic accident and others ...");

        Container cntBgnInfo     = new Container(BoxLayout.y(),Uiid.gw_bgnContenPage);
        SpanLabel lbReceiveAssit = new SpanLabel(txtReceiveAssistance, Uiid.gw_welcome);
        SpanLabel lbInfo         = new SpanLabel(txtInfo, Uiid.gw_info1);
        
        Container cntBgnIcon    = new Container(new LayeredLayout());
        Image i1     = Utils.getMaterialImageUnselected(FontImage.MATERIAL_FIBER_MANUAL_RECORD,  Uiid.gw_circle1);
        Image i2    = Utils.getMaterialImageUnselected(FontImage.MATERIAL_FIBER_MANUAL_RECORD,  Uiid.gw_circle2);
        Image i3     = Utils.getFontelloIcon(FontelloIcon.icon_tow, Uiid.gw_iconMobile, false);
        //Image i2     = Utils.getFontelloIcon(FontelloIcon.icon_tow, Uiid.gw_iconShield, false);
        //Image i3     = Utils.getFontelloIcon(FontelloIcon.icon_tow, Uiid.gw_iconShield, false);

        cntBgnIcon.add(FlowLayout.encloseCenterMiddle(new Label(i1,Uiid.gw_circle1)));
        cntBgnIcon.add(FlowLayout.encloseCenterMiddle(new Label(i2,Uiid.gw_circle2)));
        cntBgnIcon.add(FlowLayout.encloseCenterMiddle(new Label(i3,Uiid.gw_iconMobile)));
        //cntBgnIcon.add(FlowLayout.encloseRightBottom(new Label(i2)));
        //cntBgnIcon.add(Container.encloseIn(new FlowLayout(Component.LEFT, Component.BOTTOM), new Label(i3)));

        cntBgnInfo.add(cntBgnIcon);
        cntBgnInfo.add(lbReceiveAssit);
        cntBgnInfo.add(lbInfo);

        return cntBgnInfo;
    }

**Comment by DurankGts** [comment] 2020-11-18 20:21
I solved the issue. When I have in the theme.res various themes with de similar names your build server don't reconize the selected theme inside the theme.res . I delete the other theme and it work perfectly. the other issue now is that a layeredLayout don't wrapped to its inside the components. this margin or padding is showed in my layered layout.

![image](https://user-images.githubusercontent.com/16245755/99583533-046f7000-29ba-11eb-8021-4c8b275e45af.png)

**Comment by DurankGts** [comment] 2020-11-18 20:32
this the code to my tab

    public GuiWelcome(final MyForm sender) {
        this.fSender        = sender;
        String methodName   = "GuiWelcome";
        try {

            myForm = new MyForm();
            myForm.setUIID(Uiid.gupi_background);
            myForm.setSafeArea(true);
            myForm.setLayout(new BorderLayout());
            
            final String txtSkip = Utils.getLocalizeWord(KeyLang.gw_skip, "Skip", true);
            final String txtNext = Utils.getLocalizeWord(KeyLang.gw_next, "Next",true);
            final String txtBack = Utils.getLocalizeWord(KeyLang.gw_back, "Back", true);
            
            MyCheckBox rb1 = new MyCheckBox(true,FontImage.MATERIAL_FIBER_MANUAL_RECORD, Uiid.gw_tabsDots,FontImage.MATERIAL_FIBER_MANUAL_RECORD, Uiid.gw_tabsDotsOff);
            MyCheckBox rb2 = new MyCheckBox(false,FontImage.MATERIAL_FIBER_MANUAL_RECORD, Uiid.gw_tabsDots,FontImage.MATERIAL_FIBER_MANUAL_RECORD, Uiid.gw_tabsDotsOff);
            MyCheckBox rb3 = new MyCheckBox(false,FontImage.MATERIAL_FIBER_MANUAL_RECORD, Uiid.gw_tabsDots,FontImage.MATERIAL_FIBER_MANUAL_RECORD, Uiid.gw_tabsDotsOff);
            
            btnSkip = new Button(txtSkip, Uiid.gw_skip);
            Button btnNext = new Button(txtNext, Uiid.gw_next);
            btnSkip.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    
                    try {
                        int index = t.getSelectedIndex();
                        if (index == TABS_ID.PAGE_1) {
                             showGuiPhoneNumberValiation();
                        } else {
                            index--;
                            t.setSelectedIndex(index,true);
                            t.revalidate();
                        }
                    } catch (Exception e) {
                        Log.e(TAG, methodName+"()->Error:" + e.toString());
                    }
                }
            });
            btnNext.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    
                    try {
                        int index = t.getSelectedIndex();
                        int maxTab = t.getTabsContainer().getComponentCount();
                        if (index < maxTab-1) {
                            index++;
                            t.setSelectedIndex(index,true);
                            t.revalidate();
                        } else {
                            showGuiPhoneNumberValiation();
                        }
                    } catch (Exception e) {
                        Log.e(TAG, methodName+"()->Error:" + e.toString());
                    }
                }
            });
            
            Container cntBgnButtonMove = new Container(new GridLayout(2),Uiid.gw_bgnButtonsMove);
            cntBgnButtonMove.add(btnSkip);
            cntBgnButtonMove.add(btnNext);
            
            Container tabsFlow = FlowLayout.encloseCenterMiddle(rb1, rb2,rb3);
            tabsFlow.setUIID(Uiid.gw_bgnFlowTabsButtons);
            
            Container cntFooter = new Container(BoxLayout.y());
            cntFooter.add(tabsFlow);
            cntFooter.add(cntBgnButtonMove);
            cntFooter.revalidate();
            //-----------------------
            //BODY
            //-----------------------
            t = new Tabs();
            t.setTabPlacement(Component.BOTTOM);
            t.setTabTextPosition(Tabs.BOTTOM);
            t.setUIID("Container");
            //t.setTabUIID(Uiid.gm_bgnTabs);
            t.setTabsContentGap(0);
            t.setChangeTabContainerStyleOnFocus(true);
            t.setSwipeActivated(false);
            t.addSelectionListener(new SelectionListener() {
                @Override
                public void selectionChanged(int oldSelected, int newSelected) {
                    
                    Log.i(TAG, methodName + "()->TABS_ID:"+newSelected);
                    switch (newSelected) {
                        case TABS_ID.PAGE_1:
                            if (!rb1.isChecked()) {
                                rb1.setChecked(true);
                                rb2.setChecked(false);
                                rb3.setChecked(false);
                            }
                            btnSkip.setText(Utils.getLocalizeWord(KeyLang.gw_skip, "Skip", true));
                            break;
                        case TABS_ID.PAGE_2:
                            if (!rb2.isChecked()) {
                                rb1.setChecked(false);
                                rb2.setChecked(true);
                                rb3.setChecked(false);
                            }
                            btnSkip.setText(Utils.getLocalizeWord(KeyLang.gw_back, "Back", true));
                            break;
                        case TABS_ID.PAGE_3:
                            if (!rb3.isChecked()) {
                                rb1.setChecked(false);
                                rb2.setChecked(false);
                                rb3.setChecked(true);
                            }
                            btnSkip.setText(Utils.getLocalizeWord(KeyLang.gw_back, "Back", true));
                            break;
                    }
                    t.revalidate();
                    tabsFlow.revalidate();
                }
            });
            //---------------------------
            //CONTENT
            //---------------------------
            t.addTab("", getPageInfo1());
            t.addTab("", getPageInfo2());
            t.addTab("", getPageInfo3());
            //---------------------------
            myForm.add(BorderLayout.CENTER,t);
            myForm.add(BorderLayout.SOUTH,cntFooter);
            t.hideTabs();
            myForm.revalidate();
            
        } catch (Exception e) {
            Log.e(TAG, methodName+"()->Error:" + e.toString());
        }
    }

**Comment by DurankGts** [comment] 2020-11-18 20:40
shai why don't adapt to the screen all the component if Always I'm using millimeters?
![image](https://user-images.githubusercontent.com/16245755/99585437-b5770a00-29bc-11eb-9193-751ec8ceff6f.png)

**Comment by DurankGts** [comment] 2020-11-18 20:41
![image](https://user-images.githubusercontent.com/16245755/99585547-de979a80-29bc-11eb-9c81-b99e5f9a371c.png)

**Comment by DurankGts** [comment] 2020-11-18 21:05
this margin or padding is generated by LayeredLayout. Why? I don't Know

![image](https://user-images.githubusercontent.com/16245755/99587913-38e62a80-29c0-11eb-8be4-b5fe5ec4a4b5.png)

**Comment by javieranton-zz** [comment] 2020-11-21 10:08
Might help to see a screenshot of padding amd margin settings for this UIID

**Comment by DurankGts** [comment] 2020-11-21 18:09
I attached the Uiid of this icons gw_circle1, and gw_circle2. The LayeredLayout don't have Uiid. the Container by default I seet margin and padding to 0. See the code of every Page in tabs attached. The problem is in the LayeredLayout or the FontImage Method that Insert internal padding to every FontImage.

**Comment by shai-almog** [comment] 2020-11-22 06:41
Millimeters aren't a magic bullet. A phone that has an 8 inch screen will have fewer millimeters than a phone with a 6 inch screen. So you'll run out of space soon enough if your form isn't scrollable as it seems from your code.

**Comment by javieranton-zz** [comment] 2020-11-22 10:45
I suggest setting a container's background image with your fontimage icon. This way you will be able to control its exact dimensions. You will have more freedom to play with background styles/resizing

    Style coolIconStyle = new Style();
                coolIconStyle.setBgColor(0xf2f2f2);
		coolIconStyle.setFgColor(0xff0000) : Utils.getInstance().getCoolColor());
		Image coolIconImg = com.codename1.ui.EncodedImage.createFromImage(FontImage.createMaterial(FontImage.MATERIAL_FIBER_MANUAL_RECORD, coolIconStyle, 10.6f),true);
		boxBackground.getAllStyles().setBgTransparency(0);
		boxBackground.getAllStyles().setBackgroundType(Style.BACKGROUND_IMAGE_ALIGNED_CENTER);
		boxBackground.getAllStyles().setBgImage(coolIconImg);

**Comment by DurankGts** [comment] 2020-11-22 12:50
The background image of my first circle it just solve that image,  but the other issue it will continue because i will need layered layout to others item.

**Comment by DurankGts** [comment] 2020-11-22 12:52
shai could you provide any solution or explain us why the layered layout have this margin or padding if don't have Uiid with that features?

**Comment by javieranton-zz** [comment] 2020-12-13 23:07
Hi @DurankGts I recently had a similar issue. I ended up forcing the problematic layer's size with an override of calcPreferredSize if that helps

**Comment by DurankGts** [comment] 2020-12-14 12:11
orverriding the LayeredLayout calcPreferredSize?

**Comment by javieranton-zz** [comment] 2020-12-14 12:17
overriding the one of the offending item (one of the pieces in the layers was stretching the layered layout in my case)

**Comment by DurankGts** [comment] 2020-12-14 12:20
Could you provide a way? I can't understand you very well

**Comment by javieranton-zz** [comment] 2020-12-14 12:24
In my case, I was enclosing like so:

    thisContainer.add(LayeredLayout.encloseIn(labelsContainer,FlowLayout.encloseCenterMiddle(arcProgress),
		        FlowLayout.encloseRightBottom(statusContainer),FlowLayout.encloseCenter(selectedContainer)));

The `arcProgess` bit was stretching the overall container, so I did the following:

        arcProgress = new ArcProgress(){
                        @Override
                        protected Dimension calcPreferredSize()
                        {
                            return new Dimension(200, 200);
                        }
                    };

It might not work for you, and I chose to arbitrarily assign it a 200 pixels value because I couldn't rely on the layered container's dimensions (sometimes its preferred size is calculated at the time of the arcProgress' calcPreferredSize, sometimes it is after that

Just sharing in case it can help

**Closed** 2023-03-08 16:58 UTC
