### ISSUE TITLE
com.codename1.io.Socket.getHostOrIP()) returning wrong value

### ISSUE THREAD

**Issue by mab1423** [codenameone/CodenameOne#2155] opened 2017-07-09 13:04 UTC
I have tested this on Samsung SCH-1545 Running Android V 5.0.1
    deviceIP.setText(com.codename1.io.Socket.getHostOrIP());
Method is returning "localhost"
Should be returning the (192.168.1.114) IP address assigned to the wireless network.

**Comment by mab1423** [comment] 2017-07-12 13:09
Confirmed on Samsung SCH-1545 Running Android V 5.0.1
com.codename1.io.Socket.getHostOrIP() returns "localhost"
VS IOS returns the expected 192.168.1.112 address assigned VIA wifi 

Please advise

**Comment by codenameone** [comment] 2017-07-13 03:57
This was fixed in the commit above

**Comment by mab1423** [comment] 2017-07-13 11:54
As of this morning Jul 13th 750AM EST a new build on Android generates "localhost" 

Please Advise.

**Comment by codenameone** [comment] 2017-07-14 06:32
We update the build servers once a week on Fridays

**Comment by mab1423** [comment] 2017-07-14 19:58
Ok, Thanks, I will test this Saturday.

**Comment by mab1423** [comment] 2017-07-15 12:03
Saturday Jul 15th 800AM EST a new build on Android SCH-1545 Android V 5.0.1 generates "localhost"
Please advise.

**Comment by codenameone** [comment] 2017-07-16 06:55
Does it work for you on the simulator now?
I've tested the fix there and since the code is identical for this feature I'm not sure what could be the problem.

**Comment by mab1423** [comment] 2017-07-17 12:12
The simulator has been returning the USERDOMAIN name such as USERDOMAIN=MAB_WIN7-I7 for at least a month as I recall. The IOS phones return the xxx.xxx.xxx.xxx address
Only the Android SCH-1545 Android V 5.0.1
phone returns "localhost".

**Comment by codenameone** [comment] 2017-07-18 11:03
When I tested the simulator it didn't work for me and returned local host. It worked after this fix. I'll reopen it but this will take time as we'll need to test it on the device.

**Comment by mab1423** [comment] 2017-07-24 12:37
Can you advise an approximate date when this will be addressed?

**Comment by codenameone** [comment] 2017-07-25 05:40
No. 
Right now 3.8 is pretty full and relatively close (November) we don't have room for it there. Since this failed a few fix attempts and needs reproducing on the device it's non-trivial and we need time for it. It's scheduled for 3.9 at the moment which might take a while. We normally priorities things we hear a lot but this is something that was only raised by one person.

If you need it sooner here are your options:

- Fix it yourself and submit a pull request: https://www.codenameone.com/blog/how-to-use-the-codename-one-sources.html

- Use a different approach e.g. a native interface to implement this https://www.codenameone.com/how-do-i---access-native-device-functionality-invoke-native-interfaces.html

- We push forward issues raised by enterprise customers faster as they effectively fund the work in this project and subsidize the free/basic accounts so we put an extra effort

**Comment by mab1423** [comment] 2017-07-25 13:27
Fair enough.

Thanks.

Regards

[cid:image001.jpg@01D27C64.63ED8510]
Digital End to End, Shop Management Software Suite

Auto Shop Technologies, Corp.
Mark Bolduc: VP, Engineering & Product Development
138 Wells Village Road
Sandown, NH 03873-0091

Cell Number 603-327-8465
Email markb@autoshoptechnologies.com<mailto:markb@autoshoptechnologies.com>
Web: www.autoshoptechnologies.com<http://www.autoshoptechnologies.com>

**Comment by codenameone** [comment] 2018-02-05 13:25
I've looked again at the code and tested this on the device. It works for me and I can't see a situation where this will fail. Is this working for you now?

**Closed** 2018-02-07 09:07 UTC
