### ISSUE TITLE
Scrolling container locks into visible region at either end of container, with 2 quick scroll/drag gestures.

### ISSUE THREAD

**Issue by igo211** [codenameone/CodenameOne#1417] opened 2015-03-28 18:53 UTC
on iOS, two or more drag gestures in a scrolling container in rapid succession, performed at either end of the container, causes the container scrolling to be limited to visible region at that end.

This doesn't appear to be reproducible on Android.

To reproduce:
On iOS...

In a form with a scrolling container (test case uses an InfiniteContainer) that is larger than the screen, and with tensile drag set to true, scroll to the end of the container (doesn't matter which end).  

Once at the end, do 2 scroll/drag gestures in quick succession towards the same end of the container.
Then attempt to scroll in the opposite direction.

If you have done the previous 2 scroll/drag gestures quickly enough, the container will only scroll/show the already visible portion of the container and then quickly reset to the end of the container by itself.

I will send a link to the test case project via email.

**Comment by codenameone** [comment] 2015-03-29 11:58
The test case you sent is a scrollable that contains a huge container. You should have set the infinite container to the center area of a border layout and made it scrollable.

**Comment by igo211** [comment] 2015-03-29 16:27
Thanks for the tip, but the suggested change is irrelevant to the bug.
Change the layout as you suggested, and then follow the steps I had listed.
It may take you a few tries - the bug is very sensitive to gesture technique - be sure to do the double drag/scrolling gesture quickly at the top or bottom ( by *flicking* twice in quick succession, like an impatient teenager would ;-) ).

Please reopen.

**Comment by igo211** [comment] 2015-03-29 16:31
Not sure if you get notified, but I've updated the bug. 

Your suggestion doesn't change anything relevant to the bug. Please
re-open it. 

If you can't reproduce after making a serious attempt to do so, I'll be
happy to make a video of it and send it to you so that you understand
how to reproduce it. 

On 2015-03-29 04:58, codenameone wrote: 

> The test case you sent is a scrollable that contains a huge container. You should have set the infinite container to the center area of a border layout and made it scrollable. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/codenameone/CodenameOne/issues/1417#issuecomment-87403465

**Comment by codenameone** [comment] 2015-03-29 17:28
I didn't get a chance to dig into this but I'll retry with the relevant change.

**Comment by igo211** [comment] 2015-03-29 17:38
As suggested by Steve Hannah...
Gist to reproduce:  https://gist.github.com/igo211/c09b6d721ce70b8572ab

**Comment by codenameone** [comment] 2015-03-30 06:45
I cleaned up the gist a bit and was still able to reproduce it https://gist.github.com/5db41188891aa24cb556.git
Its odd since I can't reproduce it on the simulator even with the latest version of the code. Yet I was able to reproduce this both with the old and new VM.

**Comment by igo211** [comment] 2015-04-02 17:21
FYI, this has now been reproduced on Android (but still not on the simulator).

**Comment by codenameone** [comment] 2015-04-03 04:50
If it happens both on iOS and Android then Chen might have a better clue.

**Comment by igo211** [comment] 2015-04-05 18:24
Chen, any progress on this?  
We're about 1 day of coding away from re-submitting our app to the Apple review process and would like to know if this is likely to get fixed soon.  I'd prefer not to submit the app until this is fixed, but will roll the dice if you think this is going to take 8 days or longer (the current estimated apple review queue length).  thanks.

**Comment by chen-fishbein** [comment] 2015-04-06 08:32
yes, it's now fixed in the repository.
Thanks for the bug report

**Closed by chen-fishbein** 2015-04-06 08:32 UTC

**Comment by igo211** [comment] 2015-04-07 17:29
Thanks much Chen.

I'm guessing we have to wait for a new client library to be built and made available before we actually have access to the fix.  Any estimate on when that will happen (this is the only thing holding up our Apple app store submission at this point)?

**Comment by codenameone** [comment] 2015-04-07 19:10
We'll try to deploy tomorrow but its hard to guarantee since almost all of us are on the passover holiday right now.

**Comment by igo211** [comment] 2015-04-09 16:19
So, it appears this didn't happen yesterday.   
I'd like to know when this fix is going to be available.  
As stated 4 days ago, we're holding up our Apple app store submission for this fix (after holding up our Apple app store submission for about 6 other bugfixes since December).   As stated, we would have taken the chance of this last bug not being caught/experienced by Apple's review people if the bugfix availability was going to be more 8 days or more out.  So, we're now 1/2 way to that date, and still no answer, and no available bugfix.

**Comment by codenameone** [comment] 2015-04-09 16:57
We did an update yesterday morning (IL time). The fix should have been there.
If it still isn't working there was either a problem with the update process or the fix failed, I'm assuming the latter but Chen can probably verify this more easily than I can. He'll probably post an evaluation after the weekend.

**Comment by igo211** [comment] 2015-04-09 17:50
Arrgh... my apologies -
It appears the updated client libs update *did* come thru and somehow I missed seeing it when pressing the "Update Project libs" button in Eclipse yesterday.
As an aside - I'll file a separate enhancement request with a suggestion on how to alleviate this kind of situation (devs not knowing/noticing the client lib has updated), but you've got a pretty clear usability issue there with the "Update Project libs" button.

In any case, it appears the bugfix for this bug is in place and works.  
Thanks much!

**Comment by codenameone** [comment] 2015-04-10 04:47
The fix was entirely in the build server, you got a client update that's completely unrelated.
The fix was made for devices only.
Client library version is numbered in the codenameone_settings.properties file.
