### ISSUE TITLE
designer_1.jar build 20200410 breaks css compiler

### ISSUE THREAD

**Issue by rombosia** [codenameone/CodenameOne#3077] opened 2020-04-10 22:38 UTC
Tested platform: Win 10, JDK 1.8, Intellij 2019.3 with css activated.

Reproduction of Error: On update of CodenameOne plugin, executing 'Refresh cn1libs' to trigger compilation fails on ant target **cn1-compile-css** with the following error:

Target: -cn1-compile-css
JavaFX is loaded
Exception in thread "main" java.lang.NoClassDefFoundError: com/codename1/impl/javase/JavaSEPortWithSVGSupport
at com.codename1.designer.ResourceEditorApp.main(ResourceEditorApp.java:262)
Caused by: java.lang.ClassNotFoundException: com.codename1.impl.javase.JavaSEPortWithSVGSupport
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

**Comment by codenameone** [comment] 2020-04-11 03:38
Sorry about that. We pushed an update just now which should resolve this. Please open Codename One Settings and do an Update Project Libs to download the new update.

@shannah this seems to be a regression related to the new CI pipeline. It must be missing some dependencies in the packaging logic.

**Comment by rombosia** [comment] 2020-04-11 07:47
Perfect! The push has resolved this issue. 
Thank you.

**Comment by codenameone** [comment] 2020-04-11 07:54
There is still an issue to resolve, this is just a workaround

**Comment by rombosia** [comment] 2020-04-14 23:30
After this workaround, the css compiler's generated theme.res doesn't honour overrides.
**Example 1: TextField works, TextField.selected doesn't**
TextField{
border-bottom: 5px solid #8798A7;
}
TextField.selected{
border-bottom: 5px solid #16D173;

}

**Example 2: Button works, LinkButton doesn't**
Button{
color: white;
background-color: #16D173;
border-radius: 1mm;
}
LinkButton{
cn1-derive: Button;
border: none;
padding-left: 1mm;
color: #16D173;
background: transparent;
}

![2020_04_15_02_18_35_](https://user-images.githubusercontent.com/63478662/79283586-0079ed80-7ec1-11ea-8251-62821e6feaed.png)

**Comment by shannah** [comment] 2020-04-15 01:00
This is now fixed.  It will be included in the update on Friday.

**Closed** 2020-04-15 17:56 UTC
