### ISSUE TITLE
Bug: Some Material icons are not defined 

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#2857] opened 2019-06-26 17:26 UTC
Hi, 

some of the Material icons don't seem to have their codes added, I've found the following that I wanted to use: work_outline, work_off, notification_important, offline_bolt, check_circle_outline. 

But there may be more, I haven't done a systematic check. 

Would it be possible to add these?

**Comment by codenameone** [comment] 2019-07-03 08:07
Duplicate of #2421

**Closed by codenameone** 2019-07-03 08:07 UTC
Labels: duplicate
