### ISSUE TITLE
[Regression] Unit test  are not run (Netbean plugin 1.0.85)

### ISSUE THREAD

**Issue by heralight** [codenameone/CodenameOne#1443] opened 2015-04-11 16:22 UTC
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 1
Java: 1.7.0_76; Java HotSpot(TM) 64-Bit Server VM 24.76-b04
Runtime: Java(TM) SE Runtime Environment 1.7.0_76-b13
System: Linux version 3.13.0-49-generic running on amd64; UTF-8; fr_FR (nb)

OS: Ubuntu 14
Ant: 1.9.4

From Netbeans, with last plugin (1.0.85) (same on intellij) , no tests was found on new a new dummy project.
From command line, with last plugin, "ant test" no test was found and 
-do-test-run:
     [java] Preparing to execute 0 tests
     [java] All tests passed. Total 0 tests passed
     [java] org.apache.tools.ant.ExitException: Permission ("java.lang.RuntimePermission" "exitVM") was not granted.

On precedent netbeans plugin generated project, unit test was discovered, but from command line :
$ant test
.....

-do-test-run:
     [java] Preparing to execute 2 tests
     [java] java.lang.ClassNotFoundException: com.codename1.impl.javase.TestExecuter
     [java] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
     [java] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
     [java] 	at java.security.AccessController.doPrivileged(Native Method)
     [java] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
     [java] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
     [java] 	at java.lang.ClassLoader.findSystemClass(ClassLoader.java:1059)

Best regards,

Alexandre

**Comment by codenameone** [comment] 2015-04-12 07:59
I couldn't reproduce this issue.

**Comment by heralight** [comment] 2015-04-12 10:04
From a new clean install of last netbeans and last cn1 plugin on a fresh windows 7 x64.

Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 1
Java: 1.7.0_45; Java HotSpot(TM) 64-Bit Server VM 24.45-b08
Runtime: Java(TM) SE Runtime Environment 1.7.0_45-b18
System: Windows 7 version 6.1 running on amd64; Cp1252; fr_FR (nb)

![tubugunreco1](https://cloud.githubusercontent.com/assets/534840/7105168/8b7363d4-e10b-11e4-9985-aca46abbbe09.png)

You will see that fresh add unit test is not recognized by plugins in contextual menu (same after clean build)

![tubugunreco](https://cloud.githubusercontent.com/assets/534840/7105176/e326ed76-e10b-11e4-8c70-409ea32b388e.png)

On this screenshot, a manual call to ant test target will produce this bug (on right bottom, 2 unit test compiled, 0 passed) .

**Comment by codenameone** [comment] 2015-04-12 14:34
I just tried this with the latest plugin and my test executed. 
Make sure a file like this exists under the appropriate directory.
![screen shot 2015-04-12 at 5 32 06 pm](https://cloud.githubusercontent.com/assets/2353641/7105958/df28db34-e139-11e4-859d-f5c7c0963cf5.png)

Its a binary but should include the names of the test classes. Its generated by the prepareTests ant tag, can you point out why that isn't generated?

**Comment by heralight** [comment] 2015-04-12 17:06
A zip of dummy project with the problem can be downloaded here: http://dl.free.fr/ffY9S0Oi9
test.dat exists but have a size of 8octets instead of arround 50o with precedent plguin generation...

A more hot track, could be the compile target, nothing is done during -do-jar-copylibs.
With previous generated project we have at least something like this  [copylibs] Copy libraries to /tttt/dfdfdf/dist/lib.

 Previous generated project was not perfect, test ran from netbeans but not from command line (ref my first post).

**Comment by codenameone** [comment] 2015-04-16 11:24
Is it possible that one of the classes you have in the test package is abstract?

**Comment by sidiabale** [comment] 2015-04-16 14:26
No, I don't have an abstract class due to limitations that you explained [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/codenameone-discussions/awdH2WoY8Ts/TBmX_QtrlYQJ). However, I do have a concrete BaseTest class that derives from AbstractTest. All my tests derive from BaseTest.

PS: Has the limitation with abstract test classes been fixed yet as promised?

**Comment by codenameone** [comment] 2015-05-03 10:48
Thanks, this is fixed in our SVN and will be a part of the next update. It was because of the abstract fix.

**Closed by codenameone** 2015-05-03 10:48 UTC
