### ISSUE TITLE
Form max width (RFE or BUG report?)

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2628] opened 2018-11-28 01:30 UTC
I used the answer to this question to obtain a centered Form in the screen:
https://stackoverflow.com/questions/53489186/codename-one-app-shown-in-a-centered-rectangle-on-wide-screens

The problem is that this solution is not fully working on iPhone, there are issues with the Javascript port (executed on iOS Chrome, while with Android Chrome it's fine) and with the native iOS app (regarding the Toolbar title position after rotation).

My RFE is a Codename One API to get this feature in a fully supported way... or a test of my code to fix what it's wrong in the Codename One implementation. The problems are on iPhone only.

I spent a lot of hours to understand what's the main problem; maybe it's the orientationListener in the Javascript port on Chrome on iOS (while with Safari it works fine). Note that I tested the orientationListener in a barebones project and it works, the problem appears only when there is the centered Form.

In my code, the expected behaviour is to show a centered Form when the device is portrait, or another alert form when the device is landscape. The real crazy behavior is in this video (the strings are localized in Italian, but the code is the same):

https://www.informatica-libera.net/docLavoro/deviceRotation.mp4

```
 public void init(Object context) {
[...]
// force the screen orientation to portrait
        Display.getInstance().lockOrientation(true);
}
```

```
public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hi World"));
        FormUtilities.showCentered(hi);
    }
```

```
public class FormUtilities {

    /**
     * Shows the given Form centered in screen, giving it a maxium width equal
     * to maxWidth; it assumes that the device should be locked to portrait.
     * More info:
     * https://stackoverflow.com/questions/53489186/codename-one-app-shown-in-a-centered-rectangle-on-wide-screens
     *
     * @param form the Form to be shown
     * @param maxWidth in mm (if no value is provided, the default is 90mm)
     *
     */
    public static void showCentered(Form form, int... maxWidth) {
        int width = 90;
        if (maxWidth.length == 1) {
            width = maxWidth[0];
        }
        Form backgroundForm = new Form("", LayoutUtilities.getCenterOneComponentLayout(width));
        backgroundForm.getToolbar().hideToolbar();
        backgroundForm.add(form);

        Form alertForm = getOrientationAlertForm(backgroundForm);

        // workaround for javascript to force users to use portrait orientation
        if (Display.getInstance().isPortrait()) {
            backgroundForm.show();
        } else {
            alertForm.show();
        }

        // workaround for javascript to force users to use portrait orientation
        backgroundForm.addOrientationListener(l -> {
            if (!Display.getInstance().isPortrait()) {
                alertForm.show();
            }
        });

        Log.p("FormUtilities.showCentered executed with the given Form: " + form.getTitle(), Log.INFO);
    }

    /**
     * Alert Form to invite the user to rotate the device to portrait; it's
     * relevant only for javascript, because the screen rotation of Android and
     * iOS should be locked.
     *
     * @param portraitForm
     * @return
     */
    private static Form getOrientationAlertForm(Form portraitForm) {
        Form alertForm = new Form("", BorderLayout.center());
        alertForm.getToolbar().hideToolbar();
        alertForm.add(BorderLayout.CENTER, FlowLayout.encloseCenterMiddle(new SpanLabel("PleaseRotate")));
        alertForm.addOrientationListener(l -> {
            if (Display.getInstance().isPortrait()) {
                portraitForm.show();
            }
        });
        return alertForm;
    }
}
```

```
public class LayoutUtilities {

    /**
     * Returns a special layout that center a Component, giving it a fixed size.
     * More info:
     * https://stackoverflow.com/questions/53489186/codename-one-app-shown-in-a-centered-rectangle-on-wide-screens
     *
     * @param width in mm
     * @return
     */
    public static Layout getCenterOneComponentLayout(int width) {
        Log.p("LayoutUtilities.getCenterOneComponentLayout executing", Log.INFO);
        return new Layout() {
            @Override
            public void layoutContainer(Container parent) {
                // calculate the width to give to the Form
                int actualWidth = Display.getInstance().getDisplayWidth();
                int maxWidth = Display.getInstance().convertToPixels(width);
                if (actualWidth > maxWidth) {
                    actualWidth = maxWidth;
                }

                if (parent.getComponentCount() == 1) {
                    Component cmp = parent.getComponentAt(0);
                    cmp.setWidth(actualWidth);
                    cmp.setHeight(parent.getHeight());
                    cmp.setY(0);

                    // calculate the setX position
                    int xPosition = (parent.getWidth() - cmp.getWidth()) / 2;
                    if (xPosition < 0) {
                        xPosition = 0;
                    }
                    cmp.setX(xPosition);

                } else if (parent.getComponentCount() > 1) {
                    throw new IllegalArgumentException("CenterOneComponentLayout can be used with only zero or one Component inside a Container.");
                }
            }

            @Override
            public Dimension getPreferredSize(Container parent) {
                return new Dimension(100, 100);
            }
        };
    }
}
```

**Comment by shannah** [comment] 2019-01-04 20:43
This should also be fixed now (next update) as the described problem is a duplicate of #2636

**Closed by shannah** 2019-01-04 20:43 UTC
