### ISSUE TITLE
Codename Calendar API vs Java8SE Calendar API

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2256] opened 2017-10-28 12:46 UTC
Why the Codename Calendar API is missing of several things?
For example, in my app I need to know the day of the year: to calculate it, I had to implement an appropriate method using Calendar.MONTH and Calendar.DAY_OF_MONTH, because the Calendar.DAY_OF_YEAR constant is missing.

Please compare the two API, both referring to java.util.Calendar:
https://www.codenameone.com/javadoc/java/util/Calendar.html
https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.html

**Comment by codenameone** [comment] 2017-10-31 06:45
I suggest reading this https://www.codenameone.com/blog/why-we-dont-support-the-full-java-api.html

We have no goal of implementing the full API so this won't be done. Day of year is probably something we could implement but again the problem is doing it all over for an API that's on the way out. Calendar is replaced by the new date and time API so I think this issue is really a duplicate of #1763 which mentions the 310 project.

That project can be ported to a cn1lib which can probably be installed independently to get a portable clean date/time API https://github.com/ThreeTen/threetenbp/

**Closed by codenameone** 2017-10-31 06:45 UTC
