### ISSUE TITLE
Location simulation in simulator not working

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3619] opened 2022-08-23 13:04 UTC
the map does not refresh. I using plugin 7.0
![image](https://user-images.githubusercontent.com/16245755/186165133-d7424057-0829-4099-b4b6-34e532cf16a9.png)

**Comment by shai-almog** [comment] 2022-08-26 06:42
Duplicate of #3173

**Closed by shai-almog** 2022-08-26 06:42 UTC
Labels: duplicate
