### ISSUE TITLE
Opening theme Designer makes all rounded rectangle borders as squares

### ISSUE THREAD

**Issue by Peterko1234** [codenameone/CodenameOne#3003] opened 2020-01-21 16:10 UTC
I have set rounded rectangle borders with radius 2 mm to many styles in Designer. I saved it. Then I closed Designer. I've builded app and tested it on both iOS/Android and components got rounded borders. Then I opened Designer and all rectangle borders have changed to squares (no longer rounded). The thing is that when I open border settings dialog, all those settings (radius 2mm, etc.) remained the same. Then I close the border setting dialog and that style has rounded border once again (its shown in Preview).  Issue seems to happen on opening theme.res - Designer.

**Comment by shannah** [comment] 2020-01-21 16:20
I think this is a duplicate of https://github.com/codenameone/CodenameOne/issues/2993
But the fix should already have made it into the library.  Try updating your libs and see if it fixes it.

**Closed** 2020-01-23 14:03 UTC
Labels: duplicate
