### ISSUE TITLE
Scrolling issue in iOS / Android when virtual keyboard is on

### ISSUE THREAD

**Issue by akash-more4apps** [codenameone/CodenameOne#1601] opened 2015-11-09 03:25 UTC
(Original thread : https://groups.google.com/forum/#!topic/codenameone-discussions/mvXyEyq00ZI )

Hi,
after testing it several times, I come across the fact that,
- if Scrollable Y is true then:
    It works in Android but will NOT work in iPhone
- if Scrollable Y is false then:
    It works in iPhone but NO more working (scrolling) in Android

And I crosscheck with demo app and its reproducing the same situation...
Here is the link of that demo project having TextFieldTestIniOS form containing bunch of Textfields to test this.
Link: https://www.dropbox.com/s/8way4frjsahqxbu/TestProject.zip?dl=0

If you change the Scrollable Y property of 'Container2' then you will notice this in real iOS / Android device

Thanks.

**Comment by shannah** [comment] 2015-11-13 21:43
Not sure if this is related, but in trying to reproduce this problem on iOS, I'm getting a NPE

~~~~
java.lang.NullPointerException
    at com_codename1_ui_TextArea.getLines:731
    at com_codename1_ui_TextArea.getActualRows:675
    at com_codename1_ui_plaf_DefaultLookAndFeel.getTextAreaSize:891
    at com_codename1_ui_plaf_DefaultLookAndFeel.getTextFieldPreferredSize:1500
    at com_codename1_ui_TextField.calcPreferredSize:1505
    at com_codename1_ui_Component.preferredSizeImpl:1914
    at com_codename1_ui_Component.preferredSize:1949
    at com_codename1_ui_Component.getPreferredSize:741
    at com_codename1_ui_Component.getPreferredW:821
    at com_codename1_ui_layouts_BoxLayout.getPreferredSize:177
    at com_codename1_ui_Container.calcPreferredSize:1566
    at com_codename1_ui_Component.preferredSizeImpl:1914
    at com_codename1_ui_Component.preferredSize:1949
    at com_codename1_ui_Component.getPreferredSize:741
    at com_codename1_ui_Component.getPreferredH:831
    at com_codename1_ui_layouts_BoxLayout.getPreferredSize:175
    at com_codename1_ui_Container.calcPreferredSize:1566
    at com_codename1_ui_Component.calcScrollSize:771
    at com_codename1_ui_Component.getScrollDimension:758
    at com_codename1_ui_Container.isScrollableY:1646
    at com_codename1_ui_Component.paintComponent:1455
    at com_codename1_ui_Component.paintComponent:1428
    at com_codename1_impl_CodenameOneImplementation.paintDirty:502
    at com_codename1_ui_Display.edtLoopImpl:1070
    at com_codename1_ui_Display.mainEDTLoop:994
    at com_codename1_ui_RunnableWrapper.run:120
    at com_codename1_impl_CodenameOneThread.run:176
    at java_lang_Thread.runImpl:153
~~~~

So it looks like there is a race condition in dealing with the `rowStrings` property of TextArea.

In trying to track that down, I noticed this:

~~~~
if(!Display.getInstance().isEdt()) {
            if(rowStrings == null) {
                rowStrings = new ArrayList();
                rowStrings.add(getText());
                return;
            }
        }
~~~~

https://github.com/codenameone/CodenameOne/blob/master/CodenameOne/src/com/codename1/ui/TextArea.java#L789-L794

@codenameone Under what circumstances would this be called off the EDT?

**Comment by shannah** [comment] 2015-11-13 22:00
Used a break point to find where it is called off the EDT.  Looks like that was a bug... a revalidate() cycle called off the EDT when the keyboard is being shown in some situations.  This may have been a cause of numerous quirks.

I was never able to reproduce the lock-ups shown in the video for this issue.  Testing with iOS 8.2 simulator and iOS 9 on iPhone 4S device.  However, I suspect this fix might also fix that problem.  Should be available on the build server soon.  

Closing for now.  Please reopen this issue if the problem persists after trying this fix.

**Closed by shannah** 2015-11-13 22:00 UTC
