### ISSUE TITLE
iOS: Local notifications not working (localNotificationReceived() is not called after tapping the local notification in the OS)

### ISSUE THREAD

**Issue by ThomasH99** [codenameone/CodenameOne#3734] opened 2023-09-15 17:13 UTC
**Describe the bug**
Since some time the local notifications are no longer working. When I click them in the OS, the localNotificationReceived() is not called. At first I thought it was my code, but after weeks of testing, I found the below in the native logs on my iOS device (iPhone 10Xr, latest OS version):

Warning: UNUserNotificationCenter delegate received call to -userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: but the completion handler was never called.

I was then adviced by your support to set the  ios.includePush=true (I don't use push and never has). 

After building with that I get the below native log (and the log above is gone): 

2023-09-14 14:32:55.530 MyApp[16954:2778359] Handle push from background or closed
2023-09-14 14:32:55.530 MyApp[16954:2778359] {
"__ios_id__" = "7fs7yuh0-[MyID]";
}

After that log entry I see that the app starts, but localNotificationReceived() is never called (I don't see the log trace I put in it). 

**To Reproduce**
Build an iOS app with main class implementing LocalNotificationCallback.localNotificationReceived(String var1). Activate a local notification, put the app in background (or kill it), click the local OS notifications when it appears (or later). App starts up, but localNotificationReceived() is not called.

**Comment by shannah** [comment] 2023-09-16 13:25
I was able to reproduce (and fix) the warning about `Warning: UNUserNotificationCenter delegate received call to -userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: but the completion handler was never called.`

However, I was not able to reproduce local notifications not working.  All of my examples worked fine, despite the warning.  Running on iOS 16.3, iPhone 8.

It is possible that iOS starts "revoking" your local notification privileges after this warning is triggered too many times.  It is also possible that there is another reason why it isn't delivering your local notifications.

This fix will be part of next week's release.

**Closed by shannah** 2023-09-16 13:25 UTC

**Comment by ThomasH99** [comment] 2023-09-16 14:50
Thanks Steve. It may be possible that the privileges have been revoked at some point. I believe some time back I had a bug that meant the onComplete would not be called on every call. I will wait for the update and see if it resolves the issue and if not, try to reset the revocation (I guess by completely uninstalling the app and re-installing it instead of the usual update). I googled and found a somewhat similar issue saying that the device needed to be rebooted after an OS update, so I'll try that as well.

**Comment by ThomasH99** [comment] 2023-09-16 14:54
Since I've now set ios.includePush=true, could you let me know if I should set it back to false again (just to ensure that is not impacting anything)?

**Comment by shannah** [comment] 2023-09-16 14:56
Might as well set it back to false.  If you're not using push I don't think it can help anything to keep it turned on.
