### ISSUE TITLE
graphics synchronization failure

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#1660] opened 2016-01-30 08:38 UTC
See https://groups.google.com/forum/#!topic/codenameone-discussions/QDFy4jO_4zQ
The upshot is that painting from images is not properly syncronized.  In the code below,
which is a simplified representation of my normal paint loop, a full screen buffer is sent
out to the screen by "paint", and then at some time later, the buffer image is rewritten
in preparation for the next frame.  The exact timing is not important.  The same glitchy
behavior will occur with very low frame rates.  The only requirement is that the buffer
image reuse starts sometime shortly after the paint operation.

````java
package com.mycompany.myapp;

import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Display;
import com.codename1.ui.FontImage;
import com.codename1.ui.Form;
import com.codename1.ui.Graphics;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.animations.CommonTransitions;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.geom.Dimension;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.layouts.LayeredLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.util.UITimer;

import java.io.IOException;

class DisplayComponent extends Component
{	public Image fixed = null;
	public Image front = null;
	public void fillFixed()
	{	int w = getWidth();
		int h = getHeight();
		Graphics g = fixed.getGraphics();
		g.setColor(0xd0d0d0);
		g.fillRect(0,0,w,h);
	}
	int frame = 0;
	public Dimension getPreferredSize() 
	{ Container parent = getParent();
	  return(new Dimension(parent.getWidth(),parent.getHeight()));
	}
	public void fillFront()
	{	int w = getWidth();
		int h = getHeight();
		frame++;
		Graphics g = front.getGraphics();
		g.drawImage(fixed,0,0);
		g.setColor(0);
		g.fillRect(w/3,0,w/4,h);
		g.setColor(0xff);
		g.drawLine(0,0,w,h);
		g.setColor(0xff00);
		g.drawString("Frame "+frame,w/2,h/2);
	}
	public void paint(Graphics g)
	{	int w = getWidth();
		int h = getHeight();
		if(fixed==null) { fixed = Image.createImage(w,h); fillFixed(); }
		if(front==null) { front = Image.createImage(w,h); fillFront(); }
		if(front!=null)
		{
		g.drawImage(front,0,0);
		// prepare the next frame
		fillFront();
		repaint();
		}
	}
	
}

public class MyApplication {

	private Form current;
	private Resources theme;
	private DisplayComponent display = null;
	public void init(Object context) {
		theme = UIManager.initFirstTheme("/theme");

		// Pro only feature, uncomment if you have a pro subscription
		// Log.bindCrashProtection(true);
	}

	public void start() {
		if (current != null) {
			current.show();
			return;
		}
		Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));
		
		display = new DisplayComponent();
		display.setVisible(true);
		hi.add("Center",display);

		hi.show();
	}

	public void stop() {
		current = Display.getInstance().getCurrent();
	}

	public void destroy() {
	}

}
````

**Comment by codenameone** [comment] 2016-03-14 04:32
Issue is applicable to Android

**Comment by shannah** [comment] 2016-04-05 15:24
This might be fixed with the shape clip enhancements.  Assigning to myself to test.

**Comment by shannah** [comment] 2016-07-22 22:55
Looking at this issue more closely, I don't think this issue can be fixed without major performance trade-offs.  The graphics pipelines are asynchronous so a call to g.drawImage(img) will result in the image being drawn sometime later.    Painting onto an image currently is synchronous.  The problem is that you're passing an image to the async pipeline to draw - then you're immediately changing that image. When the pipeline gets around to rendering the image, it may be working with it in an inconsistent state.

If we were to, instead of passing a reference of the image, pass a copy of the image then we would incur an expensive copy.  

@codenameone What do you think?

**Comment by ddyer0** [comment] 2016-07-22 23:13
This is about what I expected.   

The first thing, is if you can determine if the image is cleared for re-use either by polling
or by setting up a callback of some kind.   At present, I'm papering over this problem by
imposing a heuristically determined delay, which is clearly unsatisfactory.  Once the information
is available, various options how to use it could be discussed.

**Comment by codenameone** [comment] 2016-07-23 04:13
This isn't something we should address. Callbacks aren't practical here as they occur deep within the rendering native pipeline in the native thread and doing something like that will be useless. By the time you get the message the image would already be in the next drawing cycle causing the exact same problem to re-appear. 

If you don't care at all about performance (which I've indicated in the past that you won't get with mutable images) just use an intermediate buffer or flip between images.

**Closed by codenameone** 2016-07-23 04:13 UTC

**Comment by ddyer0** [comment] 2016-07-23 17:25
I do use an intermediate buffer, but you still need to know when the alternate buffer is
free to be rewritten.  At any given time, buffer A is owned by the device display and buffer B
is being written with the next frame.  Once buffer B is ready, flip the buffers so that next time
a paint occurs, buffer B will be taken by the device, but you still have to know when it is
safe to start rewriting buffer A.

**Comment by Maaartinus** [comment] 2019-12-13 04:21
@ddyer0 Could you solve it somehow? A "heuristically determined delay" sounds too bad, but what about using three buffers? When you give B to the graphics engine, it may be still using A, so you let it play with both and paint to C. When you're done with painting C, it must have switched to B (otherwise, B wouldn't be displayed at all), so you give it C and start painting to A. Just a theory... haven't tried it yet.

**Comment by ddyer0** [comment] 2019-12-13 04:34
I've ended up with a fairly complex scheme, where after I prepare an offscreen image, I let it "age" for a certain time before allowing it to be displayed.  If a request do paint it to the real screen arrives during the embargo period, it is ignored and rescheduled.
