### ISSUE TITLE
New warning api target 34 in Android to 31 August 2024

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3820] opened 2024-07-09 18:01 UTC
Update your target API level by August 31, 2024 to be able to release updates to your app
Global Multi-Assistance
Global Multi-Assistance
Jul 4, 2024 10:08
We detected that your app targets an older version of Android. For users to have a safe experience, Google Play requires that all apps meet target API level requirements.

Starting August 31, 2024, the target API level must be 1 year or younger than the most recent version of Android; Otherwise, you will not be able to update the app.

You must implemented this issue???

![image](https://github.com/codenameone/CodenameOne/assets/16245755/06b98d38-6647-415c-aa0e-78f058399b61)

When I increase the target this error occurr in you build server

**Comment by shai-almog** [comment] 2024-07-10 02:17
We will migrate to API 34 before August 31st so this should be mostly seamless.

**Comment by shai-almog** [comment] 2024-07-11 02:34
Servers now include support for API level 34, 35. However, this is untested and the builds themselves are unsupported/might crash. Feel free to report related errors here.

**Comment by shai-almog** [comment] 2024-07-12 02:48
Can't read Portuguese but that's generally the point of not switching this to the default right now... We need to update implementations to work with the various things Google broke in newer API levels.

**Comment by carlosverdier** [comment] 2024-07-26 08:00
I built my app for api level 34 successfully, but my phone refuse to install it. It says couldn't analyse the package, then does nothing.

**Comment by shai-almog** [comment] 2024-07-30 13:35
@shannah is this something you can reproduce?

**Comment by shannah** [comment] 2024-08-03 13:32
I have not been able to reproduce this in my tests.  @carlosverdier Can you share the APK?

**Comment by carlosverdier** [comment] 2024-08-08 11:00
Sure, you can find it here:

`https://downloads.yourappeasy.com/Hijos-release.apk`

**Comment by shannah** [comment] 2024-08-09 15:59
App installed and launched OK for me on Android Simulator running API 34.

![image](https://github.com/user-attachments/assets/45cfcb2d-c5cd-4bf7-a1f8-3c079b28c933)

Can you provide details on the device that you tried to install on?

**Comment by carlosverdier** [comment] 2024-08-11 16:37
I tried on two different devices with same results. It refuses to install due to could not analyse the package:

Samsung Galaxy A71 Android 13
Huawei Redmi Note 9S Android 12

The moment I remove the build hint to force api 34, it goes well.

Could you try on an actual device?

**Comment by shannah** [comment] 2024-08-18 15:09
Tested your APK on Samsung Galaxy S8 running Android 9.  Installed and launched OK.

Then tested on UMIDGI A3X running Android 10.  Also installed and launched OK.

**Comment by shannah** [comment] 2024-08-18 15:13
@carlosverdier I may have to debug this issue through you, since it doesn't reproduce on any of my devices, nor in the Android emulator.

Can you connect your device to your computer and view the logcat messages when you try to install it to see if it provides anything useful?

**Comment by carlosverdier** [comment] 2024-08-19 10:33
Sorry, but I am not sure if I uploaded the right version. Could you please try to download again?

https://downloads.yourappeasy.com/Hijos-release.apk

Also, this is the build hist I am using:

android.min_sdk_version=34

**Comment by NicoHubert197** [comment] 2024-08-19 14:02
Hello, 

As I said here, https://github.com/codenameone/CodenameOne/issues/3829, there is an issue when I try to build my apk on server on android 34 but not on android 33

Best regards

**Comment by DurankGts** [comment] 2024-08-19 15:09
Do you add this codename1.arg.android.targetSDKVersion=34 ??? this work in my case....

@carlosverdier use this android.min_sdk_version=34 limit your app to just install in android 14 and not in oldest version 33,32... etc

**Comment by carlosverdier** [comment] 2024-08-20 09:37
@DurankGts Thanks, it works with that hint. I'll try now on Google Play and see if the warning disappears.

@shannah Sorry about the confusion

**Comment by DurankGts** [comment] 2024-08-23 12:46
> @DurankGts I added this hint codename1.arg.android.buildToolsVersion=34, should I replace it by targetSDKVersion

not you must to use codename1.arg.android.targetSDKVersion=34, delete codename1.arg.android.buildToolsVersion=34 because the buiild server required that you delete when compile.

**Comment by shai-almog** [comment] 2024-08-25 02:22
This should be resolved by the latest update to the build servers.

**Closed by shai-almog** 2024-08-25 02:22 UTC

**Comment by JTBrandao** [comment] 2024-09-30 20:51
We generated a build using build hint "codename1.arg.android.targetSDKVersion=34" . Compiled with cn1 plugin maven version 7.0.145 (this is the correct plugin version ?). But the message on Google Play console remains (the APP must segment Android 14 (API 34 level or more recent).
