### ISSUE TITLE
MULTIANEWARRAY build error when ios.newVM=true

### ISSUE THREAD

**Issue by BrianSchultheiss** [codenameone/CodenameOne#1426] opened 2015-04-03 02:08 UTC
Build Target: IOS Debug Build

=============================================================
Issue: when using 'ios.newVM=true', I get the build error below. However when using 'ios.newVM=false', it builds without error.
=============================================================

=============================================================
Simplest Test Java Case:
=============================================================
package com.airegear.glodebug;

import java.io.IOException;

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

public class GLO_DEBUG {

	private Form	current;

	public void destroy() {
	}

	public void init(Object context) {
		/*TEST CASE*/
		Foo[][] gridFoo = new Foo[5][5];
		for (int x = 0, xsize = gridFoo.length; x < xsize; x++) {
			Foo[] rowFoo = gridFoo[x];
		}

		try {
			Resources theme = Resources.openLayered("/theme");
			UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
		} catch (IOException e) {
			e.printStackTrace();
		}

	}

	public void start() {
		if (current != null) {
			current.show();
			return;
		}
		Form hi = new Form("Hi World");
		hi.addComponent(new Label("Hi World"));
		hi.show();
	}

	public void stop() {
		current = Display.getInstance().getCurrent();
	}

	public static class Foo {
		public String	bar;
	}

}

=============================================================
Build Error is:
=============================================================

CompileC build/GLO_DEBUG.build/Release-iphoneos/GLO_DEBUG.build/Objects-normal/armv7/com_airegear_glodebug_GLO_DEBUG.o GLO_DEBUG-src/com_airegear_glodebug_GLO_DEBUG.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode6.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    /Applications/Xcode6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wno-int-conversion -Wbool-conversion -Wno-enum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DNS_BLOCK_ASSERTIONS=1 -isysroot /Applications/Xcode6.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -miphoneos-version-min=6.0 -iquote /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/build/GLO_DEBUG.build/Release-iphoneos/GLO_DEBUG.build/GLO_DEBUG-generated-files.hmap -I/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/build/GLO_DEBUG.build/Release-iphoneos/GLO_DEBUG.build/GLO_DEBUG-own-target-headers.hmap -I/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/build/GLO_DEBUG.build/Release-iphoneos/GLO_DEBUG.build/GLO_DEBUG-all-target-headers.hmap -iquote /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/build/GLO_DEBUG.build/Release-iphoneos/GLO_DEBUG.build/GLO_DEBUG-project-headers.hmap -I/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/build/Release-iphoneos/include -I/Applications/Xcode6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/build/GLO_DEBUG.build/Release-iphoneos/GLO_DEBUG.build/DerivedSources/armv7 -I/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/build/GLO_DEBUG.build/Release-iphoneos/GLO_DEBUG.build/DerivedSources -F/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/build/Release-iphoneos -include /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/C/com.apple.DeveloperTools/6.0.1-6A317/Xcode/SharedPrecompiledHeaders/GLO_DEBUG-Prefix-bskcoktdzfiwhddxxmnxpnlbihjl/GLO_DEBUG-Prefix.pch -MMD -MT dependencies -MF /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/build/GLO_DEBUG.build/Release-iphoneos/GLO_DEBUG.build/Objects-normal/armv7/com_airegear_glodebug_GLO_DEBUG.d --serialize-diagnostics /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/build/GLO_DEBUG.build/Release-iphoneos/GLO_DEBUG.build/Objects-normal/armv7/com_airegear_glodebug_GLO_DEBUG.dia -c /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/GLO_DEBUG-src/com_airegear_glodebug_GLO_DEBUG.m -o /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/build/GLO_DEBUG.build/Release-iphoneos/GLO_DEBUG.build/Objects-normal/armv7/com_airegear_glodebug_GLO_DEBUG.o
/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/GLO_DEBUG-src/com_airegear_glodebug_GLO_DEBUG.m:63:171: error: use of undeclared identifier 'class_array1__com_airegear_glodebug_GLO_DEBUG_Foo'; did you mean 'class_array2__com_airegear_glodebug_GLO_DEBUG_Foo'?
    PUSH_OBJ(alloc2DArray(threadStateData, (*pop(stack, &stackPointer)).data.i, (*pop(stack, &stackPointer)).data.i, &class_array2__com_airegear_glodebug_GLO_DEBUG_Foo, &class_array1__com_airegear_glodebug_GLO_DEBUG_Foo, sizeof(JAVA_OBJECT))); /* MULTIANEWARRAY */
                                                                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                                                                          class_array2__com_airegear_glodebug_GLO_DEBUG_Foo
In file included from /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/GLO_DEBUG-src/com_airegear_glodebug_GLO_DEBUG.m:1:
In file included from /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/GLO_DEBUG-src/GLO_DEBUG-Prefix.pch:18:
/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/GLO_DEBUG-src/cn1_globals.h:402:46: note: expanded from macro 'PUSH_OBJ'
#define PUSH_OBJ(value)  { JAVA_OBJECT ppX = value; stack[stackPointer].type = CN1_TYPE_INVALID; \
                                             ^
In file included from /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/GLO_DEBUG-src/com_airegear_glodebug_GLO_DEBUG.m:1:
In file included from /var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/GLO_DEBUG-src/com_airegear_glodebug_GLO_DEBUG.h:6:
/var/folders/p_/xlvwhg4101z8r81_nl13cds80000gn/T/build6189407152682086618xxx/dist/GLO_DEBUG-src/com_airegear_glodebug_GLO_DEBUG_Foo.h:8:21: note: 'class_array2__com_airegear_glodebug_GLO_DEBUG_Foo' declared here
extern struct clazz class_array2__com_airegear_glodebug_GLO_DEBUG_Foo;
                    ^
1 error generated.

**Comment by codenameone** [comment] 2015-04-03 10:25
Thanks, this was fixed in the repository and should be in the build servers after the weekend.
The issue is triggered by the optimizer that stripped out the 1d array when only a 2d array is used.
You can workaround it by just referencing a Foo[] which will prevent the optimizer from stripping it out.

**Closed by codenameone** 2015-04-03 10:25 UTC
Labels: Priority-Critical
