### ISSUE TITLE
desktop.skin doesn't load anymore the default iOS7 theme

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2526] opened 2018-08-21 08:43 UTC
At the moment, I'm not using the Codename One sources. I'm using the last Codename One plugin with the last updated Codename One project libs on Netbeans 9.0 with Java 10.0.2. I'm using Linux.

The problem is that the `desktop.skin` doesn't load anymore the default iOS7 theme (it worked correctly after I had just installed the Codename One plugin few days ago, then it suddenly stopped to load any default theme). This incorrect behavior happened some day ago, but I thought that was a problem of my installation.

I've just tried to remove the Codename One plugin and to delete its hidden folders in the home directory. I also replaced the `theme.res` files with an empty `theme.res` and I removed the checksums of the CSS to force compile to regenerate the `theme.res`. But nothing is changed, the `desktop.skin` doesn't load the iOS7 theme as default.

This is how the "Hello world" (Bare Bones) default project with native theme appears in my computer:
![desktopskin](https://user-images.githubusercontent.com/1997316/44390863-9f084c80-a52e-11e8-972f-972fc90558ab.png)

**Comment by codenameone** [comment] 2018-08-21 19:13
Is it possible you picked UWP desktop skin by mistake?

**Comment by codenameone** [comment] 2018-08-21 19:26
@shannah This might be a JDK 10 issue. I can't reproduce it in 8.

**Comment by shannah** [comment] 2018-08-23 13:03
I just tried this out on linux with the latest plugin and confirmed the same thing.  It looks like the latest plugin doesn't include the latest changes in git.  The problem here is that the designer included with the plugin doesn't include the JAXB dependency that is necessary on JDK9/10/11.  This was fixed in https://github.com/codenameone/CodenameOne/commit/4a504e464eeefed1fc9126cba85a906331150c9c#diff-abc034abd992734fbb0ec61d289f63a6  on July 13th. 

@codenameone Should that fix be included with the latest plugin?

**Comment by codenameone** [comment] 2018-08-23 14:08
@shannah why would a change to the designer be relevant to the desktop skin?

**Comment by shannah** [comment] 2018-08-23 14:11
The designer is used when a new project is created by the Netbeans plugin.  Among other things, it copies the theme.res from the project template into the new project.  It requires JAXB for this step.    If you create a new project on OpenJDK 10, it will look like the project is created successfully, but if you look more closely, you see that the project doesn't have a theme.res file.

@jsfan3 Can you confirm whether the project has a theme.res file?

**Comment by codenameone** [comment] 2018-08-23 14:17
If I understood correctly he tried to place an empty theme file and got that result too. I think the problem is that I just didn't push an update for the designer, this can be fixed easily.

**Comment by shannah** [comment] 2018-08-23 14:27
>  Like @codenameone said, I tried to place an empty theme file and got that result too.

I can't reproduce that, then.  On Ubuntu with OpenJDK 10, and a fresh project, if I copy a theme.res file into the src directory, it runs fine in the simulator with the desktop skin.

**Comment by jsfan3** [comment] 2018-08-23 14:44
@shannan I zipped a new Codename One empty project (bare bones, native theme) as generated in Linux by Netbeans 9 + Oracle JDK10 (not OpenJDK). Can you please try if it's identical to your project? I mean a check of the libraries and of the theme.res (that I didn't manually copied in this zip, it's the one generated automatically):
 
[EmptyProject.zip](https://github.com/codenameone/CodenameOne/files/2314934/EmptyProject.zip)

**Comment by shannan** [comment] 2018-08-23 14:45
@jsfan3 you are tagging the wrong person. You want to tag @shannah

**Comment by jsfan3** [comment] 2018-08-23 14:49
Oh, I'm sorry... you're right... I confused the last char of the nickname ;-)

**Comment by shannah** [comment] 2018-08-23 15:37
That project works fine for me.  Netbeans 9.  OpenJDk 10.0.2.  Fresh plugin install.  Fresh .codenameone directory.  Deleted cn1-related java preferences -- so fresh state.

**Comment by shannah** [comment] 2018-08-23 15:39
Wait... I've reproduced it by switching to the UWP desktop skin, then switching back to Desktop skin.  It still uses the UWP desktop skin.

**Comment by shannah** [comment] 2018-08-23 15:46
Fixed.  Will be included in next update.

**Comment by jsfan3** [comment] 2018-08-23 15:49
Thank you! :-)

**Comment by jsfan3** [comment] 2018-08-24 22:03
Is the update for this fix released? Today I tried again with an empty project and there is the same issue (no default theme loading).

**Comment by jsfan3** [comment] 2018-08-25 08:28
Steps to reproduce:

1. I do an update project libs again, from one of my projects.
2. I created a new Codename One project (bare bones, native theme).
3. This is the created project: [TestNativeTheme.zip](https://github.com/codenameone/CodenameOne/files/2320450/TestNativeTheme.zip)
4. In the /src folder there is a "theme.res" of 49byte
5. I compile the project
6. On the first run the result is fine: 
![run1](https://user-images.githubusercontent.com/1997316/44616487-2ae0e800-a851-11e8-9556-030fbdae6ae2.png)
7. I change the skin from desktop to iPhoneX, then to UWP desktop, then to desktop again. Now the result is bad: 
![run2](https://user-images.githubusercontent.com/1997316/44616490-39c79a80-a851-11e8-89b7-3d2f2ceff0d3.png)
8. Starting from now, there is no way to have the default iOS7 theme like in the step 6.

**Comment by codenameone** [comment] 2018-08-25 09:00
After creating the project you need to update the client libs again. That operation does two things:

- Fetches global updates (e.g. designer, gui builder/settings etc.)
- Updates this specific project

Currently projects are always created with the libraries from the plugin (we should probably change that) so the update after the creation will deliver the fix from @shannah

**Closed by codenameone** 2018-08-25 09:00 UTC

**Comment by jsfan3** [comment] 2018-08-25 09:06
Thank you, it solved :)
