### ISSUE TITLE
Map issue with back and onTop side menu

### ISSUE THREAD

**Issue by bbeckk** [codenameone/CodenameOne#2306] opened 2018-01-13 20:00 UTC
There's a problem in map Component with back and onTop side menu. If the back btn is clicked, the map component disappears and back functionality doesnt work unless the screen or back btn is clicked again. 

Likewise when the command in ontop side menu is clicked, the same problem exists as in back. 

P.S keep the map key in the build hint. I've removed it since mine is in production. 

Stackoverflow q: https://stackoverflow.com/questions/48144094/map-infinite-progress-of-connectionrequest-issue

Please have a look at the video here:  https://youtu.be/UCwkaKuP2tI

Here is the test case:  https://drive.google.com/file/d/1yrFqlBRBxV_WfnMge_rBeVgT4vh1yO0F/view?usp=sharing

Here is the apk with the problem:  https://drive.google.com/file/d/1aXT8fi4ca4_N1J3rCYbDrmHKMc3wRoIj/view?usp=sharing

Code Snippet: 

MyApplication class

`public void start() {
        if(current != null){
            current.show();
            return;
        }
        new Home(theme).show();
    }`

Home.class 

~~~~
import com.codename1.googlemaps.MapContainer;
import com.codename1.maps.Coord;
import com.codename1.ui.Command;
import com.codename1.ui.EncodedImage;
import com.codename1.ui.FontImage;
import com.codename1.ui.Form;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

public class Home extends Form {

    MapContainer cnt = null;

    public Home(Resources res) {
        super(new BorderLayout());
        Command back = new Command("Back") {
            public void actionPerformed(ActionEvent ev) {
                new SomeForm(res).show();
            }
        };
        setBackCommand(back); // back command

        Command home = new Command("Home") {//on top side menu starts

            @Override
            public void actionPerformed(ActionEvent evt) {
                new Home(res).show();
            }
        };
        getToolbar().addCommandToSideMenu(home);

        Command sales = new Command("Sales Entry") {

            @Override
            public void actionPerformed(ActionEvent evt) {
                new SomeForm(res).show();
            }
        };
        getToolbar().addCommandToSideMenu(sales); //on top side menu ends

        Style s = UIManager.getInstance().getComponentStyle("Label");


        //map component
        cnt = new MapContainer();
//      cnt = new MapContainer("keep ur map key here");

        s.setFgColor(0x0000ff);
        s.setBgTransparency(0);
        FontImage markerImg = FontImage.createMaterial(FontImage.MATERIAL_PLACE, s, 4);


        cnt.setCameraPosition(new Coord(40.6976701, -74.259875));
        cnt.addMarker(
                EncodedImage.createFromImage(markerImg, false),
                new Coord(40.6976701, -74.259875),
                "marker",
                "Optional long description",
                evt -> {
                    
                }
        );
        cnt.zoom(new Coord(40.6976701, -74.259875), 15);
        add(BorderLayout.CENTER, cnt);
        
        revalidate();
    }
}
~~~~

SomeForm class

````
import com.codename1.ui.Command;
import com.codename1.ui.Form;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.util.Resources;

public class SomeForm extends Form{
    
    public SomeForm(Resources res){
        setTitle("Some Form");
        Command back = new Command("Back") {
            public void actionPerformed(ActionEvent ev) {
                new Home(res).show();
            }
        };
        setBackCommand(back);
        Command home = new Command("Home") {//on top side menu starts

            @Override
            public void actionPerformed(ActionEvent evt) {
                new Home(res).show();
            }
        };
        getToolbar().addCommandToSideMenu(home);

        Command sales = new Command("Sales Entry") {

            @Override
            public void actionPerformed(ActionEvent evt) {
                new SomeForm(res).show();
            }
        };
        getToolbar().addCommandToSideMenu(sales); //on top side menu ends
    }
}
  
````

**Comment by codenameone** [comment] 2018-01-14 05:07
Can you just extract the main class's java source snippet that deals with the map and paste it here?

That way search and historic issue inspection will work. It will also make it easier for us to reproduce this properly.

**Comment by bbeckk** [comment] 2018-01-15 10:59
Sure... I've included main class source snippet above... Moreover I've given a link to the entire project file (test project) as well above (in case you need it). thankyou

**Comment by shannah** [comment] 2018-01-19 15:05
I can't really tell from the Video what the problem is.  The test case you provided isn't self contained, so I need to create my own stubs for portions of it - and since I already have test cases with maps that include on top side menu that seem to work fine, it is possible that the portions that I fill in here will prevent the problem from occurring.

Please post a self-contained test case.  Same format you're using right now (just main class) - but it should be self contained so I can just paste it into my project and build.

**Comment by codenameone** [comment] 2018-01-20 05:49
I think the problem in the video is that one of the markers there vanishes during extreme zoom out.

**Comment by bbeckk** [comment] 2018-01-20 08:59
No.. the problem is that when I click back, the map disappears (bt stays in the same form), hence back action doesn't work until the device screen is touched or back btn is clicked again ( in this case the form is back twice). The same problem occurs when the command in the onTop side menu is clicked.

**Comment by codenameone** [comment] 2018-01-21 05:22
OK, I got some issues crossed in my head. What's the `SideMenu` class?
There seems to be a lot of unused stuff within the test case that isn't related to the issue while some of the functionality that triggers the issue seems to be missing.

**Comment by bbeckk** [comment] 2018-01-21 06:55
Sorry, I missed that one... have a look now. I've kept all the necessary code there

**Comment by bbeckk** [comment] 2018-02-09 07:03
One more thing here, if the permission is asked, for instance camera permission in the same screen that has map component, it asks for the permission but though it is accepted, the permission is not given when seen in permission setting of the app.

**Comment by shannah** [comment] 2018-02-09 13:46
I see the issue with your apk, but I cannot reproduce the issue with your test case.  Make sure you have the most recent google maps cn1lib, and please verify that your test case produces the issue.

**Comment by shannah** [comment] 2018-02-16 13:43
Closing since the test case doesn't reproduce the described issue.  If testcase can be adjusted to reproduce issue, I'll reopen.

**Closed by shannah** 2018-02-16 13:43 UTC
