### ISSUE TITLE
[BUG?] Blank white screen after waking up app from background using a link

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2582] opened 2018-10-15 19:29 UTC
I tried to read more times my code and to do some trials, but I didn't find any error in my code.

As I described here:
https://stackoverflow.com/questions/52807700/intercept-an-url-with-a-given-domain-in-the-android-ios-and-javascript-ports-of

the problem is that my code works fine if the app is killed and then opened from a link, **but it doesn't work if the app is opened from the icon, then it is putted in background and then it is opened again from the link**: in this case, the app will show a blank white screen.

Tested on Android 7 (with this phone: https://www.gsmarena.com/huawei_honor_6x-8388.php)

Build hint:
`android.xintent_filter=<intent-filter><action android:name="android.intent.action.VIEW" /><category android:name="android.intent.category.DEFAULT" /><category android:name="android.intent.category.BROWSABLE" /><data android:host="example.com" android:scheme="https" /></intent-filter>`

Code:
```
public class MyApplication {

    private Form current;
    private Resources theme;
    private String arg;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());

        final SpanLabel message;
        arg = Display.getInstance().getProperty("AppArg", null);
        if (arg == null) {
            message = new SpanLabel("App launched from icon");
        } else {
            message = new SpanLabel("App launched from the url: " + arg);
        }
        hi.add(message);
        hi.show();

        hi.addShowListener(l -> {
            arg = Display.getInstance().getProperty("AppArg", null);
            if (arg == null) {
                message.setText("App launched from icon");
            } else {
                message.setText("App launched from the url: " + arg);
            }
            hi.revalidate();
        });

    }

    public void stop() {
        current = getCurrentForm();

        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();

        }
    }

    public void destroy() {
    }

}
```

**Comment by codenameone** [comment] 2018-10-16 04:03
Do you see anything in the device logs when this happens?

**Comment by jsfan3** [comment] 2018-10-16 09:38
I've just used my "Native Logs Reader" CN1Lib to get a full detailed log.
- I opened from icon and I got the log by Log.sendLogAsync();
- I put the app in background
- I tapped a link in Gmail that opened the app again
- The app shown me a blank white screen and I got the log by Log.sendLogAsync();

This is the result:

[EDT] 0:0:0,1 - Codename One revisions: fc0d6f39c091259d0fc5c972eb143c37e44eebba

[EDT] 0:0:0,4 - Native Logs Reader initialized correctly
[EDT] 0:0:0,120 - **--- NATIVE LOGS AFTER LAUCHING THE APP FROM ICON ---**
[EDT] 0:0:0,122 - --------- beginning of main
10-16 11:24:27.521 28205 28226 I Codename One: Resource not found: theme_phone.ovr
10-16 11:24:27.522 28205 28226 I Codename One: Resource not found: theme_android.ovr
10-16 11:24:27.523 28205 28226 I Codename One: Resource not found: theme_android-phone.ovr
10-16 11:24:27.557 28205 28231 I OpenGLRenderer: Initialized EGL, version 1.4
10-16 11:24:27.567 28205 28231 W linker  : /vendor/lib64/libhwuibp.so: unused DT entry: type 0xf arg 0xe3a
10-16 11:24:27.574 28205 28231 E OpenGLRenderer: allen debug liyu Key: 0
10-16 11:24:27.582 28205 28210 I art     : Do partial code cache collection, code=0B, data=21KB
10-16 11:24:27.583 28205 28210 I art     : After code cache collection, code=0B, data=21KB
10-16 11:24:27.583 28205 28210 I art     : Increasing code cache capacity to 128KB
10-16 11:24:27.600 28205 28226 E HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
10-16 11:24:27.601 28205 28226 E HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
10-16 11:24:27.602 28205 28226 E HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
10-16 11:24:27.608 28205 28226 I System.out: showKeyboard false
10-16 11:24:27.616 28205 28233 I WebViewFactory: Loading com.android.chrome version 68.0.3440.91 (code 344009152)
10-16 11:24:27.616 28205 28226 I System.out: [logcat, -d]
10-16 11:24:27.616 28205 28226 I System.out: null
10-16 11:24:27.616 28205 28226 I System.out: null
10-16 11:24:27.617 28205 28226 I System.out: Calling by::className:a.a.a.a.c  MethodName:b

[EDT] 0:1:33,733 - **--- NATIVE LOGS AFTER LAUCHING FROM LINK (THE APP WAS IN BACKGROUND) ---**
10-16 11:24:27.658 28205 28226 E HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
10-16 11:24:27.660 28205 28226 E HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
10-16 11:24:27.661 28205 28226 E HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
10-16 11:24:27.662 28205 28226 E HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
10-16 11:24:27.663 28205 28226 E HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
10-16 11:24:27.664 28205 28226 E HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
10-16 11:24:27.673 28205 28233 I cr_LibraryLoader: Time to load native libraries: 5 ms (timestamps 7975-7980)
10-16 11:24:27.679 28205 28258 E cr_VariationsUtils: Failed reading seed file "/data/user/0/cool.teammate.tests.intercept/app_webview/variations_seed_new": /data/user/0/cool.teammate.tests.intercept/app_webview/variations_seed_new (No such file or directory)
10-16 11:24:27.679 28205 28258 E cr_VariationsUtils: Failed reading seed file "/data/user/0/cool.teammate.tests.intercept/app_webview/variations_seed": /data/user/0/cool.teammate.tests.intercept/app_webview/variations_seed (No such file or directory)
10-16 11:24:27.680 28205 28233 I chromium: [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
10-16 11:24:27.680 28205 28233 I cr_LibraryLoader: Expected native library version number "68.0.3440.91", actual native library version number "68.0.3440.91"
10-16 11:24:27.687 28205 28231 E OpenGLRenderer: allen debug liyu Key: 4
10-16 11:24:27.689 28205 28231 E OpenGLRenderer: allen debug liyu Key: 3
10-16 11:24:27.693 28205 28258 W System  : ClassLoader referenced unknown path: 
10-16 11:24:27.713 28205 28210 I art     : Compiler allocated 5MB to compile void com.codename1.o.g.i.d(java.util.Hashtable)
10-16 11:24:27.771 28205 28210 I art     : Do partial code cache collection, code=36KB, data=55KB
10-16 11:24:27.772 28205 28210 I art     : After code cache collection, code=36KB, data=55KB
10-16 11:24:27.772 28205 28210 I art     : Increasing code cache capacity to 256KB
10-16 11:24:27.774 28205 28210 I art     : Compiler allocated 4MB to compile com.codename1.o.g.f com.codename1.o.g.i.a(java.lang.String, java.lang.String, boolean)
10-16 11:24:30.690 28205 28205 E c       : null
10-16 11:24:30.690 28205 28205 E c       : java.io.FileNotFoundException: /data/user/0/cool.teammate.tests.intercept/files/CN1$AndroidServiceProperties (No such file or directory)
10-16 11:24:30.690 28205 28205 E c       : 	at java.io.FileInputStream.open(Native Method)
10-16 11:24:30.690 28205 28205 E c       : 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
10-16 11:24:30.690 28205 28205 E c       : 	at android.app.ContextImpl.openFileInput(ContextImpl.java:530)
10-16 11:24:30.690 28205 28205 E c       : 	at android.content.ContextWrapper.openFileInput(ContextWrapper.java:186)
10-16 11:24:30.690 28205 28205 E c       : 	at com.codename1.impl.android.c.d(AndroidImplementation.java:6217)
10-16 11:24:30.690 28205 28205 E c       : 	at com.codename1.impl.android.c.e(AndroidImplementation.java:6243)
10-16 11:24:30.690 28205 28205 E c       : 	at cool.teammate.tests.intercept.MyApplicationStub.onStop(MyApplicationStub.java:166)
10-16 11:24:30.690 28205 28205 E c       : 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1301)
10-16 11:24:30.690 28205 28205 E c       : 	at android.app.Activity.performStop(Activity.java:7108)
10-16 11:24:30.690 28205 28205 E c       : 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4064)
10-16 11:24:30.690 28205 28205 E c       : 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4117)
10-16 11:24:30.690 28205 28205 E c       : 	at android.app.ActivityThread.-wrap27(ActivityThread.java)
10-16 11:24:30.690 28205 28205 E c       : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
10-16 11:24:30.690 28205 28205 E c       : 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-16 11:24:30.690 28205 28205 E c       : 	at android.os.Looper.loop(Looper.java:156)
10-16 11:24:30.690 28205 28205 E c       : 	at android.app.ActivityThread.main(ActivityThread.java:6523)
10-16 11:24:30.690 28205 28205 E c       : 	at java.lang.reflect.Method.invoke(Native Method)
10-16 11:24:30.690 28205 28205 E c       : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
10-16 11:24:30.690 28205 28205 E c       : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
10-16 11:26:01.092 28205 28205 E HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
10-16 11:26:01.096 28205 28205 E HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null
10-16 11:26:01.098 28205 28205 W WindowDecorActionBar: should not do the transition or the transition anim is null or it is running or the mContainer view is null or mContainer view hasn't been drawn to screen 
10-16 11:26:01.099 28205 28205 W CfgFilePolicy: No config file found for:/themes/diff/icons
10-16 11:26:01.099 28205 28205 W CfgFilePolicy: CFG_DIRS length : 12
10-16 11:26:01.113 28205 28205 I HwPointEventFilter: do not support AFT because of no config
10-16 11:26:01.189 28205 28226 I System.out: showKeyboard false
10-16 11:26:01.229 28205 28226 I System.out: [logcat, -d]
10-16 11:26:01.229 28205 28226 I System.out: null
10-16 11:26:01.229 28205 28226 I System.out: null
10-16 11:26:01.229 28205 28226 I System.out: Calling by::className:a.a.a.a.c  MethodName:b

**Comment by shannah** [comment] 2018-10-16 13:40
Was this log output from the sample code or different code.  I ask because I don't see the debugging print statements in the code that produce things like "--------- beginning of main".

Nothing specifically jumps out at me from either the sample code or the log.

Can you send me a project that I can build and test myself?  (e.g. post/share a github project or send me a zip)

**Comment by jsfan3** [comment] 2018-10-16 17:42
The log was from a slightly different code, in which I added the logging. 
This is a temporary link to a project that you can build and test yourself:
https://www.informatica-libera.net/docLavoro/InterceptLinks.zip

**Comment by shannah** [comment] 2018-10-16 18:08
So far haven't been able to reproduce with your test project.  Tried in Android 8 and Android 7.11 in android simulator.  Don't have a device right now with Android 7 to test on.

Are you doing a release build or a debug build?  If release, does it make a difference if you do a debug build?

**Comment by jsfan3** [comment] 2018-10-16 18:16
I've done a release build. Ok, I'm going to try a debug build...

**Comment by jsfan3** [comment] 2018-10-16 18:44
Using the debug build, the same issue happens...

**Comment by jsfan3** [comment] 2018-10-16 18:46
Can you test with a real Android device (even with a different Android version) opening the app from a Gmail link when the app is in background?

**Comment by codenameone** [comment] 2018-10-16 19:12
This works for me in Codename One Build. Do you see that behavior in that app?

**Comment by codenameone** [comment] 2018-10-16 19:50
You can log out and send a new link to yourself to see.

**Comment by jsfan3** [comment] 2018-10-16 19:57
Five minutes ago I tried what you suggested me, but I didn't received yet a new activation link...

**Comment by codenameone** [comment] 2018-10-16 20:02
I don't see an email in the queue. Did you press the done button or something else after entering the email? Did you see a toast message indicating success?

**Comment by jsfan3** [comment] 2018-10-16 20:08
Now I received the email and I've done the test: the app works correctly.

About the activation email, my smartphone was offline because a LAN issue and I didn't received any error from the app, that's why I supposed that me email was sent, instead it wasn't.

**Comment by codenameone** [comment] 2018-10-16 20:22
It's odd that it didn't send an error. I'll try to add that to my test cases. That means the core feature works the question is how does your implementation differ from ours? 
Since you have a standalone test case I suggest following the suggestion from @shannah and sending out the full project so we can see the differences and try to reproduce it.

**Comment by shannah** [comment] 2018-10-16 21:33
And that's the exact same project that you posted above?  No build hint differences?

**Comment by jsfan3** [comment] 2018-10-16 21:40
No, it's not the same project. I tried to do some changes removing the `showListener` _(because I hoped that changing the code could solve the issue...)_. No build hints differences _(except the domain, I suppose that it doesn't matter)_. This is the new code that doesn't use the `.addShowListener`:

```
import com.codename1.components.SpanLabel;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.util.UITimer;
import net.informaticalibera.cn1.nativelogreader.NativeLogs;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {

        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {
        String arg = Display.getInstance().getProperty("AppArg", null); // iOS and Android
        if (arg == null) {
            // https://www.codenameone.com/manual/appendix-javascript.html
            arg = Display.getInstance().getProperty("browser.window.location.href", null); // Javascript port
        }

        if (arg == null && current != null) {
            current.show();
            return;
        } else if (arg != null) {
            // we suppose to load a specific Form according to the arg
            Form anotherForm = new Form("Another Form", BoxLayout.y());
            SpanLabel message = new SpanLabel("App launched from the url:\n" + arg);
            anotherForm.add(message);
            anotherForm.show();
            return;
        }

        Form hi = new Form("Form without an arg", BoxLayout.y());
        SpanLabel message = new SpanLabel("This form is the \"default\" form shown if the app is launched without an arg");
        hi.add(message);
        hi.show();

    }

    public void stop() {
        current = getCurrentForm();

        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();

        }
    }

    public void destroy() {
    }

}
```

**Comment by jsfan3** [comment] 2018-10-16 22:21
Additional note: using the **exact same project** that previously I gave you (https://www.informatica-libera.net/docLavoro/InterceptLinks.zip), without modifying anything, I confirm the issue that the app is opened more times (if launched with differents args). This is the screenshot obtained with that code:

![screenshot_20181017-001603](https://user-images.githubusercontent.com/1997316/47050839-1ca0af80-d1a2-11e8-8d33-b58fcb20c697.png)

**Comment by jsfan3** [comment] 2018-10-17 10:16
No, I haven't a redirect url, neither a display.execute. I have only a standard https link and an intent-filter, as described in the Google documentation about "Deep Links" (I think that my build hint is correct according to the Google documentation): 
https://developer.android.com/training/app-links/deep-linking

**I recorded a video that shows my issue: maybe a video can be more understandable that a lot of words... :)
Link to the video: https://www.informatica-libera.net/videoLavoro/multipleAppOpening.mp4**

My use case is not an activation link. My use case is to offer the same content inside the app or inside a web-app (that will be the javascript port of the app).

This is my build hint (that is the same in project that I previously linked):
`android.xintent_filter=<intent-filter><action android:name="android.intent.action.VIEW" /><category android:name="android.intent.category.DEFAULT" /><category android:name="android.intent.category.BROWSABLE" /><data android:host="mywebsite.com" android:scheme="https" /></intent-filter>`

**Comment by jsfan3** [comment] 2018-10-17 10:18
As side note: in the video and in the build hint, you can see that I use the fake url "mywebsite.com". The issue is the same if I use my actual domain.

**Comment by codenameone** [comment] 2018-10-17 11:41
That's probably related to minor differences between intercepting URI's and the generic URL domain interception. We'll need to investigate that.

**Comment by shannah** [comment] 2018-10-17 13:05
Also unable to reproduce on Nexus 5 running Android 6.1.

The behaviour you are describing makes it sound like the app's main activity has a different launch mode.  The launch mode should be "singleTop".  Can you do a source build and check the AndroidManifest.xml file.

This is the AndroidManifest.xml file I get from my build.  

~~~~
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="cool.teammate.tests.intercept"
      android:versionCode="100"
      android:versionName="1.0"
      xmlns:tools="http://schemas.android.com/tools"
      android:minSdkVersion="15"
      android:installLocation="auto">
    <uses-sdk android:minSdkVersion="15" android:targetSdkVersion="27"  />
    <supports-screens android:smallScreens="true"
          android:normalScreens="true"
          android:largeScreens="true"
          android:xlargeScreens="true"
          android:anyDensity="true" />
  <application  android:label="InterceptLinks"  android:icon="@drawable/icon"  android:allowBackup="true" >
<provider
          android:name="android.support.v4.content.FileProvider"
          android:authorities="${applicationId}.provider"
          android:exported="false"
          android:grantUriPermissions="true">
          <meta-data
              android:name="android.support.FILE_PROVIDER_PATHS"
              android:resource="@xml/file_paths">
          </meta-data>
      </provider><meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>        <activity android:name="MyApplicationStub"
                  android:theme="@style/CustomTheme"
                  android:configChanges="orientation|keyboardHidden|screenSize"
                  android:launchMode="singleTop"
                  android:label="InterceptLinks">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
<intent-filter><action android:name="android.intent.action.VIEW" /><category android:name="android.intent.category.DEFAULT" /><category android:name="android.intent.category.BROWSABLE" /><data android:host="mywebsite.com" android:scheme="https" /></intent-filter>        </activity>
  <receiver android:name="com.codename1.impl.android.LocalNotificationPublisher" ></receiver>
<service android:name="com.codename1.impl.android.BackgroundFetchHandler" android:exported="false" />
<activity android:name="com.codename1.impl.android.CodenameOneBackgroundFetchActivity" android:theme="@android:style/Theme.NoDisplay" />
<activity android:name="com.codename1.location.CodenameOneBackgroundLocationActivity" android:theme="@android:style/Theme.NoDisplay" />
<service android:name="com.codename1.location.BackgroundLocationHandler" android:exported="false" />
<service android:name="com.codename1.location.GeofenceHandler" android:exported="false" />
<service android:name="com.codename1.media.AudioService" android:exported="false" />    </application>
    <uses-feature android:name="android.hardware.touchscreen" android:required="false" />
    <uses-feature android:name="android.hardware.telephony" android:required="false" />
    <uses-permission android:name="android.permission.INTERNET" android:required="false" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:required="false" />
  </manifest>

~~~~

Can you post yours so I can take a look?

**Comment by shannah** [comment] 2018-10-18 13:03
Try setting the build hint `android.activity.launchMode=singleTask`, and see if that makes a difference.

**Comment by codenameone** [comment] 2018-10-18 13:45
I recall there were issues with singleTask back in the day but I don't recall why. I think there is probably old discussions about this in the forum

**Comment by shannah** [comment] 2018-10-18 16:14
I know I've struggled with the launchMode before - and I'm pretty sure I've tried setting singleTask as the default before and run into issues.  Unfortunately, the build daemon repo doesn't include any logs prior to moving to github (2017) so I can't see any of this info... unless I can somehow dig up the old SVN logs.

When I do a search in my email for "singleTop" or "singleTask", I only find references to people running into similar problems with our singleTop default - and with instructions on using the android.activity.launchMode=singleTask build hint to resolve it.

It even finds this old post that I wrote on DZone https://dzone.com/articles/mobile-file-association-on-ios-android-amp-uwp  with a similar use case, where I also suggest changing it to singleTask.  

I can't find any documentation of what's wrong with using singleTask though.  Maybe I should just change the default to singleTask.    What do you think @codenameone ?

**Comment by codenameone** [comment] 2018-10-19 06:37
This produced issues with launching the app from an intent, unfortunately it's been such a long time ago I can't find a specific reference.

**Comment by shannah** [comment] 2018-10-22 11:17
Tough call then.  I guess I'll just leave it the way it is.

**Closed by shannah** 2018-10-22 11:17 UTC
