### ISSUE TITLE
New apps that use UIWebView are no longer accepted in ios side

### ISSUE THREAD

**Issue by DurankGts** [codenameone/CodenameOne#3537] opened 2021-12-07 16:40 UTC
Please help me to solve this issue. I'm using built hint 

codename1.arg.ios.noUIWebView=true

could you tell me what is the problem?

**Comment by shannah** [comment] 2021-12-07 16:52
We don't use UI webview at all - haven't for quite a while.

If you're getting that error when you submit your app, then it must be getting it from dependency.  Check your pod and ios native dependencies for likely culprits.  You may need to update version numbers of certain cocoapod dependencies.

**Comment by DurankGts** [comment] 2021-12-07 17:10
could you provide the correct version of cocoapod?

codename1.arg.ios.pods.platform=,9.0,7.0

this the build hint that I have used a long time ago

**Comment by DurankGts** [comment] 2021-12-07 19:08
Could you help me?

**Comment by DurankGts** [comment] 2021-12-07 19:24
this issue is more important now that the other issue related with localization.

**Comment by DurankGts** [comment] 2021-12-07 19:29
this the message from apple.
![image](https://user-images.githubusercontent.com/16245755/145093645-a96c5f1f-5688-4f41-a707-d49bf36138b4.png)

**Comment by DurankGts** [comment] 2021-12-08 13:02
...

**Comment by shannah** [comment] 2021-12-08 13:35
Do a build with sources, then send the resulting sources archive to the support channel, and I can take a look to see where your UIWebView is coming from.

**Comment by DurankGts** [comment] 2021-12-08 13:55
If this information is necessary to you in my app I'm using  the BrowserComponent. This the problem? if this the problem I can't understand why , because I launched other app using BrowserComponent.

**Comment by shannah** [comment] 2021-12-08 13:58
BrowserComponent doesn't use UIWebView.  It uses WKWebView.
The problem is likely in some dependency.

**Comment by DurankGts** [comment] 2021-12-08 17:10
Please check your email support with the source code

**Comment by DurankGts** [comment] 2021-12-08 18:48
this the solution steve? Please I need this update as soon as possible because we have a client waiting to test the app...

**Comment by DurankGts** [comment] 2021-12-08 19:46
@shannah  can I now to compile my project with this solution?

**Comment by shannah** [comment] 2021-12-09 17:56
It will be part of tomorrow's server update

**Comment by DurankGts** [comment] 2021-12-09 18:33
in witch hour it will available?

**Comment by DurankGts** [comment] 2021-12-10 12:28
please I need to Know if this fix is Available?

**Comment by DurankGts** [comment] 2021-12-10 12:40
How can I check what is the last update of your build server code?

**Comment by shannah** [comment] 2021-12-10 13:45
It should be there now.

**Comment by DurankGts** [comment] 2021-12-10 15:22
@shannah  this issue isn't solved yet. Please helpme with this I need to submitt an app to App Store To day before you can't give me support.

![image](https://user-images.githubusercontent.com/16245755/145597994-88a3978e-9e4d-490b-88d1-e9f2b0c263dc.png)

**Comment by DurankGts** [comment] 2021-12-10 15:36
I compare your tags recently and I don't see your fix. the Tags is the source code in your build server?

https://github.com/codenameone/CodenameOne/compare/v7.0.50...v7.0.51

![image](https://user-images.githubusercontent.com/16245755/145600020-4a4f551c-5d25-420e-b55b-ae77e5e8cb88.png)

**Comment by shannah** [comment] 2021-12-10 16:11
Looking into this deeper, it looks like this is caused by the GoogleMaps dependency.  If updating to 2.7.0 fixes this issue.
I will be updating the GoogleMaps cn1 later today with this version.  You can override this in your own project with the following build hint:

`var.ios.pods.GoogleMaps.version=2.7.0`

**Comment by DurankGts** [comment] 2021-12-10 16:16
Actually this build hint is added in my project

codename1.arg.ios.pods=,GoogleMaps ${var.ios.pods.GoogleMaps.version\:2.6.0}

this means if I just set 
codename1.arg.ios.pods=,GoogleMaps ${var.ios.pods.GoogleMaps.version\:2.7.0}

will work?

**Comment by shannah** [comment] 2021-12-10 16:21
no.

That build hint is added by the lib.  If you change it, it may conflict with the one provided by the lib.
Use the one I suggested above.

**Comment by DurankGts** [comment] 2021-12-10 16:23
could you write again completely the build hint please?

all your build hint have codename1 prefix. 

???????var.ios.pods.GoogleMaps.version=2.7.0

**Comment by shannah** [comment] 2021-12-10 16:38
If you set the build hint in the Codename One Settings, it will add the prefix automatically.  If you edit it directly in the codenameone_settings.properties file, then you need to add the prefix.  I will never include the prefix when describing what build hints to add, as the prefix is implied (it is also an implementation detail).

The build hint is `var.ios.pods.GoogleMaps.version=2.7.0`.
In the codenameone_settings.properties file, with prefix, this would appear as
`codename1.arg.var.ios.pods.GoogleMaps.version=2.7.0`

**Comment by DurankGts** [comment] 2021-12-10 16:42
I always use directly in the file. that the reason of my question. I don't use the ui settings.

**Comment by shannah** [comment] 2021-12-10 17:00
I have updated the GoogleMaps cn1lib now.  Version 1.02 has been pushed to maven central, and will be available in a few hours.  CodenameOne preferences will also have the update available in a few hours.  Alternatively, you can get the updated cn1lib [here](https://github.com/codenameone/codenameone-google-maps/blob/master/GoogleMaps.cn1lib)

With the updated lib you will no longer need to set the `var.ios.pods.GoogleMaps.version` build hint.

**Closed by shannah** 2021-12-10 17:00 UTC
