### ISSUE TITLE
RFE: add "Doesn't compile sources" (or "Include ONLY sources") as option for the build servers

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2990] opened 2020-01-14 08:04 UTC
Currently, in the "Codename One Settings", "Basic" section, there is the checkbox "Include sources".

Can you add an option "Doesn't compile sources", that is equivalent to say "Include ONLY sources"?

This could be convenient and time-saver at least in two circumstances:

1. when we are interested only in the sources, because we are developing a native interface or other code that we want to write and test in Android Studio or Xcode; consider that I usually have to wait five-six minutes for the build server compiling (especially for the iOS builds), that's why in this case a similar option can be time-saver;

2. when we want to investigate odd build server errors: in several circumstances in which the actual cause of a build error is not clear, it could be faster and effective trying to compile the sources locally to discover why they generate a compile error.

Thank you

**Comment by codenameone** [comment] 2020-01-14 18:40
Duplicate of #1500

**Closed by codenameone** 2020-01-14 18:40 UTC
Labels: duplicate

**Comment by jsfan3** [comment] 2020-01-14 18:46
Oh... I wasn't aware that there was a so long discussion before!!!
