### ISSUE TITLE
[BUG Javascript port] Dialog unexpected behavior

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2519] opened 2018-08-18 11:18 UTC
Please see this test case built as Javascript (with the browser Console opened):
https://cloud.codenameone.com/build/getData?m=result&i=ec49b6be-166e-476b-88dd-bf3216cdf042&b=7fea9d80-8744-4cf9-bfdc-a5a37c22c5e3&n=preview7446862976523410167.html

Click on "Show Dialog", type one or more chars in the "keyword" field, after that in the browser console is logged "OK pressed" _(that's not true!)_ and you will see a new Dialog that shows an error "Cannot insert row" (that Dialog is inside the ActionLister of the OK button).

This is the code that I used to generate this test case:
```
package ...;

import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.properties.BooleanProperty;
import com.codename1.properties.InstantUI;
import com.codename1.properties.IntProperty;
import com.codename1.properties.Property;
import com.codename1.properties.PropertyBusinessObject;
import com.codename1.properties.PropertyIndex;
import com.codename1.ui.Button;
import com.codename1.ui.Command;
import com.codename1.ui.Container;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class TestCase {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if (err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        Button showDialog = new Button("Show Dialog");
        SportTypeDAO dao = new SportTypeDAO();
        InstantUI iui = new InstantUI();
        iui.excludeProperty(dao.position);
        iui.excludeProperty(dao.isNew);

        showDialog.addActionListener(l -> {
            Container instantUiCnt = iui.createEditUI(dao, true);
            Command okCmd = Command.create("OK", null, ev -> {
                Log.p("OK Pressed");
                if (dao.keyword.get() != null && !dao.keyword.get().isEmpty()
                        && dao.text_IT.get() != null && !dao.text_IT.get().isEmpty()
                        && dao.text_EN.get() != null && !dao.text_EN.get().isEmpty()
                        && dao.position.get() != null) {
                    dao.keyword.set(dao.keyword.get().trim().toLowerCase());
                } else {
                    Dialog.show("CannotInsertRow", "CannotInsertRowText", null, "OK");
                }
            });

            Command cancel = Command.create("CANCEL", null, ev -> {
                Log.p("CANCEL pressed");
            });
            Dialog.show("Test Dialog", iui.createEditUI(dao, true), okCmd, cancel);
        });

        hi.add(showDialog);

        hi.show();
    }

    public void stop() {
        current
                = getCurrentForm();

        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current
                    = getCurrentForm();

        }
    }

    public void destroy() {
    }

}

class SportTypeDAO implements PropertyBusinessObject {

    public final Property<String, SportTypeDAO> keyword = new Property<>("keyword");
    public final Property<String, SportTypeDAO> text_IT = new Property<>("text_IT");
    public final Property<String, SportTypeDAO> text_EN = new Property<>("text_EN");
    public final IntProperty<SportTypeDAO> position = new IntProperty<>("position");
    public final BooleanProperty<SportTypeDAO> isNew = new BooleanProperty<>("isNew");

    private PropertyIndex idx = new PropertyIndex(this, "SportTypeDAO",
            keyword, text_IT, text_EN, position, isNew);

    @Override
    public PropertyIndex getPropertyIndex() {
        return idx;
    }

    public SportTypeDAO() {
        isNew.set(false);
        position.set(0);
        idx.setExcludeFromJSON(isNew, true);
        idx.setExcludeFromMap(isNew, true);
    }
}

```

**Comment by jsfan3** [comment] 2018-08-18 12:38
This test case can be made simpler without the InstantUI _(as in following code)_, however the wrong behavior is the same. Moreover, both in the Simulator and in the Javascript port the Dialog is not rendered correctly, because only the first TextComponent is shown correctly... the Dialog size is too small _(this is a just discovered second issue)_.

```
    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        Button showDialog = new Button("Show Dialog");

        showDialog.addActionListener(l -> {
            Container body = new Container(new TextModeLayout(3, 1));
            TextComponent title = new TextComponent().label("Keyword");
            TextComponent text_IT = new TextComponent().label("Text_IT");
            TextComponent text_EN = new TextComponent().label("Text_EN");
            body.addAll(title, text_IT, text_EN);

            Command okCmd = Command.create("OK", null, ev -> {
                Log.p("OK Pressed");
                if (title.getText() != null && !title.getText().isEmpty()
                        && text_IT.getText() != null && !text_IT.getText().isEmpty()
                        && text_EN.getText() != null && !text_EN.getText().isEmpty()) {
                    Log.p("Data inserted: " + title.getText() + ", " + text_IT.getText() + ", " + text_EN.getText());
                } else {
                    Dialog.show("Data Invalid", "Some inputs are empty", "OK", null);
                }
            });

            Command cancel = Command.create("CANCEL", null, ev -> {
                Log.p("CANCEL pressed");
            });
            Dialog.show("Test Dialog", body, okCmd, cancel);
        });

        hi.add(showDialog);

        hi.show();
    }
```

**Comment by codenameone** [comment] 2018-08-18 12:43
I would suggest not doing text input in a dialog. It's generally a bad practice to do that. An interaction dialog would be slightly better. But inherently dialogs are bad for text input.

**Comment by jsfan3** [comment] 2018-08-18 13:40
Thank you for your suggestion. Use an InteractionDialog instead of a Dialog is good workaround for this specific issue, because it's rendered correctly in Javascript (and in the Simulator):
https://cloud.codenameone.com/build/getData?m=result&i=0a6a06c4-0297-4232-a470-1dc038445dac&b=81902886-87fc-4b8b-82a1-b715e04ec656&n=preview5404280268306837766.html

I suppose that your suggestion to don't use dialogs for text input is because a problem of user experience design, or are there other technical reasons?

**Comment by codenameone** [comment] 2018-08-18 13:52
Dialogs have several problems with input. First the modality aspect of a dialog creates some edge cases with text input. `invokeAndBlock` which is the feature underlying modality can can impact text input by relaying events in problematic ways.
Another problem is scrollability. The size of a dialog is fixed so if a virtual keyboard comes up you have nowhere to scroll to. It makes input very difficult.
Finally, dialog is a different form. That means that input can't impact the underlying form instantly.

**Comment by jsfan3** [comment] 2018-08-18 13:57
Thank you for the explanation :)

**Comment by shannah** [comment] 2018-08-20 14:29
> Click on "Show Dialog", type one or more chars in the "keyword" field, after that in the browser console is logged "OK pressed" (that's not true!) and you will see a new Dialog that shows an error "Cannot insert row" (that Dialog is inside the ActionLister of the OK button).

I tried your 2nd simplified test case on Chrome, and Firefox on OS X, and Edge on Windows, and could not reproduce the problem "OK pressed" problem.  I.e. I clicked on "Show Dialog", and it opened the dialog correctly, and did not log "OK pressed" to the console until I pressed the "OK" button.

> Dialog is not rendered correctly, because only the first TextComponent is shown correctly... the Dialog size is too small (this is a just discovered second issue).

This issue is now fixed.  Will be included in next update.

**Comment by jsfan3** [comment] 2018-08-20 15:08
> I tried your 2nd simplified test case on Chrome, and Firefox on OS X, and Edge on Windows, and could not reproduce the problem "OK pressed" problem. I.e. I clicked on "Show Dialog", and it opened the dialog correctly, and did not log "OK pressed" to the console until I pressed the "OK" button.

I tried again that case and it produces the same issue. Can you please check this link? Is the page produced by you different?
https://cloud.codenameone.com/build/getData?m=result&i=c2235e4d-c7de-497b-bfbd-d2db23879803&b=c2ef223f-8ac0-48df-823b-582f5434c488&n=preview7249944964376794552.html

**Comment by shannah** [comment] 2018-08-20 15:12
That works fine in Chrome on Mac.  ("OK pressed" isn't logged until you actually press "OK").

**Comment by jsfan3** [comment] 2018-08-20 15:28
It's very very strange. In this video I show you what I see and what I do to reproduced the bug:
https://www.informatica-libera.net/videoLavoro/bugDialogJavaScript.mp4

Tested with "Chrome 68" 64bit on Linux. But the same issue is with "Firefox 61" on Linux, so I suppose that it's not related to the operating system.

**Comment by shannah** [comment] 2018-08-20 17:02
OK.  I have reproduced the issue and fixed it.  The fix will be included in the next update.

**Closed by shannah** 2018-08-20 17:02 UTC

**Comment by jsfan3** [comment] 2018-08-20 17:15
Thank you! :-)
