### ISSUE TITLE
Freeze and crash using keybord next button with actionListener on TextField

### ISSUE THREAD

**Issue by jpaul51** [codenameone/CodenameOne#2544] opened 2018-09-12 09:01 UTC
When I use the next button of the keyboard when editing a TextField, the app freezes and crashes. This happens because I put an actionListener on the TextField with an InfiniteProgress:

```
 public void start() {
        if (current != null) {
            current.show();
            return;
        }
        Form hi = new Form("Welcome", new BorderLayout(BorderLayout.CENTER_BEHAVIOR_CENTER_ABSOLUTE));

        Container ctFields = new Container(new BoxLayout(BoxLayout.Y_AXIS));
        hi.add(BorderLayout.CENTER, ctFields);
        TextField txtField1 = new TextField();
        TextField txtField2 = new TextField();
        TextField txtField3 = new TextField();
        ctFields.add(txtField1).add(txtField2).add(txtField3);

        addListener(txtField3);
        addListener(txtField1);
        addListener(txtField2);

        hi.show();
    }

    private void addListener(TextField txtField) {
        txtField.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                Dialog progress = new InfiniteProgress().showInfiniteBlocking();
                Timer t = new Timer();
                t.schedule(new TimerTask() {
                    @Override
                    public void run() {
                        Display.getInstance().callSerially(new Runnable() {
                            @Override
                            public void run() {
                                progress.dispose();
                            }
                        });

                    }
                }, 3000);

            }
        });
    }
```

And this is what I get on Android logcat after the freeze:
```
09-12 10:49:46.556  1602  1646 E ActivityManager: PID: 8473
09-12 10:49:46.556  1602  1646 E ActivityManager: Reason: Input dispatching timed out (Waiting because the touched window's input channel is full.  Outbound queue length: 1.  Wait queue length: 52.)
09-12 10:49:46.556  1602  1646 E ActivityManager: Load: 0.0 / 0.0 / 0.0
09-12 10:49:46.556  1602  1646 E ActivityManager: CPU usage from 51543ms to 0ms ago (2018-09-12 10:48:53.099 to 2018-09-12 10:49:44.643):
09-12 10:49:46.556  1602  1646 E ActivityManager:   23% 657/logd: 22% user + 0.9% kernel / faults: 15 minor
09-12 10:49:46.556  1602  1646 E ActivityManager:     21% 1098/logd.reader.per: 21% user + 0.3% kernel
09-12 10:49:46.556  1602  1646 E ActivityManager:     0.8% 662/logd.writer: 0.4% user + 0.4% kernel
09-12 10:49:46.556  1602  1646 E ActivityManager:     0.5% 1096/logd.reader.per: 0.3% user + 0.1% kernel
09-12 10:49:46.556  1602  1646 E ActivityManager:     0% 665/logd.auditd: 0% user + 0% kernel
09-12 10:49:46.556  1602  1646 E ActivityManager:   19% 1602/system_server: 10% user + 9.2% kernel / faults: 72983 minor 49 major
```

**Comment by codenameone** [comment] 2018-09-13 10:44
@shannah I assigned this for 5.0 strictly to evaluate whether this is an issue that warrants a code freeze fix. On the surface it seems like something we can push for 6.0.

**Comment by shannah** [comment] 2018-09-19 14:06
I have reproduced this issue on Nexus 5/Android 6

**Comment by shannah** [comment] 2018-09-19 16:58
I have fixed the deadlock - but this is an antipattern because InfiniteProgress.showInfiniteBlocking() actually creates a new Dialog, which is a new Form - so it navigates away from the current form.  Any time a form is changed, text editing is stopped.

So this example will no longer deadlock, but the keyboard will be closed when the inifinite progress finishes.

**Closed by shannah** 2018-09-19 16:58 UTC
