### ISSUE TITLE
FileChooser not working in iOS device

### ISSUE THREAD

**Issue by poojanarshetty** [codenameone/CodenameOne#2622] opened 2018-11-26 16:43 UTC
Hi,

I am using FileChooser in my app, was working fine before like few months before. But now suddenly it stopped working I mean it don't open anything. The code is as given below

`if(FileChooser.isAvaliable()){
FileChooser.showOpenDialog(".zip,application/zip", (e)->{
				
				final String file= (String) e.getSource();
				// code implemenation

}});
`
It just dont do anything at FileChooser.isAvaliable(). Please let me know whats the issue. Thanks

**Comment by shannah** [comment] 2018-11-26 16:44
What device does this occur on?  What version of iOS?

**Comment by poojanarshetty** [comment] 2018-11-26 17:06
It's occurring on iPhone and iPad even and iOS12 version I am using

**Comment by shannah** [comment] 2018-11-27 18:39
My samples are working ok.  Can you post a test case?

**Comment by poojanarshetty** [comment] 2018-11-28 15:18
Ok, its working fine now, dont know what was the issue. Sent to build again it started working. 

But, if I press cancel option of FileChooser dialog, instead of returning back to app, its exiting the app completely.

**Comment by poojanarshetty** [comment] 2018-12-13 11:32
Hi, sorry for late reply. So it works fine when app is sent for debug build. But when app is downloaded from app-store, the filechooser not working, it just dont pop-up. I am checking on iOS 12 for iPAD and iPhone.
It doesnt work when app is submitted to App-store and installed from there.

**Comment by poojanarshetty** [comment] 2019-01-09 09:46
Hi, May I know when this issue will be resolved?

**Comment by shannah** [comment] 2019-01-09 13:32
It is marked for version 6 which is scheduled for Feb. 19th.  There are a lot of issues that still need to be resolved for that release so it may get pushed back.  

Given the information you have provided so far (works on debug but not in app store), it is likely that you just have a problem with your provisioning profiles.  Make sure that your app store provisioning profile includes iCloud support.

**Comment by shannah** [comment] 2019-01-15 14:34
Pushed to version 7.0 as I can't reproduce.  Likely this is an issue with the provisioning profiles.  Haven't heard back after suggested fixes to OP.

**Comment by poojanarshetty** [comment] 2019-01-16 09:15
It does includes iCloud support in provisioning profile.

**Comment by shannah** [comment] 2019-01-16 12:55
If you can hook it up to a Mac and get the device log from Xcode, that will help.

**Comment by shannah** [comment] 2019-07-24 12:38
Closing this issue as haven't received any feedback to help reproduce it.

**Closed by shannah** 2019-07-24 12:38 UTC
Labels: Feedback, Stalled
