### ISSUE TITLE
App not reacting on touches after pressing on social share button (iOS)

### ISSUE THREAD

**Issue by kutoman** [codenameone/CodenameOne#2164] opened 2017-07-13 14:30 UTC
as the title says. I noticed that after double tapping (after the issue happens) the `Form` acts as usual again.

Note: `CN.share` doesn't seem to cause such problems

**Comment by shannah** [comment] 2017-08-18 22:36
@kutoman Can you post a snippet that I can use as the basis for a test case.  I have apps with social share and don't see this issue happening.

**Comment by kutoman** [comment] 2017-08-22 08:34
I try to reproduce it in a sample code but without success (means I'm not facing any problems there). I will post a snippet as soon as possible.

**Comment by kutoman** [comment] 2017-08-22 09:45
finally I figured it out. Here you go:

        ShareButton sb = new ShareButton();
        sb.setTextToShare("share this");
        
        Container page = BorderLayout.center(new Label("some text"));
        page.add(BorderLayout.SOUTH, BorderLayout.east(sb));
        page.revalidate();
        
        form.addComponent(BorderLayout.CENTER, page);

**Comment by kutoman** [comment] 2017-08-25 12:52
as I created a custom share button as a workaround. I noticed that this issue seems to be linked to the sourceRect indication. Since when I use `CN.share(String text, String image, String mimeType)` the share target options get displayed but when I use `CN.share(String text, String image, String mimeType, Rectangle sourceRect)` I get the same issue as with the `ShareButton`.

**Comment by shannah** [comment] 2017-09-25 14:24
@kutoman I tried using your sample code, and still couldn't reproduce it on iOS 10, iPhone 6S.

**Comment by shannah** [comment] 2017-09-25 14:24
Moving to 3.9 pending new information that will allow me to reproduce issue.

**Comment by kutoman** [comment] 2017-09-27 08:14
hmm weird. The issue still remains for me, despite rebuilding the app. Back then I was using iOS 10, currently iOS 11. The `ShareButton` just doesn't show any reaction.

**Comment by shannah** [comment] 2017-09-27 14:42
Yes.  That was it. It only occurred on iPad.  And only on ones with retina.

**Closed by shannah** 2017-09-27 14:42 UTC

**Comment by kutoman** [comment] 2017-09-27 15:06
ah nice. I almost began to think it was black magic :D
