### ISSUE TITLE
[BUG] On Android 7 sometimes the text cannot be entered

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CodenameOne#2447] opened 2018-06-09 16:21 UTC
I noticed on the Facebook clone the same problem that sometimes I have with my apps (only with Android 7).

Please look at this code from the SignupForm.java of the Facebook clone:
```
SignupForm s = new SignupForm("Name", "Terms",
                getCurrentForm());
        Label title = new Label("What's Your Name?", "SignupSubHeader");
        TextComponent first = new TextComponent().
                label("First Name").columns(12);
        TextComponent last = new TextComponent().
                label("Last Name").columns(12);

        User currentUser = new User();
        UiBinding uib = new UiBinding();
        uib.bind(currentUser.firstName, first);
        uib.bind(currentUser.familyName, last);
        
        TextModeLayout layout = new TextModeLayout(1, 2);
        Container textContainer = new Container(layout, "PaddedContainer");
        textContainer.add(layout.createConstraint().
                widthPercentage(50), first);
        textContainer.add(layout.createConstraint().
                widthPercentage(50), last);
        [...]
```

The problem is that sometimes, after entering the first name and tapping "Next" on the virtual keyboard, the last name field gets the focus, but the virtual keyboard doesn't respond to the user input. The only chance to enter the last name, in this case, is to close the virtual keyboard and tap the last name field to get the virtual keyboard responsive again.

This problem is absent on iPhone. I mentioned Android 7 because it's the only version on a real device that I have at the moment.

It seems that this issue happens randomly.

**Comment by shannah** [comment] 2018-06-11 13:31
I've been playing with it inside the Android 7 emulator (Nexus 5X API 27)
![image](https://user-images.githubusercontent.com/2677562/41234354-c86a7f10-6d40-11e8-8e5d-630dae931900.png)

Haven't been able to reproduce so far.  I'm using the Facebook clone app, on the Name form (the one described in this issue) as a test case.

Proceeding to a real device (Nexus 5 with Android 6) to try to reproduce.  I don't have a real device with Android 7 currently to test.

**Comment by shannah** [comment] 2018-06-11 13:34
Can't seem to reproduce it on Nexus 5 real device with Android 6.0.1 either.

**Comment by jsfan3** [comment] 2018-06-11 14:18
Thank you for the trials you have done. At the moment, it stopped to reproduce also on my device. It's very strange, because few days ago I experienced this problem more times. I don't understand what condition is changed. Please keep this issue open, when it will happen again I'll try to record a video.

**Comment by shannah** [comment] 2018-07-19 15:32
Closing this issue since it can't be reproduced.   Will reopen if it reappears or if more information is provided.

**Closed by shannah** 2018-07-19 15:32 UTC

**Comment by jsfan3** [comment] 2018-07-22 22:44
This bug reappared. This time I was able to record a video:
https://www.informatica-libera.net/videoLavoro/bugInputText.mp4

As you can see, I've done some trials before being able to input text. Before recording the video, I typed the "F" in the FirstName, then I tapped the FamilyName, finally I tapped again the FirstName but I wasn't able to enter the text. Then I started to record the video. Only after tapping the FamilyName again and then the FirstName, I was able to enter text.
