### ISSUE TITLE
Issues creating new project with kotlin and intellij

### ISSUE THREAD

**Issue by comdori** [codenameone/CodenameOne#2302] opened 2018-01-11 18:36 UTC
I've experienced the following issues with project creation and submitting an android build in codename one using kotlin.

1 create new codenameone project from intellij
2 enter classname and project name as Time2Demo
3 open cno prefs, go to extensions, search kotlin and download then close the prefs dialog
4 refresh cn1libs
5 select main class in project explorer and from the main menu Code -> "Convert Java to Kotlin File"
6 change     fun init(context: Any) {  to     fun init(context: Any?) { <ISSUE 1>
7 change "class Time2Demo" to "open class Time2Demo" <ISSUE 2>
8 right click Time2Demo class and run verify that the demo app loads in the simulator
9 close the simulator window
10 invoke "send android build"

Attempt 1
11 get error "D:\dev\Time2Demo\build.xml:495: Unable to delete file D:\dev\Time2Demo\lib\impl\cls\META-INF\MANIFEST.MF" <ISSUE 3>
12 try to recompile and kotlin is broken with error "Error:(31, 23) Kotlin: Unresolved reference: Any" - ok try again

Attempt 2
11 Get prompted that i haven't set up a certificate and accept in this instance because its a test
12 View error in build server log <ISSUE 4>

/tmp/build2144932049183748973xxx/Time2Demo/src/main/java/mypackage/Time2DemoStub.java:27: error: cannot find symbol
    private static Time2Demo i;
                   ^
<ISSUE 5>  There is an error from "send android build" for every usage of the standard Kotlin extension function String.toInt() so you have to replace them in your codebase to get the build to work

Intellij version
IntelliJ IDEA 2017.3.2 (Community Edition)
Build #IC-173.4127.27, built on December 25, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

JDK 1.8.0_152

**Comment by shannah** [comment] 2018-01-17 18:12
Issue 1 & Issue 2 we can't really do anything about as this is the way IntelliJ's converter works.  Ideally we'll create a Kotlin project template so you don't have to use the Java > Kotlin converter on the main class.

Issue 3 looks like it's Windows related. (If you have a file or directory opened in any program - including file exporer, it won't let you delete it - so that foils the build script when it tries to delete that file).

Issue 4: Looks like this is an issue with the build.xml file not being updated until the project is opened for the second time.  I.e. If you close the project and reopen it (or quit intelliJ and reopen) it will work.

Issue 5:  Haven't looked into this yet.

**Comment by comdori** [comment] 2018-01-17 20:53
Thanks for looking into these issues! None of them are blockers but I think fixing them would help people using kotlin on codenameone and make it less confusing for someone starting a project or an evaluation.  Not as much of a blocker as the object val issue though :)

**Comment by shannah** [comment] 2018-01-18 15:10
Issue 4 is now fixed in Git.  It will be included in the next plugin update.

**Comment by shannah** [comment] 2018-01-18 15:16
I can't reproduce Issue 5.

Test case 

~~~~package com.codename1.kotlin2302p12


import com.codename1.ui.CN.*
import com.codename1.ui.Display
import com.codename1.ui.Form
import com.codename1.ui.Dialog
import com.codename1.ui.Label
import com.codename1.ui.plaf.UIManager
import com.codename1.ui.util.Resources
import com.codename1.io.Log
import com.codename1.ui.Toolbar
import java.io.IOException
import com.codename1.ui.layouts.BoxLayout

/**
 * This file was generated by [Codename One](https://www.codenameone.com/) for the purpose
 * of building native mobile applications using Java.
 */
open class MyApplication {

    private var current: Form? = null
    private var theme: Resources? = null

    fun init(context: Any?) {
        theme = UIManager.initFirstTheme("/theme")

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true)

        // Pro only feature
        Log.bindCrashProtection(true)
    }

    fun start() {
        if (current != null) {
            current!!.show()
            return
        }
        val hi = Form("Hi World", BoxLayout.y())
        hi.add(Label("Hi World"))
        val result:Int = "3".toInt() + "4".toInt()
        Log.p("Result of 3+4="+result);
        hi.show()
    }

    fun stop() {
        current = getCurrentForm()
        if (current is Dialog) {
            (current as Dialog).dispose()
            current = getCurrentForm()
        }
    }

    fun destroy() {
    }

}
~~~~

Works fine building for Android.

**Closed by shannah** 2018-01-18 15:16 UTC
