### ISSUE TITLE
Border image improvements

### ISSUE THREAD

**Issue by FabricioCabeca** [codenameone/CodenameOne#1579] opened 2015-09-14 23:35 UTC
Hi, I've noticed that the Border class does not use the graphics tileImage(), this is bad since there is a lot of random code to do the same logic and prevents implementation optimizations on this heavily used class. Here is an example of such tileImage() usage:

```
diff --git a/CodenameOne/src/com/codename1/ui/plaf/Border.java b/CodenameOne/src/com/codename1/ui/plaf/Border.java
index df23702..0eddf43 100644
--- a/CodenameOne/src/com/codename1/ui/plaf/Border.java
+++ b/CodenameOne/src/com/codename1/ui/plaf/Border.java
@@ -1289,11 +1289,6 @@ public class Border {
                 break;
             }
             case TYPE_IMAGE_HORIZONTAL: {
-                int clipX = g.getClipX();
-                int clipY = g.getClipY();
-                int clipWidth = g.getClipWidth();
-                int clipHeight = g.getClipHeight();
-                //g.pushClip();
                 Image left = images[0];
                 Image right = images[1];
                 Image center = images[2];
@@ -1304,15 +1299,7 @@ public class Border {
 
                 g.drawImage(left, x, y);
                 g.drawImage(right, x + width - right.getWidth(), y);
-                x += left.getWidth();
-                width -= (left.getWidth() + right.getWidth());
-                g.clipRect(x, y, width, height);
-                int centerWidth = center.getWidth();
-                for(int xCount = x ; xCount < x + width ; xCount += centerWidth) {
-                    g.drawImage(center, xCount, y);
-                }
-                g.setClip(clipX, clipY, clipWidth, clipHeight);
-                //g.popClip();
+                g.tileImage(center, x + left.getWidth(), y, width - left.getWidth() - right.getWidth(), height);
                 break;
             }
             case TYPE_IMAGE_VERTICAL: {
```

In the windows port that I am writing we do have such implementation improvement, tiling images using DirectX is way faster. Also, for Android you should definitively consider using android.graphics.Shader for the same job, maybe like this:

```
bitmapDrawable.setTileModeXY(Shader.TileMode.REPEAT, Shader.TileMode.REPEAT);
```

**Comment by codenameone** [comment] 2015-09-15 03:17
Looks good. Do you want to file this as a pull request so the commit will be attributed to you?

**Comment by FabricioCabeca** [comment] 2015-09-15 11:10
Actually there are other places in Border that would need these changes, let me take a deeper look into this and do some more testing before.

**Comment by FabricioCabeca** [comment] 2015-09-16 21:51
Done ! Take a look at this: https://github.com/codenameone/CodenameOne/pull/1580

**Comment by codenameone** [comment] 2015-09-17 02:00
Thanks! Merged.

**Closed by codenameone** 2015-09-17 02:00 UTC

**Comment by jaanushansen** [comment] 2015-10-19 07:54
Hi!

I noticed a border problem with my project, I assume that it is related to this patch. I was waiting for the issue to occur also on CN1 build server, but so far I have managed to reproduce it only when building locally. Hopefully it means, that build server has not been updated for a long time?

The problem is, that my image border on iOS looks like this:

![iosimageborder](https://cloud.githubusercontent.com/assets/11716510/10572213/e2e8e2be-764e-11e5-9c79-581e3fd65c9c.png)

But it should be:
![imageborder](https://cloud.githubusercontent.com/assets/11716510/10572227/f5e18f9c-764e-11e5-879d-8890fc3163a8.png)

You can test it with this resource file (use splashScreen form):

http://sunaaj.planet.ee/now/theme.res

**Comment by FabricioCabeca** [comment] 2015-10-19 13:55
Hi @jaanushansen , this patch did have an issue with iOS due to differences in the way image tiling was handled, but it was fixed (and that's why you can't replicate it in the build server). I suggest you to update your local project to use the latest source or use the build server.

**Comment by jaanushansen** [comment] 2015-10-20 04:35
Hi @FabricioCabeca 

Thanks for your reply, it helped me to solve the issue. The mentioned problem occurs only on old Grpahics Pipeline, that is when `codename1.arg.ios.newPipeline=false`. But probably there is no good reason to use the old one, that means there really is no problem :)

**Comment by FabricioCabeca** [comment] 2015-10-20 13:32
Thanks @jaanushansen for your feedback, you should stick with the new pipeline for sure.

@codenameone , what do you think about this ? Is it time to remove the old pipeline or should we fix it ?

**Comment by codenameone** [comment] 2015-10-20 16:52
No need to fix it.
