### ISSUE TITLE
Scanning a barcode in iOS 12.0.1  crashes app

### ISSUE THREAD

**Issue by mwarnett** [codenameone/CodenameOne#2588] opened 2018-10-19 12:18 UTC
My iPod Touch was just updated to 12.0.1 and now I can no longer scan a barcode. When I hit my scan button, the app crashes.

Downgraded my iPod Touch to iOS 12.0 and barcode scanning is working again. So it looks as though the 12.0.1 update triggered this.

**Comment by shannah** [comment] 2018-10-22 12:48
I just created a test app with the cn1-codescan library.   Tested on iPhone 8 with iOS 12.0.1

Initially the app crashed because it didn't have the ios.NSCameraUsageDescription build hint.  After adding that, the app runs fine.

My Test app:

~~~~
package com.codename1.tests.barcodescanner;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ext.codescan.CodeScanner;
import com.codename1.ext.codescan.ScanResult;
import com.codename1.ui.Button;
import com.codename1.ui.Container;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class BarcodeScanner {

    private Form current;
    private Resources theme;

    private void scanCode(Container cnt) {
        CodeScanner.getInstance().scanBarCode(new ScanResult() {

            public void scanCompleted(String contents, String formatName, byte[] rawBytes) {
                //barCode.setText("Bar: " + contents);
                cnt.addComponent(new Label(contents));
                cnt.revalidate();
            }

            public void scanCanceled() {
                System.out.println("cancelled");
            }

            public void scanError(int errorCode, String message) {
                System.out.println("err " + message);
            }
        });
    }
    
    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World", BoxLayout.y());
        Container result = new Container(BoxLayout.y());
        Button b = new Button("Scan");
        b.addActionListener(e->{
            scanCode(result);
        });
        hi.add(b);
        hi.add(result);
        
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
~~~~

Please confirm that 

1. You have the `ios.NSCameraUsageDescription` build hint.  (https://www.codenameone.com/blog/xcode-9-mode.html)
2. This test app fails on your device.

If this test app fails for you (with the build hint specified), please let me know.  If it passes, and your own test still fails (with the build hint), please provide a test case that reproduces the problem.

I'm going to make a change to the cn1-codescan lib to automatically add this build hint.

**Comment by shannah** [comment] 2018-10-22 13:06
I have updated the cn1-codescan lib to automatically add this build hint when you run it in the simulator.

https://github.com/shannah/cn1-codescan/commit/7f18e25bdc50afcff79ac077ec96b4fe6c5494fc

You can download/install the latest here https://github.com/codenameone/CodenameOneLibs/blob/master/cn1libs/cn1-codescan.cn1lib

This will be in Codename One settings soon (next update).

Closing this issue for now.  If you still have problems, I'll reopen it

**Closed by shannah** 2018-10-22 13:06 UTC

**Comment by mwarnett** [comment] 2018-10-22 20:06
My first reaction was that couldn't be it because last time I submitted my apps, Apple rejected them because of the missing ios.NSCameraUsageDescription and I had to resubmit them.

In going back to iOS 12.0 I had to reset my iPod and download my apps again from the app store. Today after I saw this I downloaded the 12.0.1 update again and barcode scanning works.

Pondering that for a while I realized I must still have had the development version of the apps on my iPod, I had never gotten the release version from the app store, they were missing ios.NSCameraUsageDescription

So that was indeed it. Thanks for all your help.
