### ISSUE TITLE
On IOS Display.getInstance().openGallery() filename returned always ends in .jpg

### ISSUE THREAD

**Issue by jeeneeno** [codenameone/CodenameOne#3492] opened 2021-09-04 23:09 UTC
Hi

The call :

Display.getInstance().openGallery()

returns the image file the user has selected from their gallery.

On Android this works ok.

On ios this always seems to return a file ending in .jpg even if it's another file format.

Problem : On ios, if I select a file I know is a .gif file it returns a file called xxxx.jpg

Lianna from CN1 Support  responded to my initial query with this :
"Hi, this works around a different bug with phone orientation but it's possible that we need to apply the workaround conditionally. Please file an issue on this."

Thx 

Surjit

**Comment by shannah** [comment] 2022-02-22 15:37
Duplicate of https://github.com/codenameone/CodenameOne/issues/3493

**Closed by shannah** 2022-02-22 15:37 UTC
