### ISSUE TITLE
IOS 2d arrays broken

### ISSUE THREAD

**Issue by ddyer0** [codenameone/CodenameOne#2168] opened 2017-07-24 23:23 UTC
something is radically wrong with 2d arrays on IOS.  The attached program demonstrates 
the problem.  Compare the result on an IOS build with the simulator or android.

Here's an extra curiosity that may offer a hint.   If built for IOS with ios.debug.archs armv7,
it works correctly

~~~~
package dtest.boardspace;
//
// this version shows a simulator problem; unicode strings display
// as blocks, whereas on real android and ios devices, the results
// are correct.  This may imply that codename1 deployed to desktop
// has a problem too.
//

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

import com.codename1.ui.Graphics;
import com.codename1.ui.layouts.BorderLayout;


public class Dtest  {
    int blob_index[] = {0,0 };
    int blob_size[][] = {{0,0,0},{0,0,0}};
    boolean blobs_valid = true;
    void sweep(int row,int col,int n) 
    {	blob_size[row][col]++;
    	if(n>1) { sweep(row,col,n-1); }
    }
    int scoreForPlayer(int pl,boolean sweep)
    {	blob_index[pl]=0;
    	if(pl==0)
    	{	
    		sweep(pl,blob_index[pl]++,2);
    	}else
    	{
    		sweep(pl,blob_index[pl]++,5);
    	}

    	return(blob_size[pl][0]);
    }

    private Form current;
    @SuppressWarnings("unused")
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");
        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    int loops = 0;

    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi >>0 World");
         current = hi;
        hi.setLayout(new BorderLayout());
        hi.addComponent(BorderLayout.CENTER, new Label("Hi Overlay World 2") {

            @Override
            public void paint(Graphics g) {
                int w = getWidth();
                int h = getHeight();
                g.setColor(0x8f8f9f7f);
                g.fillRect(0,0,w,h);
                g.setColor(0);
                g.drawString("player 0 (should be 2) = "+scoreForPlayer(0,true),110,110);
                g.drawString("player 1 (should be 5) = "+scoreForPlayer(1,true),110,140);
            }

        });
        hi.show();

    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }
}
~~~~

**Comment by codenameone** [comment] 2017-07-25 05:22
I don't think this is a regression it's probably been there a while and not for all 2d array modes. If it is a regression we can try to push it to 3.8 but we've had bad experience with the reliability of some of these changes in the past.

**Comment by ddyer0** [comment] 2017-07-25 06:45
It is possible it has been there for a while.  The previous change that broke 2d arrays was an
attempt to quiet some (probably legitimate) warnings in the 2d array access code you generate.
That change was reverted, but I think the warnings are now gone again.

This problem seems to be specific to code generated for a[x][y]++

**Comment by shannah** [comment] 2018-02-14 14:34
I just tried to build the test case and it works correctly.  Perhaps it was fixed in a previous change.  Can you verify if this is still happening for you?

I was building with xcode 9.2, running in iOS simulator running 11.2

**Comment by ddyer0** [comment] 2018-02-14 17:45
The comment at the top is from a previous test.  Build it for IOS, it still fails.
line 2 of
the display says "player 1 (should be 5) = 1

**Comment by shannah** [comment] 2018-02-14 21:38
It's possible that https://github.com/codenameone/CodenameOne/commit/87b6cb421f1a4b4f8d45cf894b72f779f2e3f793 fixes this issue.  I haven't reproduced the problem myself, so I don't know.  It will be available in next build server update.

**Comment by shannah** [comment] 2018-02-16 13:44
Closing as I can't reproduce, and it was likely fixed by https://github.com/codenameone/CodenameOne/commit/87b6cb421f1a4b4f8d45cf894b72f779f2e3f793

Will reopen if issue is confirmed to persist.

**Comment by ddyer0** [comment] 2018-02-16 18:20
Not fixed by the fix for #2277.  Reopen.

**Comment by shannah** [comment] 2018-02-20 14:28
Still can't reproduce.   Try building with ios.xcode_version=9.2

**Comment by ddyer0** [comment] 2018-02-20 18:25
Here are the codename1 setting I'm using
codename1.android.keystore=
codename1.android.keystoreAlias=
codename1.android.keystorePassword=
codename1.arg.android.debug=false
codename1.arg.android.enableproguard=false
codename1.arg.android.includeGPlayServices=false
codename1.arg.android.release=true
codename1.arg.build.incSources=1
codename1.arg.ios.fastbuild=true
codename1.arg.ios.fileSharingEnabled=true
codename1.arg.ios.interface_orientation=UIInterfaceOrientationPortrait\:UIInterfaceOrientationPortraitUpsideDown\:UIInterfaceOrientationLandscapeLeft\:UIInterfaceOrientationLandscapeRight
codename1.arg.ios.objC=true
codename1.arg.ios.pods.sources=,https\://github.com/CocoaPods/Specs.git
codename1.arg.ios.project_type=ios
codename1.arg.java.version=8
codename1.displayName=Dtest
codename1.icon=icon.png
codename1.ios.appid=N9ZJLP5456.dtest.boardspace
codename1.ios.certificate=
codename1.ios.certificatePassword=
codename1.ios.debug.certificate=G\:\\share\\projects\\ios-certificates\\boardspace-prod\\net_development.p12
codename1.ios.debug.certificatePassword=password
codename1.ios.debug.provision=G\:\\share\\projects\\ios-certificates\\dtest\\Dtest_development.mobileprovision
codename1.ios.provision=
codename1.ios.release.certificate=G\:\\share\\projects\\ios-certificates\\boardspace-prod\\net_distribution.p12
codename1.ios.release.certificatePassword=password
codename1.ios.release.provision=G\:\\share\\projects\\ios-certificates\\dtest\\Dtest_distribution.mobileprovision
codename1.j2me.nativeTheme=nativej2me.res
codename1.languageLevel=5
codename1.mainName=Dtest
codename1.packageName=dtest.boardspace
codename1.rim.certificatePassword=
codename1.rim.signtoolCsk=
codename1.rim.signtoolDb=
codename1.secondaryTitle=Dtest
codename1.vendor=CodenameOne
codename1.version=1.0
libVersion=209

**Comment by ddyer0** [comment] 2018-02-20 18:27
Here's a screenshot just made from a fresh build (ipad2)
![image-1](https://user-images.githubusercontent.com/5963076/36441817-a00c008a-1628-11e8-834d-162c0112198c.jpg)

**Comment by shannah** [comment] 2018-02-20 18:48
Try building with ios.xcode_version=9.2

**Comment by ddyer0** [comment] 2018-02-20 19:00
that fixes it.  Thanks Apple! (eventually they get it right)

**Comment by shannah** [comment] 2018-02-20 19:03
Since we are making 9.2 the default very soon, I'm inclined to "not fix" this one.  Any objections @codenameone ?

**Comment by codenameone** [comment] 2018-02-20 19:05
No. OK, with me.

**Closed by codenameone** 2018-02-20 19:05 UTC
